-- ============================================================
-- Conflict Data Updates: Casualties, Descriptions,
-- Progressive Analysis, and Outcomes
-- Generated 2026-02-12
-- ============================================================

-- ============================================================
-- 1. RUSSIAN REVOLUTION / RUSSIAN CIVIL WAR
-- ============================================================
UPDATE conflicts SET
    casualties_low = 7000000,
    casualties_high = 12000000,
    description = 'The Russian Revolution of 1917 overthrew the Tsarist autocracy and culminated in the Bolshevik seizure of power in October 1917, establishing the world''s first socialist state. The ensuing Russian Civil War (1917-1922) pitted the Red Army of the Bolsheviks against the White Army coalition of monarchists, liberals, and foreign interventionist forces from 14 nations including Britain, France, the United States, and Japan. The conflict devastated the former Russian Empire, with an estimated 7-12 million total deaths from combat, famine, disease, and political repression on all sides. The war ended with a decisive Bolshevik victory, leading to the formation of the Soviet Union in 1922.',
    progressive_analysis = 'The Russian Revolution stands as the most consequential revolutionary event of the 20th century, representing the first successful seizure of state power by the working class. The October Revolution demonstrated that an organized proletariat, guided by revolutionary theory, could overthrow centuries of feudal and capitalist exploitation. The Civil War that followed was fundamentally a class war: the White forces represented the old aristocratic order, the bourgeoisie, and their imperialist backers from 14 capitalist nations who intervened militarily to crush the revolution. The intervention of Western powers exposed the international character of class struggle -- the capitalist powers feared the example of a workers'' state more than anything else. Despite devastating conditions, the Red Army''s victory proved that revolutionary determination could overcome the combined forces of domestic reaction and foreign imperialism. The revolution inspired liberation movements worldwide and established the material basis for decolonization by providing an alternative model to capitalist development.',
    outcome = 'Bolshevik victory. Formation of the Soviet Union in 1922. Establishment of the world''s first socialist state. Foreign interventionist forces expelled. White Army defeated on all fronts by 1920.'
WHERE name LIKE '%Russian Revolution%'
   OR name LIKE '%Russian Civil War%';

-- ============================================================
-- 2. CHINESE CIVIL WAR
-- ============================================================
UPDATE conflicts SET
    casualties_low = 6000000,
    casualties_high = 10000000,
    description = 'The Chinese Civil War (1927-1949) was a prolonged conflict between the Chinese Communist Party (CCP) led by Mao Zedong and the Kuomintang (KMT) Nationalist government led by Chiang Kai-shek. The war began with the Shanghai Massacre of 1927 when the KMT, backed by foreign powers and domestic capitalists, turned on its Communist allies, killing hundreds of thousands of workers and peasants in the White Terror. After the Long March (1934-35), the Japanese invasion (1937-45), and a final phase of civil war (1945-49), the CCP achieved victory. Estimated casualties range from 6-10 million, including military and civilian deaths from combat, starvation, and disease.',
    progressive_analysis = 'The Chinese Civil War represents one of history''s greatest peasant revolutions, in which hundreds of millions of exploited farmers and workers overthrew feudal landlordism and comprador capitalism. The KMT''s White Terror of 1927 -- in which Chiang Kai-shek, backed by Western powers and Shanghai''s criminal underworld, massacred communists and workers -- exposed the class character of the Nationalist regime as a tool of imperialism and domestic reaction. The CCP''s success was rooted in its mass line approach, conducting land reform and empowering peasants who had endured millennia of feudal exploitation. The revolution liberated China from the semi-colonial "century of humiliation" imposed by Western and Japanese imperialism, ending the unequal treaties and foreign concessions that had carved up Chinese sovereignty. The People''s Republic represented the liberation of one-quarter of humanity from feudal and colonial subjugation, fundamentally altering the global balance of power against imperialism.',
    outcome = 'Communist victory. Establishment of the People''s Republic of China on October 1, 1949. KMT forces fled to Taiwan. Land reform redistributed holdings to 300 million peasants. End of semi-colonial status and foreign concessions in China.'
WHERE name LIKE '%Chinese Civil War%';

-- ============================================================
-- 3. SPANISH CIVIL WAR
-- ============================================================
UPDATE conflicts SET
    casualties_low = 500000,
    casualties_high = 1000000,
    description = 'The Spanish Civil War (1936-1939) was fought between the democratically elected Republican government -- supported by socialist, communist, anarchist, and liberal forces -- and the Nationalist insurgency led by General Francisco Franco, backed by Nazi Germany and Fascist Italy. An estimated 500,000 to 1,000,000 people died, including approximately 200,000 in combat, 150,000 civilians from political violence, and tens of thousands from disease and malnutrition caused by the Nationalist blockade. The Nationalists executed over 100,000 people during the war and another 50,000 after it ended. International volunteers formed the International Brigades to defend the Republic, while Western democracies maintained a policy of non-intervention that effectively aided Franco.',
    progressive_analysis = 'The Spanish Civil War was the defining anti-fascist struggle of the interwar period and a critical defeat for the international working class. The Spanish Republic represented a genuine experiment in popular democracy, workers'' self-management, and agrarian reform that threatened the entrenched power of the landed aristocracy, the Catholic Church hierarchy, and industrial capitalists. The revolution within the war -- particularly in Catalonia and Aragon where workers collectivized factories and peasants seized land -- demonstrated the creative potential of the working class to reorganize society. Franco''s coup was backed by the full military might of Nazi Germany and Fascist Italy, while the Western "democracies" imposed an arms embargo that strangled the Republic. This non-intervention policy revealed the class solidarity of the capitalist powers: they preferred fascism to the possibility of a workers'' revolution. The International Brigades, composed of 35,000 volunteers from 53 countries, represented the highest expression of proletarian internationalism. Spain''s tragedy foreshadowed World War II and demonstrated that fascism, when not confronted by organized working-class power, leads to catastrophe.',
    outcome = 'Nationalist victory. Establishment of Franco''s fascist dictatorship (1939-1975). Mass repression with over 50,000 executed after the war. Hundreds of thousands imprisoned or exiled. Republican reforms reversed. The dictatorship lasted until Franco''s death in 1975.'
WHERE name LIKE '%Spanish Civil War%';

-- ============================================================
-- 4. CUBAN REVOLUTION
-- ============================================================
UPDATE conflicts SET
    casualties_low = 2000,
    casualties_high = 5000,
    description = 'The Cuban Revolution (1953-1959) was an armed revolt led by Fidel Castro, Che Guevara, and the 26th of July Movement against the US-backed military dictatorship of Fulgencio Batista. Beginning with the failed attack on the Moncada Barracks in 1953 and the subsequent guerrilla campaign launched from the Sierra Maestra mountains in 1956, the revolutionary forces grew from a small band of fighters to a mass movement. The Batista regime, responsible for an estimated 1,000-20,000 political killings, collapsed on January 1, 1959. Combat deaths during the revolutionary war are estimated at 2,000-5,000. The revolution established a socialist government that implemented sweeping land reform, nationalization of industries, and universal healthcare and education.',
    progressive_analysis = 'The Cuban Revolution demonstrated that a small, determined revolutionary force rooted in the peasantry and working class could defeat a US-backed military dictatorship. Batista''s regime was a textbook case of neo-colonial exploitation: Cuba functioned as a playground for American capital, with US corporations controlling sugar production, utilities, and banking while the majority of Cubans lived in poverty. The revolution''s significance extends far beyond Cuba''s borders -- it proved that Latin American nations could break free from US imperial domination, inspiring liberation movements across the continent and the Global South. Post-revolution achievements in healthcare, education, and literacy -- including the elimination of illiteracy in one year and the development of a world-class medical system -- demonstrated what becomes possible when resources are directed toward human needs rather than private profit. Cuba''s internationalist commitment, sending doctors and teachers to dozens of nations and military support to African liberation movements (notably Angola), represents an extraordinary example of socialist solidarity transcending national boundaries.',
    outcome = 'Revolutionary victory. Overthrow of Batista dictatorship on January 1, 1959. Establishment of socialist government. Land reform, nationalization of industry, universal healthcare and education. Elimination of illiteracy. Cuba became a symbol of anti-imperialist resistance in Latin America.'
WHERE name LIKE '%Cuban Revolution%';

-- ============================================================
-- 5. NICARAGUAN REVOLUTION
-- ============================================================
UPDATE conflicts SET
    casualties_low = 50000,
    casualties_high = 78000,
    description = 'The Nicaraguan Revolution (1978-1990) encompassed the Sandinista uprising against the Somoza family dictatorship (1978-1979) and the subsequent Contra War (1980s). The Sandinista National Liberation Front (FSLN) led a broad-based insurrection that toppled the 43-year Somoza dynasty in July 1979. Approximately 50,000 Nicaraguans died during the initial revolution. The Reagan administration then funded, trained, and directed the Contra rebels to destabilize the Sandinista government, resulting in an additional 30,000 deaths. Total casualties across both phases are estimated at 50,000-78,000, with 150,000 displaced.',
    progressive_analysis = 'The Nicaraguan Revolution was a defining moment in Central American history, demonstrating that popular insurrection could overthrow a brutal, US-backed dynasty. The Somoza family had ruled Nicaragua as a personal fiefdom for over four decades with full American support -- as Roosevelt reportedly said, "He may be a son of a bitch, but he''s our son of a bitch." The Sandinista victory represented a triumph of the Nicaraguan people''s will to self-determination against decades of imperialist domination. The revolution''s achievements -- mass literacy campaigns that reduced illiteracy from 50% to 12%, land reform, healthcare expansion, and democratic participation -- demonstrated the transformative potential of revolutionary governance. The subsequent Contra War was a textbook case of US imperialist aggression: the CIA organized, funded, and directed a terrorist campaign specifically designed to destroy these social gains. The International Court of Justice found the US guilty of violating international law for its support of the Contras and mining of Nicaraguan harbors, yet the US refused to recognize the court''s jurisdiction -- exposing the hypocrisy of imperialist "rule of law" rhetoric.',
    outcome = 'Sandinista victory over Somoza in 1979. Social reforms including literacy campaigns, land reform, and healthcare expansion. US-backed Contra War caused massive destruction. FSLN lost 1990 elections under pressure of economic warfare and military destabilization, but remained a major political force.'
WHERE name LIKE '%Nicaraguan Revolution%'
   OR name LIKE '%Nicaraguan Civil War%'
   OR name LIKE '%Contra War%';

-- ============================================================
-- 6. ALGERIAN WAR OF INDEPENDENCE
-- ============================================================
UPDATE conflicts SET
    casualties_low = 400000,
    casualties_high = 1500000,
    description = 'The Algerian War of Independence (1954-1962) was a brutal anti-colonial struggle waged by the National Liberation Front (FLN) against French colonial rule. After 132 years of French colonization that dispossessed the Algerian population and established a settler-colonial system privileging one million European settlers over nine million Algerians, the FLN launched an armed insurrection on November 1, 1954. France responded with massive military force, including systematic torture, forced relocations of over two million Algerians, and aerial bombardment. Casualties are estimated between 400,000 and 1.5 million Algerians killed, with the Algerian government citing 1.5 million martyrs. French military losses were approximately 17,456 dead and 65,000 wounded. An additional 50,000-150,000 Harki collaborators were killed in post-war reprisals.',
    progressive_analysis = 'The Algerian War of Independence was among the most significant anti-colonial struggles of the 20th century, exposing the inherent violence of settler colonialism. For 132 years, France had subjected Algeria to a system of colonial exploitation in which one million European settlers controlled the best land and economic resources while nine million Algerians were relegated to second-class status in their own country. The French "civilizing mission" was nothing more than a pretext for systematic dispossession and racial subjugation. The war itself revealed the true face of colonial "democracy": France employed systematic torture (documented by Henri Alleg in "La Question"), forced population transfers of over 2 million Algerians into concentration camps, and the complete destruction of rural communities. Frantz Fanon''s analysis of the Algerian revolution, particularly in "The Wretched of the Earth," provided the theoretical framework for understanding colonial violence and the necessity of armed resistance -- influencing liberation movements worldwide. The FLN''s victory demonstrated that a colonized people, though outgunned and outmanned, could defeat a major European power through determined resistance, fundamentally accelerating the process of African decolonization.',
    outcome = 'Algerian independence on July 5, 1962, following the Evian Accords. End of 132 years of French colonial rule. Mass exodus of European settlers (pieds-noirs). Establishment of the People''s Democratic Republic of Algeria. The war accelerated decolonization across Africa and inspired liberation movements worldwide.'
WHERE name LIKE '%Algerian War%'
   OR name LIKE '%Algerian Independence%';

-- ============================================================
-- 7. ANGOLAN WAR OF INDEPENDENCE
-- ============================================================
UPDATE conflicts SET
    casualties_low = 30000,
    casualties_high = 100000,
    description = 'The Angolan War of Independence (1961-1974) was an anti-colonial struggle against Portuguese colonial rule, waged primarily by three liberation movements: the MPLA (People''s Movement for the Liberation of Angola), FNLA (National Front for the Liberation of Angola), and UNITA (National Union for the Total Independence of Angola). The war began with uprisings in 1961, including the Baixa de Cassanje revolt and the March 1961 insurrections in northern Angola. Portuguese forces responded with massive repression, killing an estimated 20,000 civilians in the northern provinces in the early months alone. Total casualties are estimated at 30,000-100,000, including approximately 3,000 Portuguese soldiers killed. The war ended with the Portuguese Carnation Revolution of 1974.',
    progressive_analysis = 'The Angolan War of Independence was a critical front in the broader struggle against Portuguese colonialism, which represented one of the most exploitative and extractive colonial systems in Africa. Portugal, itself a semi-peripheral European economy, maintained its African colonies as sources of forced labor and raw materials well into the 1960s -- the forced cotton cultivation system in the Baixa de Cassanje region was essentially a continuation of slavery. The MPLA''s Marxist-Leninist orientation reflected the understanding that national liberation required not just political independence but a fundamental transformation of the colonial economic structures that extracted Angola''s wealth for foreign benefit. The war demonstrated the interconnected nature of anti-colonial struggles: the simultaneous liberation wars in Angola, Mozambique, and Guinea-Bissau stretched Portuguese military resources to the breaking point, ultimately triggering the progressive military coup in Portugal itself. Cuba''s subsequent military intervention in Angola against South African invasion forces was one of the most remarkable acts of internationalist solidarity in modern history, helping defend Angolan sovereignty against apartheid aggression.',
    outcome = 'Portuguese withdrawal following the Carnation Revolution of 1974. Angolan independence declared November 11, 1975. However, independence was immediately followed by civil war between MPLA, FNLA, and UNITA, with extensive foreign intervention from Cuba, South Africa, the US, and the USSR.'
WHERE name LIKE '%Angolan War of Independence%'
   OR name LIKE '%Angola%Independence%';

-- ============================================================
-- 8. MOZAMBIQUE WAR OF INDEPENDENCE
-- ============================================================
UPDATE conflicts SET
    casualties_low = 30000,
    casualties_high = 50000,
    description = 'The Mozambican War of Independence (1964-1974) was an armed conflict between the Front for the Liberation of Mozambique (FRELIMO) and Portuguese colonial forces. FRELIMO, founded in 1962 under the leadership of Eduardo Mondlane and later Samora Machel, launched its guerrilla campaign on September 25, 1964. The Portuguese responded with large-scale military operations including Operation Gordian Knot (1970). Civilian casualties are estimated at 30,000-50,000 from Portuguese military actions, guerrilla operations, and indirect effects such as famine. The war ended with the Carnation Revolution in Portugal in 1974, leading to Mozambican independence in 1975.',
    progressive_analysis = 'The Mozambican liberation struggle exemplified how anti-colonial resistance could simultaneously fight for national independence and social transformation. FRELIMO''s program went beyond mere political independence, establishing liberated zones where land reform, literacy campaigns, healthcare, and women''s emancipation were implemented even during the war -- prefiguring the society the movement sought to build. Under Portuguese colonialism, Mozambicans were subjected to forced labor (chibalo), forced crop cultivation, and a racial caste system that denied them basic rights and education. Eduardo Mondlane''s assassination by a Portuguese letter bomb in 1969 demonstrated the lengths to which colonial powers would go to crush liberation movements. The war''s success was inseparable from the broader context of Portuguese colonial wars in Africa: the combined pressure of simultaneous liberation struggles in Angola, Mozambique, and Guinea-Bissau made Portuguese colonialism unsustainable, contributing directly to the radicalization of Portuguese soldiers who eventually overthrew the fascist Estado Novo regime. FRELIMO''s victory demonstrated that colonial exploitation could be defeated through organized popular resistance.',
    outcome = 'FRELIMO victory following the Carnation Revolution in Portugal. Mozambican independence on June 25, 1975. Establishment of a socialist-oriented government under Samora Machel. Land reform and nationalization programs implemented, though followed by destabilizing civil war backed by Rhodesia and apartheid South Africa.'
WHERE name LIKE '%Mozambi%War of Independence%'
   OR name LIKE '%Mozambi%Independence%';

-- ============================================================
-- 9. GUINEA-BISSAU WAR OF INDEPENDENCE
-- ============================================================
UPDATE conflicts SET
    casualties_low = 8000,
    casualties_high = 15000,
    description = 'The Guinea-Bissau War of Independence (1963-1974) was an armed struggle led by the African Party for the Independence of Guinea and Cape Verde (PAIGC) against Portuguese colonial rule. Under the leadership of Amilcar Cabral, one of Africa''s most influential revolutionary theorists, the PAIGC waged a highly effective guerrilla campaign that eventually controlled over two-thirds of the country. Approximately 6,000 of 10,000 PAIGC fighters were killed, along with approximately 1,875 Portuguese soldiers. Total casualties including civilians are estimated at 8,000-15,000. Cabral was assassinated in 1973, but Guinea-Bissau unilaterally declared independence on September 24, 1973, recognized by Portugal after the Carnation Revolution in 1974.',
    progressive_analysis = 'The Guinea-Bissau liberation struggle produced one of the most sophisticated revolutionary theorists of the anti-colonial era in Amilcar Cabral, whose writings on culture, class, and national liberation remain essential reading for understanding the dynamics of colonial resistance. Cabral''s insistence that "national liberation is necessarily an act of culture" deepened the understanding of colonialism as not just political and economic domination but a comprehensive assault on the colonized people''s identity and self-determination. The PAIGC''s approach was remarkable for its integration of military struggle with social transformation: in liberated zones, the movement established schools, clinics, and democratic governance structures, creating a functioning counter-state within colonial territory. The war demonstrated that even a small colonized nation could defeat a European power through popular mobilization and revolutionary organization. Cabral''s assassination in 1973 -- widely believed to have been orchestrated by Portuguese intelligence -- was a testament to the threat his revolutionary vision posed to colonialism. The PAIGC''s success, along with the concurrent wars in Angola and Mozambique, directly precipitated the fall of the Portuguese fascist regime.',
    outcome = 'PAIGC victory. Guinea-Bissau unilaterally declared independence September 24, 1973, recognized by over 80 nations. Portugal formally recognized independence on September 10, 1974, following the Carnation Revolution. The war contributed directly to the fall of Portuguese fascism.'
WHERE name LIKE '%Guinea%Bissau%'
   OR name LIKE '%Guinea-Bissau%';

-- ============================================================
-- 10. CONGO CRISIS
-- ============================================================
UPDATE conflicts SET
    casualties_low = 95000,
    casualties_high = 100000,
    description = 'The Congo Crisis (1960-1965) was a period of political upheaval and conflict in the newly independent Republic of the Congo (now the Democratic Republic of the Congo). Following independence from Belgium on June 30, 1960, Prime Minister Patrice Lumumba sought genuine sovereignty over Congo''s vast mineral wealth. Belgian-backed secession in mineral-rich Katanga province, combined with a CIA-backed coup by Colonel Mobutu, led to Lumumba''s capture, torture, and execution on January 17, 1961 -- with the complicity of Belgian, American, and UN officials. An estimated 100,000 people died during the crisis, including from regional secessionist conflicts, mercenary operations, and mass atrocities. The crisis ended with Mobutu''s seizure of full power in 1965.',
    progressive_analysis = 'The Congo Crisis represents one of the most egregious cases of neo-colonial intervention in post-independence Africa. Patrice Lumumba, the Congo''s first democratically elected leader, was overthrown and murdered because he dared to assert genuine sovereignty over his nation''s resources -- particularly the uranium, cobalt, and copper that Western powers considered too strategically valuable to leave under African control. The assassination of Lumumba was orchestrated by Belgian intelligence with the active support of the CIA and the complicity of the United Nations -- exposing how international institutions serve imperialist interests. The subsequent installation of Mobutu as a pliant dictator demonstrated the pattern of neo-colonialism: formal political independence was meaningless without economic sovereignty. Mobutu''s 32-year kleptocratic dictatorship, propped up by Western governments, systematically looted the Congo''s wealth while the population lived in misery -- the quintessential example of how imperialism operates through local compradors. Lumumba''s murder remains a foundational crime of the neo-colonial era, and his vision of genuine African independence continues to inspire resistance against the exploitation of the continent''s resources by foreign capital.',
    outcome = 'Defeat of progressive forces. Assassination of Patrice Lumumba on January 17, 1961. Mobutu seized full power in 1965, establishing a 32-year US-backed dictatorship. Katanga secession eventually ended but genuine sovereignty over mineral wealth was denied. The Congo''s trajectory of exploitation and conflict traces directly to this crisis.'
WHERE name LIKE '%Congo Crisis%'
   OR name LIKE '%Congo 1960%';

-- ============================================================
-- 11. MAU MAU UPRISING
-- ============================================================
UPDATE conflicts SET
    casualties_low = 20000,
    casualties_high = 100000,
    description = 'The Mau Mau Uprising (1952-1960) was an armed rebellion by the Kenya Land and Freedom Army, primarily composed of Kikuyu people, against British colonial rule in Kenya. The uprising was rooted in the colonial dispossession of African land by white settlers in the "White Highlands." The British response included declaring a state of emergency, mass detention of over 1.5 million Kikuyu in concentration camp-like "villages," systematic torture, sexual violence, and extrajudicial killings. Estimates of those killed range from 20,000 to over 100,000, with historian Caroline Elkins estimating at least 70,000 and John Blacker estimating 50,000 -- half of them children under ten. Only 32 white settlers and 200 British soldiers were killed in comparison.',
    progressive_analysis = 'The Mau Mau Uprising was a direct response to one of the most blatant cases of colonial land theft in Africa. British settlers had seized the most fertile land in the "White Highlands," reducing the Kikuyu and other peoples to landless laborers on their own ancestral territories. The uprising was fundamentally a peasant land revolution -- the rebels called themselves the Kenya Land and Freedom Army, making their class objectives explicit. The British response revealed the inherent brutality of colonialism: 1.5 million people were forced into concentration camps, systematic torture was employed (including castration and sexual violence, as documented by historian Caroline Elkins), and collective punishment was imposed on entire communities. The British government long suppressed evidence of these atrocities, and it was not until 2013 that the UK government agreed to compensate survivors. The massive disproportion in casualties -- tens of thousands of Africans killed versus 32 white settlers -- exposes the lie of colonial "civilization." While the uprising was militarily defeated, it made British colonial rule politically and morally untenable, directly accelerating Kenyan independence in 1963.',
    outcome = 'Military defeat of the uprising but political victory for independence. State of emergency ended in 1960. Kenya achieved independence in 1963 under Jomo Kenyatta. The uprising made continued colonial rule untenable despite British military superiority. In 2013, the British government formally acknowledged torture and abuse of detainees.'
WHERE name LIKE '%Mau Mau%';

-- ============================================================
-- 12. INDONESIAN NATIONAL REVOLUTION
-- ============================================================
UPDATE conflicts SET
    casualties_low = 97000,
    casualties_high = 200000,
    description = 'The Indonesian National Revolution (1945-1949) was the armed struggle for independence from the Netherlands following the Japanese occupation of World War II. After Sukarno and Hatta declared independence on August 17, 1945, the returning Dutch attempted to reimpose colonial rule with British military support. The conflict included conventional battles, guerrilla warfare, and diplomatic negotiations. Indonesian casualties are estimated at 97,000-200,000, including both military and civilian deaths. Over 4,000 Dutch soldiers and 980 British/Indian soldiers were killed. Seven million people were displaced. The conflict ended with Dutch recognition of Indonesian sovereignty in December 1949.',
    progressive_analysis = 'The Indonesian National Revolution was one of the great anti-colonial struggles of the post-World War II era, demonstrating that the age of European colonialism was over. The Dutch had exploited the Indonesian archipelago for 350 years, extracting enormous wealth through the brutal "Cultivation System" that forced Indonesian peasants to grow export crops while their communities starved. The revolution''s timing was significant: after the Japanese had shattered the myth of European racial superiority and military invincibility, the people of Indonesia refused to accept the return of colonial masters. The Dutch attempt to reconquer Indonesia -- euphemistically called "police actions" -- exposed the violence inherent in maintaining colonial rule and drew international condemnation. The revolution united diverse ethnic and social groups across the vast archipelago in a common struggle against imperialism, forging a national consciousness from colonial subjugation. Indonesia''s independence fundamentally reshaped the geopolitics of Southeast Asia and, along with India''s independence, signaled that the era of direct colonial rule by European powers was finished. The revolution later inspired Sukarno''s role in founding the Non-Aligned Movement at the Bandung Conference of 1955.',
    outcome = 'Indonesian independence recognized by the Netherlands in December 1949 through the Dutch-Indonesian Round Table Conference. Establishment of the Republic of Indonesia under President Sukarno. End of 350 years of Dutch colonial rule. Indonesia became a founding leader of the Non-Aligned Movement.'
WHERE name LIKE '%Indonesian National Revolution%'
   OR name LIKE '%Indonesian War of Independence%'
   OR name LIKE '%Indonesian Independence%';

-- ============================================================
-- 13. INDIAN INDEPENDENCE MOVEMENT CONFLICTS
-- ============================================================
UPDATE conflicts SET
    casualties_low = 200000,
    casualties_high = 2000000,
    description = 'The Indian independence movement encompassed decades of resistance against British colonial rule, culminating in independence and partition in 1947. Key violent episodes included the Jallianwala Bagh Massacre of 1919 (379 officially killed, likely more), the Quit India Movement of 1942 (over 1,060 demonstrators killed), and numerous other instances of colonial repression. The Partition of India in 1947, a direct consequence of colonial divide-and-rule policies, resulted in an estimated 200,000 to 2,000,000 deaths in communal violence and the displacement of 15 million people across the hastily drawn borders between India and Pakistan. The independence movement combined mass non-violent resistance with armed revolutionary activity.',
    progressive_analysis = 'The Indian independence movement represents the largest anti-colonial struggle in human history by the sheer number of people involved. British colonialism in India was a system of systematic extraction that deindustrialized one of the world''s wealthiest civilizations: India''s share of global GDP fell from 24% in 1700 to under 4% by independence. The British deliberately destroyed Indian textile manufacturing to create a captive market, imposed famines that killed tens of millions (including the Bengal Famine of 1943 that killed 3 million under Churchill''s watch), and maintained racial supremacy through violence exemplified by the Jallianwala Bagh Massacre. While Gandhi''s non-violent resistance is often celebrated, the movement also included revolutionary socialists like Bhagat Singh, who understood that political independence without economic transformation would perpetuate exploitation under different masters. The catastrophic Partition -- engineered by the departing British through deliberate haste and cynical manipulation of communal divisions they had cultivated for decades -- demonstrated the final cruelty of colonialism: even in leaving, the empire ensured lasting division and conflict. The communal violence of Partition, killing hundreds of thousands and displacing millions, was the direct product of colonial divide-and-rule strategies.',
    outcome = 'Indian independence on August 15, 1947. Partition into India and Pakistan with catastrophic communal violence. End of nearly 200 years of British colonial rule. 15 million displaced in the largest mass migration in history. The independence movement inspired anti-colonial struggles across Asia and Africa.'
WHERE name LIKE '%Indian independence%'
   OR name LIKE '%India%Partition%'
   OR name LIKE '%Quit India%';

-- ============================================================
-- 14. HAITIAN REVOLUTION
-- ============================================================
UPDATE conflicts SET
    casualties_low = 200000,
    casualties_high = 350000,
    description = 'The Haitian Revolution (1791-1804) was the only successful large-scale slave revolt in history, in which enslaved Africans in the French colony of Saint-Domingue overthrew the plantation system and established the independent Republic of Haiti. The revolution began with a slave uprising in August 1791, led by figures including Toussaint Louverture, Jean-Jacques Dessalines, and Henri Christophe. The revolutionaries defeated the French colonial forces, a Spanish invasion, a British expeditionary force of 25,000, and ultimately Napoleon''s massive 1802 expedition of over 40,000 troops. An estimated 200,000-350,000 Haitians and 50,000 European soldiers died, many from yellow fever. Haiti declared independence on January 1, 1804.',
    progressive_analysis = 'The Haitian Revolution is the most radical revolutionary event in the history of the Americas and arguably the most consequential slave revolt in human history. Enslaved Africans, subjected to the most brutal plantation system in the Caribbean -- where the average slave survived only seven years -- rose up and not only liberated themselves but defeated the three most powerful European empires of the age: France, Spain, and Britain. The revolution exposed the fundamental hypocrisy of the French Revolution''s "liberty, equality, fraternity," which was never intended to apply to Black people. When Napoleon sent 40,000 troops to reimpose slavery, the Haitian revolutionaries destroyed them. The establishment of the first Black republic in 1804 terrified slaveholding societies throughout the Americas. The Western powers'' response was to impose a devastating economic embargo, and in 1825, France extorted Haiti for 150 million gold francs as "compensation" to former slaveholders -- a debt that crippled Haiti''s development for over a century. The ongoing impoverishment of Haiti is not a failure of self-governance but the direct result of imperialist punishment for the crime of Black self-liberation. The Haitian Revolution proved that the enslaved were not passive victims but historical agents capable of the highest form of revolutionary action.',
    outcome = 'Complete revolutionary victory. Establishment of the Republic of Haiti on January 1, 1804 -- the first independent Black nation and the first successful large-scale slave revolt. Abolition of slavery. Defeat of French, British, and Spanish military forces. However, Haiti was subjected to international isolation and a crippling indemnity to France that undermined its development for generations.'
WHERE name LIKE '%Haitian Revolution%'
   OR name LIKE '%Haiti%';

-- ============================================================
-- 15. PARIS COMMUNE
-- ============================================================
UPDATE conflicts SET
    casualties_low = 6000,
    casualties_high = 20000,
    description = 'The Paris Commune (March 18 - May 28, 1871) was a revolutionary socialist government that controlled Paris for 72 days following France''s defeat in the Franco-Prussian War. The Commune implemented radical democratic reforms including workers'' self-management, separation of church and state, remission of rents, women''s rights, and the abolition of night work in bakeries. The French government at Versailles, with Prussian acquiescence, launched a military assault on Paris culminating in the Semaine Sanglante (Bloody Week, May 21-28, 1871). Between 6,000 and 20,000 Communards were killed, with estimates varying significantly among historians. An additional 43,000 were arrested, with 13,500 convicted, 95 sentenced to death, and 1,169 deported to New Caledonia.',
    progressive_analysis = 'The Paris Commune was the first instance in history of the working class seizing political power and attempting to construct a new form of democratic governance based on popular sovereignty and workers'' self-management. In just 72 days, the Commune enacted more progressive legislation than the preceding century of bourgeois government: elected officials were paid workers'' wages and subject to instant recall, the standing army was replaced by a people''s militia, church and state were separated, and workplace democracy was implemented. Marx recognized the Commune as the first "dictatorship of the proletariat" -- not a dictatorship in the usual sense, but a government genuinely of, by, and for the working class. The savage repression during the Semaine Sanglante, in which the Versailles government slaughtered thousands of workers, women, and children, demonstrated the ruling class''s willingness to resort to unlimited violence when its power is threatened. That the French bourgeoisie collaborated with the Prussian occupiers to crush their own workers reveals the fundamental truth of class politics: the ruling class will always prefer foreign invasion to working-class power. The Commune''s lessons -- both its achievements and its tactical errors -- informed every subsequent revolutionary movement.',
    outcome = 'Military defeat of the Commune during the Semaine Sanglante (May 21-28, 1871). Between 6,000 and 20,000 Communards killed. Mass arrests, trials, and deportations. Despite its defeat, the Commune became the foundational reference point for the international socialist and communist movements, directly influencing the Russian Revolution and all subsequent workers'' revolutions.'
WHERE name LIKE '%Paris Commune%';

-- ============================================================
-- 16. HUNGARIAN REVOLUTION 1956
-- ============================================================
UPDATE conflicts SET
    casualties_low = 2500,
    casualties_high = 3000,
    description = 'The Hungarian Revolution of 1956 (October 23 - November 10, 1956) was a nationwide revolt against the Stalinist government of Hungary and Soviet domination. Beginning as a student-led demonstration in Budapest, it quickly evolved into a mass uprising with workers'' councils seizing factories and neighborhoods. Revolutionary Prime Minister Imre Nagy announced Hungary''s withdrawal from the Warsaw Pact. The Soviet Union responded with a massive military invasion on November 4, deploying 31,550 troops and over 1,000 tanks. Approximately 2,500-3,000 Hungarians and 699 Soviet soldiers were killed. Over 200,000 Hungarians fled as refugees. In the aftermath, 229 people were executed, including Nagy, and 22,000 were imprisoned.',
    progressive_analysis = 'The Hungarian Revolution of 1956 represents a complex and contested event in socialist history. From one perspective, it was a genuine workers'' uprising against bureaucratic Stalinism -- the workers'' councils that emerged spontaneously across Hungary represented an authentic expression of socialist democracy from below, demanding not a return to capitalism but genuine workers'' control and self-management. The revolution exposed the contradictions of Soviet-style socialism, in which a bureaucratic elite claimed to rule in the name of the working class while suppressing actual working-class self-organization. However, the revolution also contained counter-revolutionary elements seeking to restore capitalism and Western alignment. The Soviet intervention, while preventing potential NATO exploitation of the situation, came at an enormous cost to socialist legitimacy and demonstrated that socialism imposed by tanks rather than built by workers'' own initiative cannot sustain itself. The tragedy of 1956 should be understood as a call for genuine socialist democracy -- not as a vindication of capitalism, but as evidence that the working class must control its own revolutionary process.',
    outcome = 'Soviet military suppression of the revolution. Janos Kadar installed as head of a Soviet-aligned government. 229 people executed including Prime Minister Imre Nagy. 22,000 imprisoned. Over 200,000 fled as refugees. The uprising significantly damaged Soviet prestige internationally and contributed to the eventual reform movements that led to 1989.'
WHERE name LIKE '%Hungarian Revolution%'
   OR name LIKE '%Hungarian Uprising%'
   OR name LIKE '%Hungary 1956%';

-- ============================================================
-- 17. PRAGUE SPRING / WARSAW PACT INVASION
-- ============================================================
UPDATE conflicts SET
    casualties_low = 137,
    casualties_high = 500,
    description = 'The Prague Spring and subsequent Warsaw Pact invasion (1968) began as a reform movement within the Czechoslovak Communist Party under Alexander Dubcek, who sought "socialism with a human face" -- including freedom of the press, freedom of speech, and greater political pluralism while maintaining socialist economic structures. On August 20-21, 1968, approximately 250,000 Warsaw Pact troops (rising to 500,000) from the Soviet Union, Poland, Hungary, and Bulgaria invaded Czechoslovakia in Operation Danube. The invasion killed 137 Czechoslovak civilians and injured over 500. The reforms were reversed under the policy of "normalization" that imposed two decades of political repression.',
    progressive_analysis = 'The Prague Spring represents one of the most significant attempts to develop a democratic, humanistic form of socialism, and its suppression was a tragedy for the international left. Dubcek''s program of "socialism with a human face" sought to address the legitimate aspirations of the Czechoslovak people for political freedom, cultural expression, and democratic participation -- all within a socialist framework. The Action Programme did not seek to restore capitalism or leave the socialist camp, but to demonstrate that socialism and democracy were not only compatible but mutually reinforcing. The Soviet-led invasion, justified by the Brezhnev Doctrine of "limited sovereignty," was a catastrophic act of bureaucratic self-preservation that dealt a devastating blow to socialism''s global credibility. By crushing a reform movement that could have revitalized socialist democracy, the Soviet leadership ensured that the contradictions of bureaucratic socialism would eventually lead to complete collapse rather than democratic renewal. The invasion proved that the primary obstacle to genuine socialism in Eastern Europe was not Western imperialism but the Soviet bureaucracy''s determination to maintain its monopoly of power at any cost.',
    outcome = 'Warsaw Pact military occupation of Czechoslovakia. Reforms reversed under "normalization" policy. Dubcek replaced by Gustav Husak. Two decades of political repression followed. The invasion deeply damaged international communist credibility and radicalized Western leftist movements. The suppressed democratic aspirations resurfaced in the Velvet Revolution of 1989.'
WHERE name LIKE '%Prague Spring%'
   OR name LIKE '%Warsaw Pact%Czechoslovakia%'
   OR name LIKE '%Czechoslovakia 1968%';

-- ============================================================
-- 18. CHILEAN COUP 1973
-- ============================================================
UPDATE conflicts SET
    casualties_low = 3000,
    casualties_high = 40000,
    description = 'The Chilean coup d''etat of September 11, 1973, was a US-backed military overthrow of the democratically elected socialist government of President Salvador Allende. The military junta led by General Augusto Pinochet bombed the presidential palace, La Moneda, and Allende died during the assault. In the immediate aftermath, over 1,260 people were killed by security forces through the end of 1973. During the subsequent 17-year dictatorship (1973-1990), approximately 3,065 people were killed or disappeared and over 40,000 were tortured, according to official truth commission findings. The coup was actively supported by the CIA and the Nixon administration, which had worked to destabilize Allende''s government through economic warfare and covert operations.',
    progressive_analysis = 'The Chilean coup of 1973 is one of the most important events in the history of the Latin American left, demonstrating the limits of the "peaceful road to socialism" and the lengths to which imperialism will go to prevent democratic socialist transformation. Salvador Allende''s Popular Unity government attempted to build socialism through constitutional, democratic means -- nationalizing copper mines (Chile''s main resource, controlled by US corporations), expanding healthcare and education, and redistributing land. The US response was to "make the economy scream" (Nixon''s words), organizing economic sabotage, funding right-wing media and opposition parties, and ultimately directing the military coup. The destruction of Chilean democracy revealed a fundamental truth: the ruling class and its imperial backers will never accept the democratic verdict when it threatens their economic interests. Pinochet''s Chile then became the laboratory for neoliberalism under Milton Friedman''s "Chicago Boys," imposing privatization, deregulation, and austerity that devastated the working class -- demonstrating the intimate connection between authoritarian repression and capitalist "free market" economics. The murder of Victor Jara, Pablo Neruda''s suspicious death, and the torture of tens of thousands were the true cost of neoliberal capitalism.',
    outcome = 'Overthrow of Allende''s democratic socialist government. Establishment of Pinochet military dictatorship (1973-1990). Over 3,000 killed or disappeared, 40,000 tortured, 200,000 exiled. Neoliberal economic restructuring under the Chicago Boys. Chile became the first testing ground for neoliberal economic policy. Democracy restored through 1988 plebiscite and 1990 transition.'
WHERE name LIKE '%Chilean coup%'
   OR name LIKE '%Chile 1973%'
   OR name LIKE '%Chile%coup%';

-- ============================================================
-- 19. PORTUGUESE CARNATION REVOLUTION
-- ============================================================
UPDATE conflicts SET
    casualties_low = 4,
    casualties_high = 5,
    description = 'The Carnation Revolution (April 25, 1974) was a largely bloodless military coup in Lisbon that overthrew the Estado Novo authoritarian regime, which had ruled Portugal for 48 years. The coup was led by the Armed Forces Movement (MFA), composed primarily of junior military officers radicalized by the colonial wars in Africa. Only 4-5 people were killed during the revolution -- four civilians shot by the secret police (PIDE/DGS) and one PIDE agent. The revolution immediately ended Portuguese colonial wars in Africa, leading to the independence of Angola, Mozambique, Guinea-Bissau, Cape Verde, and Sao Tome and Principe. The subsequent Revolutionary Process (PREC) saw widespread worker occupations, land reform, and nationalization.',
    progressive_analysis = 'The Carnation Revolution is one of the most remarkable revolutionary events of the 20th century, demonstrating that even within a fascist military, progressive forces can emerge when the contradictions of imperialism become unbearable. The MFA officers who overthrew the Estado Novo were radicalized not by abstract ideology but by the concrete experience of fighting unjust colonial wars -- they saw firsthand that the liberation movements in Africa were fighting for legitimate goals and that Portugal''s colonial enterprise was morally bankrupt and economically unsustainable. The revolution''s aftermath -- the PREC period of 1974-75 -- was one of the most vibrant experiments in popular democracy in European history: workers occupied and self-managed factories, agricultural laborers seized latifundia estates in the Alentejo, soldiers'' committees democratized the military, and neighborhood commissions organized direct democracy. The revolution simultaneously liberated Portugal from fascism and the African colonies from colonial rule, demonstrating the interconnection between domestic oppression and imperial exploitation -- Portuguese workers and African subjects were both victims of the same authoritarian-capitalist system. The revolution''s containment and the subsequent "normalization" that prevented deeper social transformation remain subjects of debate on the left.',
    outcome = 'Overthrow of the 48-year Estado Novo fascist dictatorship. End of Portuguese colonial wars. Independence of Angola, Mozambique, Guinea-Bissau, Cape Verde, and Sao Tome and Principe. Worker occupations, land reform, and nationalization during the PREC period. Transition to parliamentary democracy. One of the most bloodless revolutions in history with only 4-5 deaths.'
WHERE name LIKE '%Carnation Revolution%'
   OR name LIKE '%Portuguese Revolution%'
   OR name LIKE '%Portugal 1974%';

-- ============================================================
-- 20. IRANIAN REVOLUTION
-- ============================================================
UPDATE conflicts SET
    casualties_low = 2000,
    casualties_high = 3000,
    description = 'The Iranian Revolution (1978-1979) was a mass popular uprising that overthrew the US-backed monarchy of Shah Mohammad Reza Pahlavi and established the Islamic Republic of Iran under Ayatollah Ruhollah Khomeini. The revolution began with widespread protests against the Shah''s authoritarian rule, his secret police (SAVAK), Western cultural domination, and economic inequality despite the country''s oil wealth. Estimated deaths during the revolutionary period (January 1978 - February 1979) range from 2,000 to 3,000, though the revolutionary government later claimed 60,000 for propaganda purposes. The revolution involved a broad coalition including Islamists, leftists, nationalists, and liberal democrats, though the Islamic faction ultimately consolidated control.',
    progressive_analysis = 'The Iranian Revolution is a complex event for progressive analysis. On one hand, it was a genuine mass uprising against a brutal, US-imposed dictatorship. The Shah''s regime, installed by the CIA-MI6 coup of 1953 that overthrew the democratically elected government of Mohammad Mosaddegh (whose crime was nationalizing Iranian oil), was a textbook case of imperial client-state authoritarianism: SAVAK tortured and murdered dissidents while Western oil companies extracted Iran''s wealth. The revolution demonstrated the power of mass popular mobilization to topple an apparently invincible US-backed regime. However, the revolution''s trajectory also illustrates the dangers when leftist forces fail to organize independently: the Iranian left -- Tudeh Party, Fedayeen, Mojahedin -- played crucial roles in the revolution but were outmaneuvered and ultimately crushed by the Islamic faction. The post-revolutionary repression of the left, including mass executions of thousands of political prisoners in 1988, represented a counter-revolution within the revolution. The Iranian experience underscores that anti-imperialism alone is insufficient -- without a clear class program and independent working-class organization, anti-imperialist movements can be captured by reactionary forces.',
    outcome = 'Overthrow of the Shah''s US-backed monarchy. Establishment of the Islamic Republic of Iran under Ayatollah Khomeini. Nationalization of oil industry. US embassy hostage crisis. Broad revolutionary coalition subsequently narrowed as Islamic faction consolidated power and repressed leftist, liberal, and Kurdish opposition movements.'
WHERE name LIKE '%Iranian Revolution%'
   OR name LIKE '%Iran%Revolution%1979%';

-- ============================================================
-- 21. MEXICAN REVOLUTION
-- ============================================================
UPDATE conflicts SET
    casualties_low = 1000000,
    casualties_high = 2000000,
    description = 'The Mexican Revolution (1910-1920) was a major armed struggle that transformed Mexican political, social, and cultural life. It began as a revolt against the 35-year dictatorship of Porfirio Diaz, whose policies had concentrated land ownership among a tiny elite and foreign corporations while the majority of peasants were landless. Key revolutionary leaders included Emiliano Zapata (agrarian reform in the south), Pancho Villa (popular army in the north), Francisco Madero, Venustiano Carranza, and Alvaro Obregon. The revolution''s death toll is estimated at 1-2 million, from combat, famine, disease (including the 1918 influenza pandemic), and displacement. Mexico''s population declined from 15.5 million in 1910 to 14.5 million in 1921.',
    progressive_analysis = 'The Mexican Revolution was the first great social revolution of the 20th century, predating the Russian Revolution by seven years and demonstrating that the dispossessed peasantry could be a revolutionary force. Under the Porfiriato, foreign capital (primarily American) controlled Mexico''s railroads, mines, oil, and most productive land, while hacienda owners held indigenous and mestizo peasants in conditions resembling feudal serfdom through debt peonage. Emiliano Zapata''s Plan de Ayala -- demanding the return of stolen communal lands to indigenous communities -- represented one of the most radical agrarian programs in history and anticipated later peasant revolutions across the Global South. The revolution''s class character was most clearly expressed in the Zapatista movement, which implemented land reform in liberated territories of Morelos and created autonomous governance structures based on indigenous communal traditions. The ultimate betrayal of the revolution''s most radical demands by the Constitutionalist faction demonstrated a recurring pattern: bourgeois nationalists hijacking popular revolutionary energy to modernize capitalism rather than transform it. Nevertheless, the 1917 Constitution''s provisions on land reform (Article 27) and labor rights (Article 123) were among the most progressive in the world at the time.',
    outcome = 'Overthrow of the Diaz dictatorship. Adoption of the progressive 1917 Constitution with provisions for land reform and labor rights. Agrarian reform redistributed some land but fell short of Zapata''s vision. Assassination of Zapata (1919) and Villa (1923). Establishment of the one-party system under the PRI that ruled until 2000. Partial land reform under Cardenas in the 1930s.'
WHERE name LIKE '%Mexican Revolution%';

-- ============================================================
-- 22. IRISH WAR OF INDEPENDENCE
-- ============================================================
UPDATE conflicts SET
    casualties_low = 2000,
    casualties_high = 2500,
    description = 'The Irish War of Independence (1919-1921) was a guerrilla conflict between the Irish Republican Army (IRA) and British Crown forces, including the Royal Irish Constabulary (RIC), the British Army, and the notorious paramilitary auxiliaries known as the Black and Tans. The war followed the overwhelming electoral victory of Sinn Fein in 1918 and the declaration of the Irish Republic by Dail Eireann in January 1919. Fighting intensified dramatically in 1920-1921, with approximately 2,000-2,500 people killed, including combatants and civilians. The war ended with the Anglo-Irish Treaty of December 1921, which established the Irish Free State but partitioned Ireland, leading to the subsequent Irish Civil War.',
    progressive_analysis = 'The Irish War of Independence was a seminal anti-colonial struggle that influenced liberation movements worldwide. Ireland''s 750-year experience of English and later British colonialism encompassed systematic land confiscation, cultural suppression, religious persecution, and economic exploitation -- culminating in the Great Famine of 1845-52, when one million Irish died and another million emigrated while food was exported to England under armed guard. The revolutionary generation of 1916-1921 recognized that centuries of constitutional agitation had failed to secure Irish freedom precisely because British imperialism would never voluntarily relinquish control over any part of its empire. The IRA''s guerrilla campaign, waged by a poorly armed force against the world''s largest empire, demonstrated the effectiveness of asymmetric warfare in anti-colonial struggles and directly influenced later movements from Palestine to Vietnam. James Connolly''s understanding that national liberation without social revolution would merely exchange foreign capitalists for domestic ones proved prophetic: the Free State that emerged preserved much of the colonial economic structure. The partition of Ireland, imposed by British imperialism to maintain its foothold in the industrialized northeast, created an artificial border that perpetuated sectarian division -- a classic example of the colonial strategy of divide and rule.',
    outcome = 'Anglo-Irish Treaty of December 1921 establishing the Irish Free State as a dominion within the British Empire. Partition of Ireland, with six northeastern counties remaining under British rule as Northern Ireland. The treaty''s terms split the independence movement, leading to the Irish Civil War (1922-23). Eventual evolution to full republic status in 1949.'
WHERE name LIKE '%Irish War of Independence%'
   OR name LIKE '%Irish Independence%';

-- ============================================================
-- 23. EASTER RISING
-- ============================================================
UPDATE conflicts SET
    casualties_low = 450,
    casualties_high = 500,
    description = 'The Easter Rising (April 24-30, 1916) was an armed insurrection in Dublin by Irish republicans against British rule during World War I. Led by Patrick Pearse of the Irish Volunteers and James Connolly of the Irish Citizen Army, approximately 1,600 rebels seized key buildings in Dublin, including the General Post Office, and proclaimed the Irish Republic. The British military responded with overwhelming force, including artillery and a gunboat. Approximately 450-500 people were killed: 262 civilians (54% of total), 116 British soldiers, 16 policemen, and approximately 80 rebels. Over 2,000 civilians were wounded. The subsequent execution of 16 leaders by the British transformed public opinion in Ireland from hostility toward the rebels to support for independence.',
    progressive_analysis = 'The Easter Rising holds a unique place in revolutionary history as an insurrection whose military defeat became a political triumph, demonstrating that revolutionary action can transform consciousness even in apparent failure. James Connolly''s participation was particularly significant: as a Marxist trade union leader, he understood that Irish national liberation and working-class emancipation were inseparable struggles. His Irish Citizen Army -- the first armed workers'' militia in Europe -- marched alongside the Irish Volunteers, embodying the unity of national and class liberation. The Proclamation of the Irish Republic was remarkably progressive for its time, addressing both men and women equally and promising to "pursue the happiness and prosperity of the whole nation and of all its parts, cherishing all the children of the nation equally." The British response -- executing the leaders one by one over nine days, including the wounded Connolly who was shot while strapped to a chair -- exposed the savagery of colonial rule and radicalized Irish public opinion. The Rising''s symbolic power inspired anti-colonial movements worldwide, and Connolly''s synthesis of socialism and national liberation anticipated the theoretical developments of Fanon and Cabral. His warning that unfurling a green flag over Dublin Castle without social revolution would leave the fundamental structures of exploitation intact remains profoundly relevant.',
    outcome = 'Military defeat of the Rising after six days of fighting. Execution of 16 leaders by the British, including Connolly and Pearse. However, the executions transformed Irish public opinion, leading to the electoral triumph of Sinn Fein in 1918 and the subsequent War of Independence. The Rising is regarded as the foundational event of Irish independence.'
WHERE name LIKE '%Easter Rising%'
   OR name LIKE '%Easter Rebellion%';

-- ============================================================
-- 24. PARTITION OF INDIA CONFLICTS
-- ============================================================
UPDATE conflicts SET
    casualties_low = 200000,
    casualties_high = 2000000,
    description = 'The Partition of India (August 1947) divided British India into the independent nations of India and Pakistan, triggering the largest mass migration in human history and devastating communal violence. An estimated 15 million people were displaced as Hindus, Sikhs, and Muslims crossed the hastily drawn Radcliffe Line. Estimates of deaths from the accompanying communal violence range from 200,000 to 2,000,000, with more recent research suggesting between 1-2 million killed. The violence was concentrated in Punjab and Bengal, involving mass killings, sexual violence, abductions, and arson. The Punjab region, split between India and Pakistan, suffered the highest casualties.',
    progressive_analysis = 'The Partition of India stands as the final, catastrophic crime of British colonialism on the subcontinent. The communal violence that accompanied partition was not some primordial religious hatred but the direct product of nearly two centuries of deliberate British divide-and-rule policy. The British had systematically cultivated Hindu-Muslim division as a tool of colonial governance -- separate electorates, communal census categories, and the deliberate favoring of one community over another in different regions were all strategies to prevent a unified anti-colonial front. The murderous haste of the actual partition -- with Cyril Radcliffe, a man who had never visited India, drawing the border in five weeks -- demonstrated the colonial power''s complete indifference to the human consequences of its administrative decisions. The mass violence, including the abduction and sexual assault of an estimated 75,000-100,000 women, was the predictable result of colonial social engineering meeting bureaucratic negligence. The tragedy of Partition also illustrates how the departing colonial power ensured that the successor states would be weakened by perpetual conflict -- the Kashmir dispute, engineered by the chaotic manner of British withdrawal, continues to this day. The working-class and peasant communities on both sides of the border paid the price for the failures and manipulations of both colonial and nationalist elites.',
    outcome = 'Creation of India and Pakistan as independent states on August 14-15, 1947. Mass communal violence killing 200,000 to 2,000,000 people. Displacement of 15 million people. First Indo-Pakistani War over Kashmir (1947-48). Establishment of ongoing Kashmir dispute. The partition''s wounds continue to shape South Asian politics.'
WHERE name LIKE '%Partition of India%'
   OR name LIKE '%India Partition%'
   OR name LIKE '%Indian Partition%';

-- ============================================================
-- 25. BANGLADESH LIBERATION WAR
-- ============================================================
UPDATE conflicts SET
    casualties_low = 300000,
    casualties_high = 3000000,
    description = 'The Bangladesh Liberation War (March-December 1971) was an armed conflict between the Pakistani military and Bengali nationalist forces (Mukti Bahini) in East Pakistan, culminating in the independence of Bangladesh. Following the Awami League''s landslide victory in the 1970 elections, the Pakistani military launched Operation Searchlight on March 25, 1971, targeting Bengali intellectuals, students, and Hindu minorities in what is widely recognized as genocide. Estimates of deaths range from 300,000 to 3,000,000, with Bangladesh''s official figure at 3 million. India intervened militarily in December 1971, leading to Pakistani surrender on December 16. An estimated 200,000-400,000 women were raped, and approximately 10 million refugees fled to India.',
    progressive_analysis = 'The Bangladesh Liberation War was fundamentally a struggle against internal colonialism and national oppression. Although Pakistan was itself a product of anti-colonial struggle, the West Pakistani ruling elite treated East Pakistan as an economic colony -- extracting its jute and other resources while concentrating development and political power in the west, despite East Pakistan''s larger population. The denial of the democratic mandate after the Awami League''s election victory, followed by the genocidal military operation targeting Bengali civilians, intellectuals, and the Hindu minority, demonstrated that the Pakistani military-feudal elite would resort to any level of violence to maintain its exploitative dominance. The genocide -- which included the systematic targeting of intellectuals to destroy Bengali cultural leadership and the mass rape of women as a weapon of war -- was supported by the United States and China for geopolitical reasons, exposing how Cold War rivalries trumped human rights. The liberation struggle united Bengalis across class lines in resistance to national oppression, though the subsequent history of Bangladesh also demonstrates that national liberation alone, without addressing class exploitation, leaves the fundamental structures of inequality intact. The war remains a powerful example of how economic exploitation and political disenfranchisement, when combined with national and ethnic oppression, inevitably produce resistance.',
    outcome = 'Independence of Bangladesh on December 16, 1971, following Indian military intervention and Pakistani surrender. Establishment of the People''s Republic of Bangladesh under Sheikh Mujibur Rahman. Recognition of genocide by international scholars. Pakistan lost its eastern wing, fundamentally altering South Asian geopolitics.'
WHERE name LIKE '%Bangladesh Liberation%'
   OR name LIKE '%Bangladesh%War%'
   OR name LIKE '%East Pakistan%';

-- ============================================================
-- 26. ERITREAN WAR OF INDEPENDENCE
-- ============================================================
UPDATE conflicts SET
    casualties_low = 60000,
    casualties_high = 200000,
    description = 'The Eritrean War of Independence (1961-1991) was a 30-year armed struggle by the Eritrean People''s Liberation Front (EPLF) and earlier the Eritrean Liberation Front (ELF) against Ethiopian rule. After Italy''s colonial rule ended in 1941, Eritrea was federated with Ethiopia in 1952 and annexed outright in 1962, prompting armed resistance. The war intensified after 1974 when the Derg military junta, backed by massive Soviet arms supplies and Cuban troops, launched devastating offensives. An estimated 60,000-200,000 people were killed, including 60,000-90,000 Eritrean soldiers and civilians and approximately 75,000 Ethiopian troops. Over 400,000 Eritreans became refugees. The EPLF achieved final victory in 1991.',
    progressive_analysis = 'The Eritrean struggle for independence was one of the longest and most determined anti-colonial wars in African history. Eritrea''s case is particularly instructive for understanding the contradictions of post-colonial Africa: having been denied the right to self-determination by the UN in 1952 (which federated it with Ethiopia at US insistence to secure military base access), Eritreans faced the paradox of fighting for liberation against an African state that itself claimed anti-colonial credentials. The Ethiopian Empire''s -- and later the Derg''s -- treatment of Eritrea reproduced the classic colonial pattern of military occupation, cultural suppression, and economic exploitation. The EPLF''s remarkable self-reliance, building an entire society in the field including hospitals, schools, and workshops in underground tunnels, demonstrated extraordinary revolutionary determination. The movement''s emphasis on women''s participation (30% of EPLF fighters were women) and land reform in liberated areas embodied progressive social transformation alongside national liberation. The fact that both the US-backed Imperial regime and the Soviet-backed Derg sought to crush Eritrean self-determination demonstrates that superpower interests consistently trumped the rights of colonized peoples during the Cold War. The EPLF''s victory, achieved without significant external support against Soviet-armed Ethiopian forces, stands as testament to the power of popular resistance.',
    outcome = 'EPLF victory in 1991 following the capture of Asmara. Eritrean independence confirmed by referendum in 1993 with 99.8% voting for independence. End of 30 years of armed struggle. However, border disputes led to the devastating Eritrean-Ethiopian War of 1998-2000, and post-independence Eritrea has faced criticism for authoritarian governance.'
WHERE name LIKE '%Eritrean War of Independence%'
   OR name LIKE '%Eritrea%Independence%';

-- ============================================================
-- 27. EAST TIMOR INDEPENDENCE
-- ============================================================
UPDATE conflicts SET
    casualties_low = 90000,
    casualties_high = 200000,
    description = 'The East Timor independence struggle (1975-1999) encompasses the resistance against Indonesian military occupation following Portugal''s withdrawal. Indonesia invaded East Timor on December 7, 1975, with the tacit approval of the United States and Australia. FRETILIN (Revolutionary Front for an Independent East Timor) waged a guerrilla resistance throughout the 24-year occupation. The Commission for Reception, Truth and Reconciliation estimated between 90,800 and 202,600 East Timorese died from violence, famine, and disease during the occupation -- representing up to one-third of the pre-invasion population of 688,000. In the first year alone, an estimated 60,000-100,000 were killed. Following a 1999 UN-supervised referendum in which 78.5% voted for independence, pro-Indonesian militias conducted a campaign of destruction, and East Timor achieved independence in 2002.',
    progressive_analysis = 'The East Timor genocide is one of the most devastating cases of imperialist-enabled mass killing in the post-World War II era. Indonesia''s invasion was directly enabled by the United States -- President Ford and Secretary of State Kissinger met with President Suharto in Jakarta on December 6, 1975, giving explicit approval for the invasion, and the US subsequently supplied 90% of Indonesia''s weapons. Australia, seeking access to Timor Sea oil and gas, acquiesced to the occupation and signed the Timor Gap Treaty with Indonesia to divide East Timor''s resources. FRETILIN''s resistance, maintained for 24 years against vastly superior forces, represents extraordinary revolutionary determination in the face of genocide. The occupation killed up to one-third of the population -- proportionally one of the worst genocides since the Holocaust -- yet received minimal Western media coverage because Indonesia was a key anti-communist ally. The East Timor case starkly illustrates how Western governments'' professed concern for human rights is subordinated to geopolitical and economic interests. The eventual achievement of independence through the 1999 referendum, following decades of international solidarity activism, demonstrates both the resilience of colonized peoples and the importance of transnational solidarity movements.',
    outcome = 'East Timorese independence achieved in 2002 following the 1999 UN-supervised referendum. End of 24 years of Indonesian occupation. Post-referendum militia violence destroyed 70% of infrastructure. Truth commission documented widespread atrocities. East Timor (Timor-Leste) became the first new sovereign state of the 21st century.'
WHERE name LIKE '%East Timor%'
   OR name LIKE '%Timor%Independence%'
   OR name LIKE '%Timor-Leste%';

-- ============================================================
-- 28. WESTERN SAHARA CONFLICT
-- ============================================================
UPDATE conflicts SET
    casualties_low = 10000,
    casualties_high = 21000,
    description = 'The Western Sahara conflict (1975-present) is an ongoing dispute between the Sahrawi independence movement, represented by the Polisario Front, and Morocco, which has occupied the territory since Spain''s withdrawal in 1975. The Polisario Front, backed by Algeria, waged a guerrilla war against both Morocco and Mauritania (which withdrew in 1979). Morocco constructed a 2,700-kilometer sand wall (berm) dividing the territory. Casualties during the active war phase (1975-1991) are estimated at 10,000-21,000. A ceasefire was established in 1991 with the promise of a UN-supervised referendum that has never been held. Over 100,000 Sahrawi refugees remain in camps in Algeria. Low-level clashes resumed in 2020.',
    progressive_analysis = 'The Western Sahara conflict represents Africa''s last major colonial question and exposes the hypocrisy of the international community regarding self-determination. When Spain withdrew in 1975, rather than allowing the Sahrawi people to exercise their right to self-determination, Morocco and Mauritania invaded and divided the territory between them -- a textbook case of one form of colonialism being replaced by another. Morocco''s "Green March" of 350,000 settlers into Western Sahara was a calculated act of colonial annexation designed to present the international community with a fait accompli. The Polisario Front''s armed resistance and the establishment of the Sahrawi Arab Democratic Republic represented a legitimate national liberation struggle recognized by the African Union and over 80 countries. Morocco''s occupation is sustained by the exploitation of Western Sahara''s rich phosphate deposits and fishing waters -- the same pattern of resource extraction that characterizes all colonial enterprises. France and the United States have consistently blocked meaningful UN action to implement the promised referendum, prioritizing their alliance with the Moroccan monarchy over Sahrawi self-determination. The 100,000+ Sahrawi refugees who have lived in desert camps for nearly five decades are a living testament to the international community''s failure to uphold the principle of self-determination when powerful interests oppose it.',
    outcome = 'Ceasefire established in 1991 with UN promise of referendum on self-determination that has never been held. Morocco controls most of the territory behind a 2,700 km sand wall. Sahrawi Arab Democratic Republic recognized by over 80 countries and the African Union. Over 100,000 refugees remain in camps in Algeria. Conflict renewed at low level in 2020. The issue remains unresolved.'
WHERE name LIKE '%Western Sahara%'
   OR name LIKE '%Polisario%';

-- ============================================================
-- 29. ZIMBABWE WAR OF LIBERATION
-- ============================================================
UPDATE conflicts SET
    casualties_low = 20000,
    casualties_high = 51000,
    description = 'The Zimbabwe War of Liberation, also known as the Rhodesian Bush War or Second Chimurenga (1964-1979), was an armed struggle by Black nationalist movements -- primarily ZANLA (Zimbabwe African National Liberation Army, military wing of ZANU) and ZIPRA (Zimbabwe People''s Revolutionary Army, military wing of ZAPU) -- against the white-minority government of Rhodesia led by Ian Smith. The conflict escalated after Smith''s Unilateral Declaration of Independence from Britain in 1965, which sought to preserve white supremacist rule. Estimates of total deaths range from 20,000 to 51,000, including over half being guerrilla fighters, approximately 1,120 Rhodesian security forces, 500 white civilians, and thousands of Black civilians. The war ended with the Lancaster House Agreement of 1979 and Zimbabwe''s independence in 1980.',
    progressive_analysis = 'The Zimbabwe liberation struggle was a war against one of the most explicit systems of racial capitalism in Africa. Ian Smith''s Rhodesia, like apartheid South Africa, was a settler-colonial state in which a tiny white minority (less than 5% of the population) controlled the best land, all political power, and the commanding heights of the economy. The Land Apportionment Act had dispossessed Black Zimbabweans of their ancestral lands and confined them to overcrowded, infertile "Tribal Trust Lands" -- a system of internal colonialism that enriched white farmers at the expense of Black subsistence. The liberation war was fundamentally about land and sovereignty: the guerrillas drew their support from the peasantry whose land had been stolen, and land redistribution was the central promise of the struggle. The war also demonstrated the international dimensions of anti-colonial resistance: Cuba, China, and the Soviet Union provided crucial military support, while the white minority regime was sustained by South Africa, international sanctions-busting, and covert Western support. Smith''s UDI was itself an act of colonial rebellion -- white settlers seizing independence from Britain to prevent Black majority rule -- exposing the fundamental contradiction of a "democracy" that excluded 95% of the population. The liberation movements'' victory represented the triumph of the African majority over settler colonialism.',
    outcome = 'Lancaster House Agreement of 1979 leading to ceasefire and elections. Zimbabwe independence on April 18, 1980, with Robert Mugabe as Prime Minister. End of white minority rule. ZANU-PF election victory. However, the Gukurahundi massacres in Matabeleland (1983-87) and the eventual authoritarian trajectory of the Mugabe government complicated the liberation legacy.'
WHERE name LIKE '%Zimbabwe%Liberation%'
   OR name LIKE '%Rhodesian Bush War%'
   OR name LIKE '%Second Chimurenga%';

-- ============================================================
-- 30. NAMIBIAN WAR OF INDEPENDENCE
-- ============================================================
UPDATE conflicts SET
    casualties_low = 10000,
    casualties_high = 25000,
    description = 'The Namibian War of Independence (1966-1990) was an armed struggle by the South West Africa People''s Organisation (SWAPO) and its military wing, the People''s Liberation Army of Namibia (PLAN), against South Africa''s illegal occupation of South West Africa (Namibia). South Africa had been administering the territory under a League of Nations mandate since 1920 and refused to relinquish control despite UN General Assembly resolutions and a 1971 International Court of Justice ruling declaring the occupation illegal. South African forces also conducted cross-border operations into Angola. Estimated casualties range from 10,000-25,000 over the 24-year conflict. The 1978 Cassinga massacre, in which South African forces killed over 600 people including women and children at a SWAPO camp in Angola, was a particularly notorious incident. Namibia achieved independence on March 21, 1990.',
    progressive_analysis = 'The Namibian liberation struggle was inseparable from the broader struggle against apartheid and white supremacy in southern Africa. South Africa''s occupation of Namibia was a direct extension of its apartheid system: Bantustans were established, Black Namibians were confined to "homelands," and the territory''s resources -- particularly diamonds and uranium -- were exploited for the benefit of South African and international capital. SWAPO''s armed struggle, waged against the most powerful military in Africa, demonstrated extraordinary determination by a small nation against an occupying power backed by Western economic interests. The Cassinga massacre of 1978, in which the South African military killed over 600 people at a refugee camp, exemplified the apartheid regime''s willingness to use indiscriminate violence against civilians, including women and children. The war was also a key theater of the Cold War in Africa: Cuba deployed thousands of troops to Angola to defend against South African invasion, and the 1988 Battle of Cuito Cuanavale -- in which Cuban and Angolan forces checked a South African offensive -- was a decisive turning point that forced South Africa to the negotiating table. Namibia''s independence in 1990 represented one of the last successful anti-colonial struggles in Africa and demonstrated that apartheid expansionism could be defeated through armed resistance combined with international solidarity.',
    outcome = 'Namibian independence on March 21, 1990, following the Tripartite Accord of 1988 between Angola, Cuba, and South Africa. SWAPO won the founding elections. End of South Africa''s illegal occupation. The war contributed to the broader collapse of the apartheid system. Cuban troops withdrew from Angola under the peace agreement.'
WHERE name LIKE '%Namibian War of Independence%'
   OR name LIKE '%Namibia%Independence%'
   OR name LIKE '%South West Africa%';

-- ============================================================
-- 31. SOUTH AFRICAN BORDER WAR
-- ============================================================
UPDATE conflicts SET
    casualties_low = 20000,
    casualties_high = 25000,
    description = 'The South African Border War (1966-1990), also known as the Namibian Bush War or the Angolan Bush War, was a conflict primarily fought in northern Namibia (then South West Africa) and southern Angola between the South African Defence Force (SADF) and its allies on one side, and SWAPO''s PLAN guerrillas, Angolan government forces (FAPLA), and Cuban expeditionary forces on the other. The conflict was intertwined with the Angolan Civil War and the broader Cold War in Africa. Estimated casualties range from 20,000-25,000 over the 24-year conflict. The war included major conventional battles such as Cuito Cuanavale (1987-88), as well as sustained counterinsurgency operations. The conflict ended with the 1988 Tripartite Accord that led to Namibian independence and Cuban withdrawal from Angola.',
    progressive_analysis = 'The South African Border War was fundamentally an extension of the apartheid state''s determination to maintain white supremacy and colonial control over southern Africa. South Africa''s military operations in Namibia and Angola served multiple purposes: suppressing the Namibian liberation movement, destabilizing the progressive Angolan government, and projecting apartheid power throughout the region. The SADF''s "total strategy" doctrine explicitly linked the defense of apartheid domestically with military aggression regionally, understanding that the liberation of Namibia and Angola would accelerate the end of apartheid itself. Cuba''s military intervention in Angola -- in which 55,000 Cuban troops ultimately served, with over 2,000 killed -- was one of the most extraordinary acts of internationalist solidarity in modern history. The Battle of Cuito Cuanavale in 1988, where Cuban and Angolan forces halted a major South African offensive, was a decisive moment: Nelson Mandela later stated that "the defeat of the apartheid army was an inspiration to the struggling people in South Africa" and that Cuito Cuanavale was "a turning point for the liberation of our continent." The Border War demonstrates how anti-colonial and anti-racist struggles are interconnected across borders and how international solidarity can shift the balance against seemingly overwhelming military power.',
    outcome = 'Tripartite Accord of 1988 ending the war. Namibian independence in 1990. Cuban withdrawal from Angola. The military stalemate, particularly after the Battle of Cuito Cuanavale, helped convince the apartheid regime that a negotiated settlement was necessary, contributing to the broader process of ending apartheid in South Africa itself.'
WHERE name LIKE '%South African Border War%'
   OR name LIKE '%Angolan Bush War%'
   OR name LIKE '%Namibian Bush War%';

-- ============================================================
-- END OF FILE
-- ============================================================
