-- Seed data for labor organizations and strikes
-- This file populates labor_organizations and strikes tables with major union and labor movement data

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Note: This script requires that countries are already seeded in the countries table
-- If country IDs are different, update the UUIDs accordingly

-- Insert Labor Organizations (International and Major National)

INSERT INTO labor_organizations (id, name, name_native, abbreviation, organization_type, industry_sectors, founded, country_id, headquarters_city, ideology_tags, political_affiliation, description, progressive_analysis) VALUES

-- International federations
('660e8400-e29b-41d4-a716-446655440001', 'International Labour Organization', NULL, 'ILO', 'federation', ARRAY['multi_sector'], '1919-01-01'::date, '00000000-0000-0000-0000-000000000001', 'Geneva', ARRAY['international', 'labor_rights'], 'International', 'UN specialized agency for labor issues, setting labor standards and developing policies, with tripartite representation of governments, employers, and workers.', 'The ILO provides a global framework for labor rights, though its effectiveness is limited by reliance on capitalist states and employers. Progressive forces must push for stronger enforcement and more radical positions.'),

('660e8400-e29b-41d4-a716-446655440002', 'International Trade Union Confederation', NULL, 'ITUC', 'confederation', ARRAY['multi_sector'], '2006-01-01'::date, '00000000-0000-0000-0000-000000000001', 'Brussels', ARRAY['social_democratic', 'international'], 'Social Democratic', 'Global trade union organization representing over 200 million workers in 163 countries, advocating for labor rights and social justice through dialogue with governments and employers.', 'While reformist in approach, the ITUC represents the organized global working class. However, it often prioritizes negotiation over confrontation and is dominated by Western unions.'),

('660e8400-e29b-41d4-a716-446655440003', 'World Federation of Trade Unions', NULL, 'WFTU', 'confederation', ARRAY['multi_sector'], '1945-01-01'::date, '00000000-0000-0000-0000-000000000001', 'Athens', ARRAY['communist', 'international'], 'Communist', 'International trade union organization founded after WWII, with historically strong ties to Soviet and other communist countries, advocating for workers'' solidarity against imperialism and capitalism.', 'The WFTU represents communist and leftist trade unions, maintaining commitment to revolutionary struggle and opposition to imperialism, though its influence has varied with geopolitical shifts.'),

-- United States
('660e8400-e29b-41d4-a716-446655440004', 'American Federation of Labor and Congress of Industrial Organizations', NULL, 'AFL-CIO', 'confederation', ARRAY['multi_sector'], '1955-01-01'::date, '00000000-0000-0000-0000-000000000002', 'Washington', ARRAY['social_democratic', 'labor_rights'], 'Democratic Party-aligned', 'Largest federation of labor unions in the US representing millions of workers across most industries, advocating for wages, benefits, and workplace rights through collective bargaining and political action.', 'The AFL-CIO is a major base of working-class organization in the US. However, its leadership is often aligned with the Democratic Party and advocates compromise rather than confrontation with capital.'),

('660e8400-e29b-41d4-a716-446655440005', 'Congress of Industrial Organizations', NULL, 'CIO', 'confederation', ARRAY['manufacturing', 'mining', 'transport'], '1935-01-01'::date, '00000000-0000-0000-0000-000000000002', 'Pittsburgh', ARRAY['militant', 'industrial'], 'Labor Left', 'Historic industrial union federation (1935-1955) organizing workers in mass production industries, known for militant sit-down strikes and innovative organizing strategies that built working-class power.', 'The CIO represented an important moment of working-class militancy and industrial organization, demonstrating the potential power of organized labor when leadership is committed to radical struggle.'),

('660e8400-e29b-41d4-a716-446655440006', 'International Association of Machinists and Aerospace Workers', NULL, 'IAM', 'trade_union', ARRAY['manufacturing', 'aerospace', 'transport'], '1888-01-01'::date, '00000000-0000-0000-0000-000000000002', 'Washington', ARRAY['industrial', 'labor_rights'], 'Labor Union', 'One of the oldest and largest unions in the US, representing workers in manufacturing and aerospace with a strong tradition of militant action and shop-floor organizing.', 'The IAM has a tradition of militant struggle and rank-and-file power. However, it must continually fight against bureaucratic tendencies within its own leadership.'),

('660e8400-e29b-41d4-a716-446655440007', 'United Auto Workers', NULL, 'UAW', 'trade_union', ARRAY['manufacturing', 'automotive'], '1935-01-01'::date, '00000000-0000-0000-0000-000000000002', 'Detroit', ARRAY['industrial', 'militant'], 'Labor Union', 'Major union representing automobile workers and other manufacturing sectors, historic center of working-class struggle with famous sit-down strikes and militant rank-and-file movements.', 'The UAW has been a crucial center of working-class power and militant struggle. Recent years have seen attempts to revitalize member militancy against corrupt leadership and to challenge the auto industry''s dominance.'),

-- United Kingdom
('660e8400-e29b-41d4-a716-446655440008', 'Trades Union Congress', NULL, 'TUC', 'confederation', ARRAY['multi_sector'], '1868-01-01'::date, '00000000-0000-0000-0000-000000000003', 'London', ARRAY['social_democratic', 'labor_rights'], 'Labour Party-aligned', 'Confederation representing trade unions in the UK, advocating for workers'' rights through collective bargaining, political engagement, and workplace representation, affiliated with the Labour Party.', 'The TUC represents millions of British workers organized in trade unions. Its leadership has often compromised with capital and the state, though the base continues to struggle for workers'' interests.'),

('660e8400-e29b-41d4-a716-446655440009', 'National Union of Mineworkers', NULL, 'NUM', 'trade_union', ARRAY['mining'], '1888-01-01'::date, '00000000-0000-0000-0000-000000000003', 'Barnsley', ARRAY['militant', 'communist_influence'], 'Labor Union', 'Historic miners'' union with tradition of militant struggle, famous for the 1926 General Strike and the 1984-1985 strike against mine closures, powerful center of working-class organization.', 'The NUM represents the potential and limits of trade union struggle. While its militant past demonstrates working-class power, its defeat in the 1984-85 strike shows the challenge of confronting capitalist state power without revolutionary strategy.'),

('660e8400-e29b-41d4-a716-446655440010', 'Unite the Union', NULL, 'Unite', 'confederation', ARRAY['manufacturing', 'transport', 'public_sector'], '2007-01-01'::date, '00000000-0000-0000-0000-000000000003', 'London', ARRAY['labor_rights', 'militant_wing'], 'Labour Party-aligned with left current', 'Major British union formed from merger of TGWU and AMICUS, representing workers in transport, manufacturing, and public services with significant left-wing militant current among rank-and-file.', 'Unite has a sizeable left-wing base committed to militant struggle. The tension between leadership and rank-and-file over strategy reflects broader debates about the future of labor organization in Britain.'),

-- France
('660e8400-e29b-41d4-a716-446655440011', 'Confédération Générale du Travail', 'Confédération Générale du Travail', 'CGT', 'confederation', ARRAY['multi_sector'], '1895-01-01'::date, '00000000-0000-0000-0000-000000000004', 'Paris', ARRAY['communist', 'militant'], 'Communist-affiliated', 'Largest French trade union confederation with historic ties to French Communist Party, strong tradition of militant strike action and direct action, representing millions of workers across all sectors.', 'The CGT has been a crucial force in French working-class struggle, with deep connections to the communist movement. Its strength makes it an important focus for revolutionary forces, though its leadership often compromises.'),

('660e8400-e29b-41d4-a716-446655440012', 'Confédération Française Démocratique du Travail', NULL, 'CFDT', 'confederation', ARRAY['multi_sector'], '1964-01-01'::date, '00000000-0000-0000-0000-000000000004', 'Paris', ARRAY['social_democratic', 'labor_rights'], 'Socialist Party-aligned', 'Second-largest French union confederation advocating for worker rights through negotiation and political engagement, representing significant portions of public sector and services workers.', 'While the CFDT has organized important struggles, its leadership often prioritizes negotiation and compromise with capital and the state. It represents an important conservative pole within French labor.'),

('660e8400-e29b-41d4-a716-446655440013', 'Confédération Générale du Travail - Force Ouvrière', NULL, 'CGT-FO', 'confederation', ARRAY['multi_sector'], '1948-01-01'::date, '00000000-0000-0000-0000-000000000004', 'Paris', ARRAY['social_democratic', 'anti_communist'], 'Anti-communist socialist', 'French union confederation with historically strong anti-communist stance, advocating for worker rights through negotiation and strike action, representing significant portions of public sector workers.', 'The FO emerged from Cold War anti-communist splits in the labor movement. While it represents important sectors of workers, its anti-communist stance has often put it at odds with more radical struggle.'),

-- Germany
('660e8400-e29b-41d4-a716-446655440014', 'IG Metall', NULL, 'IG Metall', 'trade_union', ARRAY['manufacturing', 'metalworking', 'automotive'], '1950-01-01'::date, '00000000-0000-0000-0000-000000000005', 'Frankfurt', ARRAY['industrial', 'militant'], 'Social Democratic union', 'Largest German union representing metalworkers and manufacturing sectors, with strong tradition of securing wages, benefits, and workplace rights, significant power in German industry.', 'IG Metall represents core working-class sectors in Germany. Though led by social democrats, it has demonstrated capacity for militant struggle when mobilized by active rank-and-file movements.'),

('660e8400-e29b-41d4-a716-446655440015', 'German Federation of Trade Unions', NULL, 'DGB', 'confederation', ARRAY['multi_sector'], '1949-01-01'::date, '00000000-0000-0000-0000-000000000005', 'Berlin', ARRAY['social_democratic', 'labor_rights'], 'Social Democratic', 'Major German trade union confederation representing millions of workers across all sectors, advocating for worker rights through collective bargaining and political engagement with establishment parties.', 'The DGB represents organized German labor. However, its integrationist approach and focus on negotiation with capital and the state often prevents more militant action necessary for deeper working-class victories.'),

-- Poland
('660e8400-e29b-41d4-a716-446655440016', 'Solidarność', 'Solidarność', 'Solidarity', 'confederation', ARRAY['manufacturing', 'multi_sector'], '1980-01-01'::date, '00000000-0000-0000-0000-000000000006', 'Gdańsk', ARRAY['anti_communist', 'nationalist'], 'Catholic nationalist', 'Historic Polish labor movement and opposition movement that grew from Gdańsk shipyard strikes, playing crucial role in 1989-90 fall of communist regime, later institutionalized as union and political force.', 'While Solidarity represented important working-class militancy, its anti-communist politics and alliance with nationalist and Catholic elements have complicated its revolutionary potential and it became a vector for capitalist restoration.'),

-- Brazil
('660e8400-e29b-41d4-a716-446655440017', 'Central Única dos Trabalhadores', NULL, 'CUT', 'confederation', ARRAY['multi_sector'], '1983-01-01'::date, '00000000-0000-0000-0000-000000000007', 'São Paulo', ARRAY['leftist', 'militant'], 'Workers Party (PT)-affiliated', 'Major Brazilian union confederation representing millions of workers, formed during resistance to military dictatorship, historically affiliated with Workers Party, with strong tradition of militant struggle and direct action.', 'The CUT represents organized Brazilian labor and has played crucial roles in major strikes and struggles. However, its ties to the Workers Party have sometimes constrained more radical action, particularly during PT governments.'),

-- South Africa
('660e8400-e29b-41d4-a716-446655440018', 'Congress of South African Trade Unions', NULL, 'COSATU', 'confederation', ARRAY['multi_sector'], '1985-01-01'::date, '00000000-0000-0000-0000-000000000008', 'Johannesburg', ARRAY['anti_apartheid', 'communist_aligned'], 'ANC/SACP-aligned', 'Major South African labor confederation formed during anti-apartheid struggle, closely aligned with African National Congress and South African Communist Party, representing millions of workers across all sectors.', 'COSATU played crucial roles in anti-apartheid struggle. However, post-apartheid, its alliance with the ANC has often constrained more militant action, and workers have repeatedly organized wildcat strikes against union compromises.'),

-- Russia/Soviet
('660e8400-e29b-41d4-a716-446655440019', 'Confederation of Labour of Russia', NULL, 'KTR', 'confederation', ARRAY['multi_sector'], '1990-01-01'::date, '00000000-0000-0000-0000-000000000009', 'Moscow', ARRAY['reformed_state_unions'], 'Social Democratic/Independent', 'Major Russian confederation of trade unions formed from remnants of Soviet unions after 1990, representing significant portions of Russian working class, though weakened by transition and capital offensive.', 'Russian labor has faced devastating attacks during capitalist transition. Unions have struggled to protect workers'' interests against capital and the state, with important wildcat movements emerging despite weak union support.'),

-- China
('660e8400-e29b-41d4-a716-446655440020', 'All-China Federation of Trade Unions', NULL, 'ACFTU', 'confederation', ARRAY['multi_sector'], '1921-01-01'::date, '00000000-0000-0000-0000-000000000010', 'Beijing', ARRAY['communist'], 'Communist Party of China', 'Organization of trade unions in China under direction of Communist Party, representing organized Chinese workers, though with limited autonomy from party and state authorities.', 'The ACFTU represents official labor organization in China. However, it has limited independence from the party-state, and workers have increasingly organized independent strikes and unions outside official structures.'),

-- Mexico
('660e8400-e29b-41d4-a716-446655440021', 'Confederación de Trabajadores de México', NULL, 'CTM', 'confederation', ARRAY['multi_sector'], '1936-01-01'::date, '00000000-0000-0000-0000-000000000011', 'Mexico City', ARRAY['corporatist', 'affiliated_PRI'], 'PRI-affiliated corporatist', 'Major Mexican labor confederation historically tied to PRI party, representing significant portions of organized Mexican workers, though often criticized for collaborationist approach and corporatist structures.', 'The CTM has often acted as a vehicle for corporatist control of labor. However, Mexico''s workers have repeatedly organized militant independent movements challenging both capital and official union structures.'),

-- India
('660e8400-e29b-41d4-a716-446655440022', 'All India Trade Union Congress', NULL, 'AITUC', 'confederation', ARRAY['multi_sector'], '1920-01-01'::date, '00000000-0000-0000-0000-000000000012', 'New Delhi', ARRAY['communist', 'militant'], 'Communist Party of India-affiliated', 'Historic Indian labor confederation with communist ties, involved in important labor struggles including plantation workers, textile workers, and agricultural workers, representing millions of Indian workers.', 'AITUC has participated in major Indian labor struggles including important strikes. Its communist orientation provides important anti-capitalist framework, though it must contend with challenges of organizing across divisions of caste and region.'),

-- Additional major unions
('660e8400-e29b-41d4-a716-446655440023', 'General Confederation of Labor', NULL, 'CGT', 'confederation', ARRAY['multi_sector'], '1930-01-01'::date, '00000000-0000-0000-0000-000000000013', 'Buenos Aires', ARRAY['peronist', 'militant'], 'Peronist-affiliated', 'Major Argentine labor confederation with Peronist orientation, representing millions of Argentine workers, historical tradition of militant strike action and powerful working-class organization.', 'Argentine labor has strong militant traditions. The CGT represents significant working-class power, though tensions between leadership and rank-and-file over strategy continue.'),

('660e8400-e29b-41d4-a716-446655440024', 'Korean Confederation of Trade Unions', NULL, 'KCTU', 'confederation', ARRAY['multi_sector'], '1990-01-01'::date, '00000000-0000-0000-0000-000000000014', 'Seoul', ARRAY['leftist', 'militant'], 'Independent/Socialist-aligned', 'Major South Korean labor confederation formed from militant labor movements, with strong left-wing current, representing significant portions of organized Korean workers despite state repression and legal restrictions.', 'The KCTU has demonstrated impressive militancy against both capital and the South Korean state. Its struggle represents important resistance to capital in the region.');

-- Now insert major historical strikes

INSERT INTO strikes (id, name, strike_type, start_date, end_date, country_id, location_name, organization_id, participants, industries_affected, outcome, demands, achievements, casualties, arrests, government_response, description, progressive_analysis, significance) VALUES

-- Historical US strikes
('770e8400-e29b-41d4-a716-446655440001', 'Pullman Strike', 'general_strike', '1894-05-11'::date, '1894-07-20'::date, '00000000-0000-0000-0000-000000000002', 'Pullman, Illinois', NULL, 150000, ARRAY['railway', 'manufacturing'], 'suppressed', ARRAY['wage_increases', 'reinstatement_of_workers'], ARRAY[], 4, 1000, 'Federal troops killed workers; strike leader Eugene Debs imprisoned for six months', 'Major nationwide railroad strike demonstrating power of coordinated working-class action against monopoly capital and government intervention. Led by American Railway Union members, it paralyzed national rail system despite violent federal suppression.', 'The Pullman Strike demonstrates the potential of unified working-class action and the lengths the state will go to protect capitalist interests. Though militarily defeated, it inspired generations of workers and accelerated socialist growth in America.', 'Milestone of American labor struggle; demonstrated national coordination capacity; led to imprisonment of labor leaders; accelerated growth of radical labor movements.'),

('770e8400-e29b-41d4-a716-446655440002', 'Flint Sit-Down Strike', 'sit_down', '1936-12-30'::date, '1937-02-11'::date, '00000000-0000-0000-0000-000000000002', 'Flint, Michigan', '660e8400-e29b-41d4-a716-446655440005', 45000, ARRAY['automotive', 'manufacturing'], 'victory', ARRAY['union_recognition', 'wage_increases', 'working_conditions'], ARRAY['UAW_recognition', 'wage_increases', 'eight_hour_day'], 0, 0, 'Company and police attempted to disperse but workers controlled factory', 'Innovative sit-down strike at General Motors plants where workers occupied factories preventing management from replacing them with scabs, forcing company to recognize CIO union through workers'' effective control of production.', 'The Flint sit-down strike represents a highpoint of American working-class power, demonstrating the potential of workplace occupation and the control workers can exercise over production. It accelerated industrial unionization and raised possibilities for more radical action.', 'Crucial victory in American labor struggle; demonstrated sit-down strategy effectiveness; led to major industrial unionization; inspired international labor movements.'),

('770e8400-e29b-41d4-a716-446655440003', 'Memphis Sanitation Strike', 'industry_strike', '1968-02-12'::date, '1968-04-16'::date, '00000000-0000-0000-0000-000000000002', 'Memphis, Tennessee', NULL, 1300, ARRAY['sanitation', 'public_sector'], 'victory', ARRAY['living_wages', 'union_recognition', 'working_conditions'], ARRAY['AFSCME_recognition', 'wage_increases'], 0, 200, 'Police arrested strikers; national guard deployed but did not intervene after strike gained national attention', 'Strike of Memphis''s predominantly Black sanitation workers for living wages and union recognition, supported by Rev. Martin Luther King Jr., became focal point of civil rights and labor struggle intersection, won union recognition.', 'The Memphis sanitation strike demonstrates the power of organized workers fighting for dignity and living standards. King''s assassination during this struggle elevated it to tremendous symbolic and political significance, connecting racial and labor liberation.', 'Major labor and civil rights victory; demonstrated power of community support; became symbol of convergence of civil rights and labor struggle; tragic assassination of MLK elevated significance.'),

('770e8400-e29b-41d4-a716-446655440004', 'Haymarket Affair', 'general_strike', '1886-05-01'::date, '1886-05-05'::date, '00000000-0000-0000-0000-000000000002', 'Chicago, Illinois', NULL, 80000, ARRAY['manufacturing', 'multi_sector'], 'suppressed', ARRAY['eight_hour_day', 'wages', 'working_conditions'], ARRAY[], 11, 100, 'Police fired on crowd; bomb allegedly thrown by anarchists killed police; workers blamed; anarchists executed despite weak evidence', 'Mass demonstration for eight-hour workday in Chicago that became battleground between workers and police. Alleged anarchist bomb at subsequent police confrontation led to execution of four anarchists despite no clear evidence they threw it.', 'Haymarket represents both the power of working-class self-organization and the violence of state repression against workers. The execution of innocent workers fueled international labor and radical movements, making May 1 International Workers Day.', 'Origins of International Workers Day; demonstrated state violence against workers; execution of anarchists became rallying point for international labor and radical movements; shaped American labor radicalism.'),

-- Historical European strikes
('770e8400-e29b-41d4-a716-446655440005', 'UK General Strike', 'general_strike', '1926-05-03'::date, '1926-05-13'::date, '00000000-0000-0000-0000-000000000003', 'United Kingdom', '660e8400-e29b-41d4-a716-446655440008', 1700000, ARRAY['mining', 'transport', 'multi_sector'], 'defeat', ARRAY['mining_wages', 'living_standards'], ARRAY[], 0, 0, 'Government declared state of emergency; police presence increased but general suppression was primarily ideological/political', 'National general strike across British industry called to support miners'' struggle for higher wages and better conditions. Though it paralyzed the nation for nine days, union leadership negotiated an end without major concessions, demoralizing the movement.', 'The 1926 General Strike demonstrated the power of coordinated British labor and the potential of general strike strategy. However, the betrayal by union bureaucracy showed the limitations of official union structures and the need for workers'' independent organization.', 'Largest British strike in history; demonstrated potential of general strike; showed limits of union bureaucracy; influenced development of workers'' control and syndicalist theory.'),

('770e8400-e29b-41d4-a716-446655440006', 'Gdańsk Shipyard Strike (Solidarity)', 'industry_strike', '1980-08-14'::date, '1980-09-01'::date, '00000000-0000-0000-0000-000000000006', 'Gdańsk', '660e8400-e29b-41d4-a716-446655440016', 17000, ARRAY['shipbuilding', 'manufacturing'], 'victory', ARRAY['union_recognition', 'wages', 'political_prisoners'], ARRAY['Solidarity_legalization', 'wage_increases'], 0, 0, 'Communist government initially repressed but ultimately recognized Solidarity under pressure from international attention and broader unrest', 'Strike by Polish shipyard workers in Gdańsk that became catalyst for broader Solidarity movement against communist government. Strike demand for independent unions directly challenged state monopoly on labor organization, becoming focal point for anti-communist opposition.', 'The Gdańsk strikes demonstrated the potential for organized labor to challenge state authority, even in supposed workers'' states. However, the subsequent direction of Solidarity toward anti-communist politics and market capitalism complicated its class character and legacy.', 'Catalyst for Solidarity movement; accelerated collapse of Polish communist regime; complicated legacy due to anti-communist trajectory; represents limits of trade union organization for radical change.'),

('770e8400-e29b-41d4-a716-446655440007', 'French General Strike 1968', 'general_strike', '1968-05-13'::date, '1968-06-16'::date, '00000000-0000-0000-0000-000000000004', 'France', '660e8400-e29b-41d4-a716-446655440011', 9000000, ARRAY['multi_sector'], 'partial_victory', ARRAY['wages', 'working_conditions', 'student_rights'], ARRAY['wage_increases', 'reduced_working_hours'], 0, 1000, 'Government deployed police against youth and students; minimal direct military force; Gaullist backlash in June elections', 'Massive general strike that grew from student rebellion in Paris, spread across France paralyzing the economy. At its height, general strike involved major sectors including auto, rail, and public sector workers. Though workers won wage increases, the radical potential was demobilized through union negotiations.', 'The May 1968 general strike demonstrated the powerful potential of united youth and labor action. However, union betrayal of the strike by signing a deal with the government that claimed victory while containin radical impulses showed the limitations of union leadership focused on negotiation rather than transformation.', 'Largest general strike since 1947; nearly brought down De Gaulle government; demonstrated working-class power in advanced capitalist country; showed limits of union negotiation for fundamental change.'),

-- Historical Latin American strikes
('770e8400-e29b-41d4-a716-446655440008', 'Bolivian Miners'' General Strike', 'general_strike', '1946-04-01'::date, '1946-06-30'::date, '00000000-0000-0000-0000-000000000015', 'Bolivia', NULL, 50000, ARRAY['mining'], 'partial_victory', ARRAY['wages', 'working_conditions', 'nationalization'], ARRAY['wage_increases', 'working_conditions_improvement'], 150, 300, 'Military and police repression with significant casualties; government made concessions under pressure', 'Massive miners'' strike that combined labor demands with broader revolutionary agenda including nationalization of mines. Despite violent repression, miners won important concessions and demonstrated powerful working-class consciousness.', 'The Bolivian miners strike demonstrates the revolutionary potential of organized workers in Latin America. The militancy and class consciousness of Bolivian miners has remained a model of working-class struggle in the region.', 'One of most important Latin American labor struggles; demonstrated revolutionary consciousness of miners; influenced later Bolivian labor movements; connected labor struggle to anti-imperialist demands.'),

-- Asian strike
('770e8400-e29b-41d4-a716-446655440009', 'Busan General Strike', 'general_strike', '1992-09-01'::date, '1992-11-20'::date, '00000000-0000-0000-0000-000000000014', 'Busan', '660e8400-e29b-41d4-a716-446655440024', 500000, ARRAY['manufacturing', 'multi_sector'], 'partial_victory', ARRAY['wages', 'union_rights', 'working_conditions'], ARRAY['minimum_wage_increases', 'working_conditions_improvements'], 0, 500, 'Heavy police crackdown with arrests of strike leaders; government negotiated settlements after international pressure', 'Massive general strike in South Korea''s Busan city involving hundreds of thousands of workers from manufacturing and other sectors, demonstrating class consciousness against authoritarian labor policies and demanding union rights.', 'The Busan strike represents South Korean workers'' continued struggle against repressive conditions and the state. It demonstrates the vibrant but suppressed labor movements in South Korea and the need for international solidarity against state repression.', 'Major South Korean labor demonstration; showed working-class power despite severe state repression; contributed to slow liberalization of labor rights in South Korea; demonstrated global significance of Asian working-class movements.'),

-- Contemporary strikes
('770e8400-e29b-41d4-a716-446655440010', 'Chicago Teachers Strike', 'industry_strike', '2012-09-10'::date, '2012-09-18'::date, '00000000-0000-0000-0000-000000000002', 'Chicago, Illinois', NULL, 30000, ARRAY['education', 'public_sector'], 'partial_victory', ARRAY['job_security', 'evaluation_reform', 'wages'], ARRAY['wage_increase', 'evaluation_reform'], 0, 50, 'Mayor and school board attempted to pressure through school closure threats; negotiated settlement after strike', 'Strike by Chicago teachers challenging standardized testing-based evaluation reforms, job insecurity, and education cuts. Teachers won concessions while maintaining strike''s radical critiques of neoliberal education policy.', 'The Chicago teachers strike represented important resistance to neoliberal education attacks. It demonstrated the potential for public sector workers to connect their struggles to broader opposition to inequality and education commodification.', 'Important 21st century labor victory; demonstrated public sector workers'' power; challenged neoliberal education policies; influenced education debates nationally.'),

('770e8400-e29b-41d4-a716-446655440011', 'West Virginia Teachers Strike', 'industry_strike', '2018-02-22'::date, '2018-03-02'::date, '00000000-0000-0000-0000-000000000002', 'West Virginia', NULL, 34000, ARRAY['education', 'public_sector'], 'partial_victory', ARRAY['wage_increases', 'healthcare_benefits', 'funding'], ARRAY['five_percent_raise', 'reduced_healthcare_costs'], 0, 0, 'Republican state government initially resisted but capitulated to massive pressure and sympathy from other workers', 'Strike of West Virginia teachers for wage increases and against healthcare cost increases that were devastating workers. Strike gained massive public support, particularly from other workers, spreading sympathy strikes across region.', 'The West Virginia strike demonstrated the power of public sector workers to challenge austerity and the potential for wildfire strikes to spread. It represented a rekindling of labor militancy in the 2010s.', 'Important contemporary strike wave catalyst; demonstrated public sector power; inspired similar teacher strikes nationwide; showed potential for general working-class solidarity.'),

-- Additional significant strikes
('770e8400-e29b-41d4-a716-446655440012', 'Oshawa General Motors Strike', 'industry_strike', '2019-09-16'::date, '2019-10-25'::date, '00000000-0000-0000-0000-000000000016', 'Oshawa, Ontario', NULL, 4200, ARRAY['automotive', 'manufacturing'], 'partial_victory', ARRAY['job_security', 'wages', 'plant_closure_prevention'], ARRAY['wage_increases', 'job_commitments'], 0, 0, 'GM conceded significant demands after 40-day strike despite right-wing government opposition', 'Strike by Canadian auto workers against plant closure threats and for job security and wage increases. Strike demonstrated workers'' power to extract concessions even in context of global auto industry rationalization.', 'The Oshawa strike demonstrated Canadian workers'' militancy and ability to organize significant industrial action. It represents important resistance to deindustrialization and capital''s class warfare against workers.', 'Important North American auto strike; demonstrated workers'' power; challenged plant closures; influenced auto industry negotiations; showed potential for union militancy.'),

('770e8400-e29b-41d4-a716-446655440013', 'Los Angeles Teachers Strike', 'industry_strike', '2019-01-14'::date, '2019-01-23'::date, '00000000-0000-0000-0000-000000000002', 'Los Angeles, California', NULL, 34000, ARRAY['education', 'public_sector'], 'partial_victory', ARRAY['wage_increases', 'class_size_reduction', 'funding_increases'], ARRAY['salary_increases', 'some_class_size_reductions'], 0, 10, 'School district attempted pressure through threat of continuing operations; strike won concessions after 10 days', 'Strike of Los Angeles teachers for wage increases, class size reduction, and increased school funding. Strike gained broad community support and raised questions about education as basic right versus commodity.', 'The LA teachers strike continued the emerging wave of education worker militancy challenging neoliberal austerity. It demonstrated teachers'' power to organize mass work stoppages and connected education struggles to broader working-class demands.', 'Second-largest US school district struck; inspired national teacher strike wave; challenged education austerity; demonstrated teachers'' leverage and broad community support.');

-- Verify data
SELECT COUNT(*) as labor_org_count FROM labor_organizations;
SELECT COUNT(*) as strike_count FROM strikes;
