-- Seed data for media resources
-- This file populates media_resources table with documentaries, films, and podcasts

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

INSERT INTO media_resources (id, title, title_original, media_type, release_year, director, producer, creator, description, synopsis, primary_url, youtube_url, language, topics, regions, time_period_start, time_period_end, progressive_relevance) VALUES

-- Major Political Documentaries
('880e8400-e29b-41d4-a716-446655440001', 'Manufacturing Consent: The Political Economy of the Mass Media', NULL, 'documentary', 2002, 'Mark Achbar, Peter Wintonick', NULL, NULL, 'Documentary based on Chomsky and Herman''s groundbreaking analysis of how media serves as propaganda arm of capitalist ruling class, examining the political economy of news media and its role in manufacturing consent for imperial policies.', 'Based on Noam Chomsky and Edward Herman''s theory of media propaganda, this documentary examines how mainstream media corporations serve ruling-class interests, controlling information to support capitalism and imperialism while marginalizing dissent.', 'https://www.criterion.com/films/807-manufacturing-consent-the-political-economy-of-the-mass-media', 'https://www.youtube.com/watch?v=EuwVgzFvBv4', 'English', ARRAY['media_criticism', 'propaganda', 'political_economy', 'imperialism'], ARRAY['North America'], 1980, 2002, 'Essential analysis of how capitalist media manufactures consent for ruling-class policies and wars, demonstrating the ideological function of supposedly objective journalism.'),

('880e8400-e29b-41d4-a716-446655440002', 'The Act of Killing', NULL, 'documentary', 2012, 'Joshua Oppenheimer', NULL, NULL, 'Documentary exploring Indonesian death squads'' murders of over 1 million people during 1965-66 anti-communist purges, featuring perpetrators reflecting on and recreating their killings, examining how capitalist regimes justify mass violence through propaganda and denial.', 'Unprecedented documentary where Indonesian death squad leaders recreate and reflect upon their mass murders during the 1965-66 anti-communist purges. Reveals how perpetrators rationalize genocide through nationalist and anti-communist propaganda, showing the violence endemic to capitalist restoration.', 'https://www.criterion.com/films/772-the-act-of-killing', 'https://www.youtube.com/watch?v=cUXfvH6kFZ8', 'Indonesian', ARRAY['anti_communism', 'genocide', 'imperialism', 'cold_war'], ARRAY['Asia', 'Indonesia'], 1965, 2012, 'Devastating documentation of capitalist anti-communist violence and the genocide committed in service of US-backed regime change, exposing the brutality underlying supposedly liberal democratic order.'),

('880e8400-e29b-41d4-a716-446655440003', '13th', NULL, 'documentary', 2016, 'Ava DuVernay', NULL, NULL, 'Documentary examining the 13th Amendment of the US Constitution and mass incarceration''s role in perpetuating racial slavery and capitalist extraction of Black labor, tracing the history from slavery through present-day carceral state.', 'Named after the 13th Amendment which abolished slavery ''except as punishment for crime,'' this documentary traces how the criminal justice system has become a vehicle for perpetuating racial slavery and extracting Black labor under the guise of criminal punishment.', 'https://www.netflix.com/title/80091741', 'https://www.youtube.com/watch?v=krfcq5pF8u8', 'English', ARRAY['racism', 'mass_incarceration', 'slavery', 'capitalism', 'united_states'], ARRAY['North America'], 1865, 2016, 'Essential analysis of how the US criminal justice system perpetuates racial slavery and capitalist exploitation of Black people, showing connections between slavery abolition and mass incarceration.'),

('880e8400-e29b-41d4-a716-446655440004', 'I Am Not Your Negro', NULL, 'documentary', 2016, 'Raoul Peck', NULL, NULL, 'Documentary based on James Baldwin''s unfinished manuscript, examining racism in America through Baldwin''s powerful analysis of the Black struggle, connecting racism to capitalism and imperialism in Baldwin''s revolutionary vision.', 'Based on James Baldwin''s unfinished book manuscript "Remember This House," the documentary traces the lives and deaths of Malcolm X, Medgar Evers, and Martin Luther King, while examining racism as systemic feature of American capitalism.', 'https://www.criterion.com/films/1179-i-am-not-your-negro', 'https://www.youtube.com/watch?v=r6DFz0pKSKw', 'English', ARRAY['racism', 'black_liberation', 'baldwin', 'united_states'], ARRAY['North America'], 1940, 2016, 'Baldwin''s revolutionary analysis of racism as systemic to American capitalism, connecting Black liberation struggle to broader anti-imperial vision for human emancipation.'),

('880e8400-e29b-41d4-a716-446655440005', 'The Square', NULL, 'documentary', 2013, 'Jehane Noujaim', NULL, NULL, 'Documentary following Egyptian revolution in Tahrir Square from 2011 through 2013, capturing youth-led struggle against Mubarak dictatorship and subsequent battles against military rule, documenting revolutionary process and popular power in action.', 'Following the 2011 Egyptian revolution, the documentary captures activists in Tahrir Square fighting against military repression and authoritarianism, showing the ongoing struggle for liberation after Mubarak''s fall and the challenges of sustaining revolution.', 'https://www.pbs.org/wgbh/frontline/film/the-square/', 'https://www.youtube.com/watch?v=jH2_2r3PlXo', 'Arabic/English', ARRAY['revolution', 'egypt', 'arab_spring', 'youth_movements', 'anti_imperialism'], ARRAY['Middle East', 'North Africa'], 2011, 2013, 'Documentary of the Egyptian revolution showing popular power against authoritarianism, the challenges of revolutionary struggle against military and imperial interests, and the ongoing fight for dignity and liberation.'),

('880e8400-e29b-41d4-a716-446655440006', 'Winter on Fire: Ukraine''s Fight for Freedom', NULL, 'documentary', 2015, 'Evgeny Afineevsky', NULL, NULL, 'Documentary about Euromaidan protests in Ukraine 2013-2014, covering mass protests against Yanukovych government, showing scenes of violence, police repression, and popular struggle against authoritarian rule and corruption.', 'Chronicles the 2013-2014 Euromaidan protests in Ukraine where thousands of people occupied central Kiev opposing government rejection of EU trade deal, facing police violence and state repression in struggle for democratic change.', 'https://www.netflix.com/title/80031666', 'https://www.youtube.com/watch?v=zzC48ksVVMQ', 'Ukrainian/English', ARRAY['ukraine', 'protest', 'euromaidan', 'police_violence', 'russia', 'imperialism'], ARRAY['Eastern Europe'], 2013, 2015, 'Documentation of popular struggle against corruption and authoritarianism in Ukraine, though it should be contextualized within broader geopolitical struggles between Russian and Western imperialism over Eastern European influence.'),

('880e8400-e29b-41d4-a716-446655440007', 'The Killing of the Uni Students', NULL, 'documentary', 2007, 'Ivan Marquez, Marcela Godoy', NULL, NULL, 'Documentary examining assassination of Colombian university students by government forces and paramilitary groups during Plan Colombia era, revealing state terrorism and US imperialist war in Colombia disguised as drug war.', 'Investigation of assassinations of Colombian university students by government forces and paramilitaries during US-backed Plan Colombia, revealing state terrorism and extra-judicial killings in service of counterinsurgency against FARC guerrillas.', NULL, 'https://www.youtube.com/watch?v=7mGzqKWrw1I', 'Spanish', ARRAY['colombia', 'imperialism', 'state_violence', 'paramilitaries', 'plan_colombia'], ARRAY['Latin America', 'Colombia'], 2000, 2007, 'Exposes US-backed state terrorism in Colombia, showing how imperialist drug war masks counterinsurgency against leftist guerrillas and suppression of popular movements.'),

('880e8400-e29b-41d4-a716-446655440008', 'The Trials of Muhammad Ali', NULL, 'documentary', 2013, 'Ken Burns, Sarah Burns, David McMahon', NULL, NULL, 'Documentary about Muhammad Ali''s refusal to serve in Vietnam War, his struggle against racism, and his political transformation, showing connections between boxing, race, and anti-imperialism in 1960s America.', 'Chronicles Muhammad Ali''s career and political transformation, focusing on his refusal to be drafted into Vietnam War, his conversion to Islam, and his struggles against racism, connecting boxing sport to broader civil rights and anti-war movements.', 'https://www.pbs.org/wgbh/americanexperience/films/muhammadali/', 'https://www.youtube.com/watch?v=eAZR4rB9Usk', 'English', ARRAY['boxing', 'vietnam_war', 'anti_war', 'civil_rights', 'islam', 'united_states'], ARRAY['North America'], 1964, 2013, 'Ali''s courageous refusal to serve in imperialist war and his political evolution demonstrates the potential for prominent figures to speak truth to power and connect sports to broader struggles for justice.'),

-- Revolutionary and Liberation Struggle Documentaries
('880e8400-e29b-41d4-a716-446655440009', 'Cuba: A Revolution in Motion', NULL, 'documentary', 2011, 'Various directors', NULL, NULL, 'Documentary series examining Cuban revolution from 1959 through present, exploring Fidel Castro''s transformation from guerrilla leader to revolutionary president, the construction of socialism in face of US blockade, and Cuba''s anti-imperial foreign policy.', 'Comprehensive examination of Cuban revolution, from Fidel and Raul Castro''s guerrilla war to revolutionary victory and construction of socialism facing US blockade and invasion attempts. Shows anti-imperialist internationalism and socialist development in Latin America.', NULL, 'https://www.youtube.com/watch?v=7C_dW_m4dYk', 'Spanish/English', ARRAY['cuba', 'revolution', 'socialism', 'imperialism', 'anti_imperialism'], ARRAY['Latin America', 'Caribbean', 'Cuba'], 1959, 2011, 'The Cuban revolution represents crucial victory against imperialism and construction of socialism. Despite limitations and contradictions, it demonstrates the possibility of escaping imperialist domination and building alternative economic system.'),

('880e8400-e29b-41d4-a716-446655440010', 'My Pal Foot Foot', NULL, 'documentary', 2016, 'Maïa Winckler', NULL, NULL, 'Documentary exploring Palestinian resistance through underground music scene, showing Palestinian youth''s cultural production and political consciousness despite occupation and apartheid conditions in Gaza.', 'Documentary featuring Palestinian youth musicians and activists in Gaza, showing how young Palestinians express resistance and maintain hope and cultural production despite occupation, apartheid conditions, and siege.', NULL, 'https://www.youtube.com/watch?v=0KjWH0cRqRk', 'Arabic/English', ARRAY['palestine', 'resistance', 'occupation', 'youth_culture', 'gaza'], ARRAY['Middle East', 'Palestine'], 2007, 2016, 'Palestinian youth''s cultural resistance in Gaza shows the resilience and humanity of those living under occupation and siege, maintaining dignity and artistic expression despite oppression.'),

('880e8400-e29b-41d4-a716-446655440011', 'Gaza Strip and Gilo (Wall)', NULL, 'documentary', 2004, 'Khaled Jarrar', NULL, NULL, 'Documentary examining construction of Israeli apartheid wall in Palestinian territories, showing its devastating impact on Palestinian communities, water sources, and livelihoods, connecting to broader Israeli colonialism and Palestinian dispossession.', 'Documentary about the construction of Israel''s apartheid wall separating Palestinian communities, destroying agricultural lands and water sources, trapping people in open-air prison conditions while enabling continued Israeli occupation and colonization.', NULL, 'https://www.youtube.com/watch?v=rGzN3xpCl8g', 'Arabic', ARRAY['palestine', 'israel', 'apartheid', 'colonialism', 'occupation', 'wall'], ARRAY['Middle East', 'Palestine'], 2000, 2004, 'Documentation of Israeli apartheid wall shows the systematic nature of Israeli colonialism and the catastrophic impacts on Palestinian peoples'' ability to live and maintain livelihoods.'),

-- Historical and Educational Films
('880e8400-e29b-41d4-a716-446655440012', 'The Battle of Algiers', 'La battaglia di Algeri', 'film', 1966, 'Gillo Pontecorvo', NULL, NULL, 'Legendary film depicting Algerian war of independence against French colonialism 1954-1962, showing techniques of urban guerrilla warfare, popular support for liberation, and the costs of anti-colonial struggle, revolutionary in its portrayal and technique.', 'Gillo Pontecorvo''s masterpiece dramatizing the Algerian war of independence, showing urban guerrilla warfare tactics, popular support, women''s participation, and the brutality of colonial occupation and French counterinsurgency against revolutionary liberation struggle.', NULL, 'https://www.youtube.com/watch?v=QE55LNP7CFI', 'Arabic/French/Italian', ARRAY['algeria', 'colonialism', 'anti_colonialism', 'independence', 'guerrilla_war'], ARRAY['North Africa', 'Algeria', 'France'], 1954, 1966, 'The Battle of Algiers remains essential revolutionary cinema, showing the potential of popular anti-colonial armed struggle and the brutal violence colonialism employs to maintain control. The film itself became target of US military interest.'),

('880e8400-e29b-41d4-a716-446655440013', 'Land and Freedom', NULL, 'film', 1995, 'Ken Loach', NULL, NULL, 'Film depicting British volunteer''s participation in Spanish Civil War on Republican side against Franco''s fascist rebellion, showing the class nature of Spanish Civil War and revolutionary Spanish workers'' militias, the betrayal by Soviet Stalinists, and the tragedy of fascist victory.', 'Ken Loach''s historical drama following a young British communist who joins Spanish Civil War on republican side, fighting alongside revolutionary workers and militias. Shows the class struggle within the war, the role of anarchist and communist collectives, and tragic defeat by Franco''s fascism.', NULL, 'https://www.youtube.com/watch?v=b-L7i7ZqvZo', 'English/Spanish', ARRAY['spanish_civil_war', 'fascism', 'communism', 'revolution', 'working_class'], ARRAY['Europe', 'Spain'], 1936, 1995, 'Land and Freedom captures the revolutionary potential of the Spanish Civil War and the tragedy of defeat by fascism. It shows the heroic struggle of ordinary workers and the betrayal by Stalinist communists who sacrificed revolution for diplomatic alliance with imperialism.'),

('880e8400-e29b-41d4-a716-446655440014', 'Persepolis', NULL, 'film', 2007, 'Marjane Satrapi', 'Vincent Paronnaud', NULL, 'Animated film based on autobiographical graphic novel of Iranian artist growing up during Islamic Revolution and Iran-Iraq War, showing youth perspective on revolution and its contradictions, the war''s devastation, and personal liberation through artistic expression.', 'Animated adaptation of Marjane Satrapi''s graphic memoir showing her childhood in Iran during Islamic revolution and Iran-Iraq War, capturing the revolutionary upheaval and its contradictions, state repression of women and youth, and search for personal freedom.', NULL, 'https://www.youtube.com/watch?v=mrOxZ9Hg_Dw', 'French/Persian', ARRAY['iran', 'revolution', 'feminism', 'war', 'memoir'], ARRAY['Middle East', 'Iran'], 1979, 2007, 'Persepolis offers authentic perspective on Iranian revolution from viewpoint of someone who lived through it, showing both revolutionary potential and the patriarchal, authoritarian aspects that developed, while celebrating youth resistance.'),

('880e8400-e29b-41d4-a716-446655440015', 'The Wind That Shakes the Barley', NULL, 'film', 2006, 'Ken Loach', NULL, NULL, 'Film depicting Irish War of Independence and subsequent Irish Civil War, showing Irish rebels'' struggle against British colonialism and the division and civil war between those accepting partition and those committed to full independence and revolutionary socialism.', 'Ken Loach''s film about Irish independence struggle, following brothers fighting British occupation during War of Independence and then finding themselves on opposing sides in the Civil War between those accepting partition and those fighting for full liberation.', NULL, 'https://www.youtube.com/watch?v=q1nHKYKWEso', 'English/Irish', ARRAY['ireland', 'colonialism', 'independence', 'civil_war', 'british_imperialism'], ARRAY['Europe', 'Ireland'], 1916, 2006, 'The Wind That Shakes the Barley shows the class and ideological divisions within national liberation struggles, depicting Irish workers and peasants fighting colonialism and then struggling over the direction of the new state.'),

('880e8400-e29b-41d4-a716-446655440016', 'Salt of the Earth', NULL, 'film', 1954, 'Herbert J. Biberman', NULL, NULL, 'Film depicting 1951 New Mexico zinc miners'' strike by Mexican-American workers, showing women''s crucial role in sustaining strike against company and government repression, made by blacklisted communist filmmakers, revolutionary realism combined with political content.', 'The only narrative feature film made by blacklisted communist filmmakers in 1950s America, depicting a miners'' strike led by Mexican-American workers, showing women''s vital role in labor struggle and the intersection of class and racial oppression.', NULL, 'https://www.youtube.com/watch?v=JRLX4yNdIyw', 'English/Spanish', ARRAY['labor_strike', 'mining', 'mexican_american', 'women', 'racism', 'united_states'], ARRAY['North America'], 1951, 1954, 'Salt of the Earth represents radical workers'' cinema, showing ordinary miners as heroes of their own liberation struggle, centering women''s participation, and made by blacklisted communists during McCarthy-era repression.'),

-- Documentary Podcasts and Audio
('880e8400-e29b-41d4-a716-446655440017', 'Revolutions Podcast', NULL, 'podcast', 2013, NULL, NULL, 'Mike Duncan', 'Podcast series examining historical revolutions from various countries and periods, exploring causes, progress, and outcomes of revolutionary struggles, from American and French revolutions through Cuban, Russian, and Haitian revolutions, using archival research and narrative storytelling.', 'Comprehensive podcast series examining major historical revolutions including American, French, Haitian, Latin American, and other revolutionary struggles. Host uses primary sources to tell revolutionary stories and analyze what made revolutions succeed or fail.', 'https://www.revolutionspodcast.com/', NULL, 'English', ARRAY['revolution', 'history', 'social_movements'], ARRAY['Multiple'], 1776, 2021, 'The Revolutions podcast provides accessible introduction to revolutionary history, examining both successes and failures of revolutionary movements, useful for understanding continuity of liberation struggles across time.'),

('880e8400-e29b-41d4-a716-446655440018', 'Behind the Bastards', NULL, 'podcast', 2018, NULL, NULL, 'Robert Evans', 'Podcast investigating historical and contemporary bastards (authoritarian leaders, capitalists, fascists, imperialists), examining how ordinary people are harmed by abuses of power, connecting history to contemporary politics and resistance.', 'Podcast examining histories of authoritarian leaders, fascists, capitalists, and their crimes against humanity. Each episode tells stories of victims and resistance, analyzing power structures that enable exploitation and brutality.', 'https://www.iheart.com/podcast/105-behind-the-bastards-49873/', NULL, 'English', ARRAY['history', 'authority', 'fascism', 'capitalism', 'resistance'], ARRAY['Multiple'], 1800, 2024, 'Behind the Bastards connects historical atrocities to contemporary capitalism and authoritarianism, emphasizing resistance and the human cost of power abuse, with radical editorial perspective.'),

('880e8400-e29b-41d4-a716-446655440019', 'Citations Needed', NULL, 'podcast', 2017, NULL, NULL, 'Adam Johnson, Nima Shirazi', 'Podcast analyzing media coverage and narratives, exposing bias, propaganda, and structural failures in mainstream media, particularly regarding foreign policy, imperialism, and the reproduction of capitalist ideology.', 'Podcast deconstructing mainstream media narratives, exposing how corporate media reproduces propaganda supporting imperialism, capitalism, and ruling-class interests while marginalizing working-class and anti-imperialist voices.', 'https://citationsneeded.medium.com/', NULL, 'English', ARRAY['media_criticism', 'propaganda', 'imperialism', 'capitalism'], ARRAY['North America'], 2017, 2024, 'Citations Needed provides crucial media analysis exposing how supposedly objective journalism systematically reproduces capitalist and imperialist narratives while marginalizing radical perspectives.'),

-- Additional Important Media
('880e8400-e29b-41d4-a716-446655440020', 'Killing Hope: US Military and CIA Interventions Since World War II', NULL, 'documentary', 2000, 'Various', NULL, NULL, 'Documentary series examining US military and CIA interventions around the world since 1945, documenting how US imperialism has toppled democracies, sponsored dictatorships, and killed millions in service of corporate profit and geopolitical control.', 'Based on William Blum''s historical research, documentary catalogs US military and CIA interventions globally since WWII, showing systematic pattern of US imperialism supporting dictatorships, overthrowing democracies, and committing massive violence.', NULL, 'https://www.youtube.com/watch?v=kDy8OG7nJqs', 'English', ARRAY['imperialism', 'united_states', 'military', 'cia', 'interventions', 'cold_war'], ARRAY['Multiple'], 1945, 2000, 'Essential documentation of US imperial violence globally, showing how American foreign policy is fundamentally aggressive and that US involvement typically makes things worse for ordinary people.'),

('880e8400-e29b-41d4-a716-446655440021', 'Century of Enslavement: The History of the Federal Reserve', NULL, 'documentary', 2014, 'James Corbett', NULL, NULL, 'Documentary examining history of Federal Reserve in United States, showing how banking system serves capitalist class interests, controls monetary policy to benefit the wealthy, and perpetuates economic inequality and debt-based economic system.', 'Corbett Report documentary tracing Federal Reserve''s creation and role in American capitalism, showing how central banking serves financial elite interests, inflates money supply for wars and speculation, and maintains debt-based economic system.', NULL, 'https://www.youtube.com/watch?v=5XcKBmjQBGM', 'English', ARRAY['economics', 'finance', 'capitalism', 'federal_reserve', 'united_states'], ARRAY['North America'], 1913, 2014, 'This documentary exposes how financial systems perpetuate capitalist control and inequality, showing how banking serves elite interests through manipulation of monetary policy and creation of unpayable debt.'),

('880e8400-e29b-41d4-a716-446655440022', 'The Shock Doctrine', NULL, 'documentary', 2009, NULL, NULL, NULL, 'Based on Naomi Klein''s theory that capitalism uses crisis and disaster to impose radical neoliberal reforms, documentary shows how disaster capitalism operates globally, impoverishing people while enriching corporations and elites.', 'Naomi Klein''s concept of ''shock doctrine'' illustrated through documentaries showing how capitalists use wars, natural disasters, and engineered crises to impose neoliberal austerity and privatization while poor people pay the costs.', NULL, 'https://www.youtube.com/watch?v=i5Rl13PnEDc', 'English', ARRAY['neoliberalism', 'disaster', 'capitalism', 'austerity', 'imperialism'], ARRAY['Multiple'], 1970, 2009, 'The shock doctrine shows how capitalism systematically exploits crises to impose policies benefiting the rich while impoverishing the poor, demonstrating that capitalism is fundamentally violent and predatory.'),

('880e8400-e29b-41d4-a716-446655440023', 'In Jackson Heights', NULL, 'documentary', 2015, 'Frederick Wiseman', NULL, NULL, 'Observational documentary showing life in Jackson Heights, Queens, examining intersection of immigration, labor, capitalism, and community life in New York immigrant neighborhood, showing workers'' struggles and community resistance.', 'Frederick Wiseman''s multi-hour documentary observing everyday life, commercial activity, and community organizing in Jackson Heights, Queens, one of America''s most immigrant-dense neighborhoods, showing class and cultural dynamics.', NULL, 'https://www.youtube.com/watch?v=rJTvk-p7lJY', 'English/Spanish', ARRAY['immigration', 'labor', 'community', 'united_states', 'new_york'], ARRAY['North America'], 2015, 2015, 'In Jackson Heights captures the vitality of immigrant working-class communities and their resistance to displacement and exploitation through gentrification and capitalist development.'),

('880e8400-e29b-41d4-a716-446655440024', 'All Watched Over by Machines of Loving Grace', NULL, 'documentary', 2011, 'Adam Curtis', NULL, NULL, 'Three-part documentary by Adam Curtis examining how networked digital systems promise liberation but actually extend capitalism''s control, examining relationship between technology, nature, and capitalist power, from Silicon Valley to genetic engineering.', 'Adam Curtis'' series examining how digital networks and technology are presented as liberatory but actually extend capitalist control over nature and society. Traces connections between Silicon Valley, Cold War science, and contemporary digital capitalism.', NULL, 'https://www.youtube.com/watch?v=sMOpI_CFhfU', 'English', ARRAY['technology', 'capitalism', 'silicon_valley', 'digital_systems', 'nature'], ARRAY['North America'], 1950, 2011, 'Curtis'' documentary shows how technology under capitalism perpetuates rather than challenges inequality and control, offering critical perspective on techno-utopianism and its role in reproducing capitalist domination.');

-- Verify inserts
SELECT COUNT(*) as media_count FROM media_resources;
