-- Seed data for research pathways and featured collections
-- This file populates research_pathways, pathway_nodes, featured_collections, and collection_items

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Insert Research Pathways

INSERT INTO research_pathways (id, title, slug, description, category, difficulty_level, estimated_time_minutes, introduction, conclusion, tags, regions, start_year, end_year, is_published, featured) VALUES

('990e8400-e29b-41d4-a716-446655440001', 'Understanding Colonialism and Imperialism', 'colonialism-imperialism', 'Comprehensive pathway exploring the history of European colonialism and US imperialism, from 1500s through present day, examining how colonialism extracted wealth from the Global South while enriching European and American capital.', 'anti_colonial', 'beginner', 180, 'Colonialism was the foundational project of European capitalism, establishing global systems of extraction and domination that persist today as imperialism. This pathway explores how colonialism worked, who profited, and how colonized peoples fought for liberation.', 'Understanding colonialism and imperialism is essential for anti-capitalist politics. The Global North''s wealth rests on centuries of colonial extraction, and liberation struggles in the Global South represent crucial components of world revolutionary movements.', ARRAY['colonialism', 'imperialism', 'global_north', 'global_south', 'exploitation'], ARRAY['Africa', 'Asia', 'Latin America', 'Middle East'], 1500, 2024, true, true),

('990e8400-e29b-41d4-a716-446655440002', 'History of the Labor Movement', 'labor-movement-history', 'Guided tour through labor movement history from early industrial period through present day, examining strikes, unions, working-class organization, revolutionary struggles of workers, and the ongoing fight for workers'' liberation.', 'labor', 'intermediate', 240, 'Working-class struggle has driven most significant social changes in history. This pathway traces labor movements globally, showing how ordinary workers organized to fight exploitation and how their struggles continue today.', 'The labor movement represents the organized power of the working class. Today''s labor struggles inherit traditions of decades of struggle and offer potential for transforming society through workers'' power.', ARRAY['labor', 'working_class', 'strikes', 'unions', 'exploitation'], ARRAY['Multiple'], 1750, 2024, true, true),

('990e8400-e29b-41d4-a716-446655440003', 'Palestinian Liberation and Occupied Territories', 'palestine-liberation', 'Deep exploration of Palestinian history, Zionist colonialism, Israeli occupation, Palestinian resistance movements, and the struggle for Palestinian self-determination and return, examining both history and contemporary situation.', 'anti_colonial', 'advanced', 300, 'Palestine represents one of the most active and important contemporary liberation struggles. This pathway examines Palestinian history before and after Zionist colonization, Israeli occupation and apartheid, and Palestinian resistance.', 'The Palestinian struggle for liberation is essential to global anti-imperialist movements. Understanding Palestinian history and supporting Palestinian self-determination are crucial components of anti-colonial and anti-capitalist politics.', ARRAY['palestine', 'israel', 'colonialism', 'occupation', 'apartheid', 'resistance'], ARRAY['Middle East', 'Palestine'], 1900, 2024, true, true),

('990e8400-e29b-41d4-a716-446655440004', 'Feminist Theory and Women''s Liberation', 'feminist-theory', 'Exploration of feminist theory from early women''s rights movements through contemporary feminism, examining intersections with class struggle, imperialism, and racism, and women''s crucial role in liberation movements.', 'ideology', 'intermediate', 200, 'Women''s liberation is inseparable from broader liberation struggles. This pathway examines how women have fought for rights, dignity, and equality while also exploring how capitalism and imperialism maintain patriarchal oppression.', 'Feminist struggle must be grounded in understanding material roots of women''s oppression in capitalism and imperialism. Women are central to working-class and revolutionary movements globally.', ARRAY['feminism', 'women', 'patriarchy', 'liberation', 'intersectionality'], ARRAY['Multiple'], 1800, 2024, true, true),

('990e8400-e29b-41d4-a716-446655440005', 'Revolutionary Movements of the 20th Century', 'twentieth_century_revolutions', 'Comprehensive pathway examining major revolutionary movements in 20th century including Russian, Chinese, Cuban, Vietnamese, and other revolutions, analyzing their successes, challenges, and lessons for contemporary struggles.', 'revolution', 'advanced', 360, 'The 20th century witnessed multiple attempts to create socialist societies and overturn capitalist rule. This pathway examines these revolutions, their achievements and contradictions, and lessons for today''s movements.', 'Twentieth century revolutions represent crucial experiments in building socialism despite enormous internal and external pressures. Learning from both successes and failures informs contemporary anti-capitalist organizing.', ARRAY['revolution', 'communism', 'socialism', 'marxism', 'vanguard_party'], ARRAY['Multiple'], 1917, 2000, true, true),

('990e8400-e29b-41d4-a716-446655440006', 'Anti-Apartheid Struggle in South Africa', 'anti_apartheid_south_africa', 'Exploration of South African apartheid system, anti-apartheid movement, role of labor organizations and liberation movements like ANC and SACP, and transition to post-apartheid South Africa examining both achievements and ongoing struggles.', 'anti_colonial', 'intermediate', 200, 'South Africa''s apartheid system represented extreme racial oppression. This pathway examines how apartheid worked, how South Africans resisted it, and the ongoing struggle for racial and economic justice after apartheid''s formal end.', 'The anti-apartheid struggle demonstrates the power of organized resistance to even extreme oppression. However, the post-apartheid period shows that ending formal apartheid does not automatically solve economic oppression and racial inequality.', ARRAY['apartheid', 'south_africa', 'racism', 'liberation', 'labor_movement'], ARRAY['Africa', 'South Africa'], 1948, 2024, true, true),

('990e8400-e29b-41d4-a716-446655440007', 'Latin American Socialism and Revolution', 'latin_american_socialism', 'Guided tour through Latin American revolutionary and socialist movements from early 20th century through present, examining Cuban revolution, Nicaraguan revolution, FMLN in El Salvador, Zapatistas in Mexico, and contemporary left governments.', 'revolution', 'intermediate', 240, 'Latin America has been a center of socialist and revolutionary movements challenging US imperialism. This pathway examines these struggles, their victories and defeats, and their significance for global anti-imperialist movements.', 'Latin American liberation struggles represent important anti-imperialist victories and experiments in socialism. They continue to inspire global movements and offer lessons for organizing against imperialism and capitalism.', ARRAY['revolution', 'latin_america', 'socialism', 'imperialism', 'anti_americanism'], ARRAY['Latin America'], 1910, 2024, true, true),

('990e8400-e29b-41d4-a716-446655440008', 'Indigenous Movements and Sovereignty', 'indigenous_movements', 'Exploration of indigenous peoples'' struggles for sovereignty, land rights, cultural preservation, and liberation from colonialism and capitalism, examining both historical and contemporary indigenous resistance movements globally.', 'anti_colonial', 'intermediate', 220, 'Indigenous peoples have resisted colonialism and capitalism since the beginning of European conquest. This pathway examines indigenous movements for sovereignty, land rights, and cultural preservation, and connections to broader liberation struggles.', 'Indigenous movements represent crucial struggles against colonialism and capitalism. Their fight for sovereignty and land rights is inseparable from global anti-colonial and environmental liberation struggles.', ARRAY['indigenous', 'colonialism', 'sovereignty', 'land_rights', 'environment'], ARRAY['Multiple'], 1500, 2024, true, false),

('990e8400-e29b-41d4-a716-446655440009', 'Marxist Theory and Historical Materialism', 'marxist-theory', 'Deep dive into Marxist theory from Marx and Engels'' original works through contemporary Marxist analysis, examining historical materialism, class struggle, surplus value, imperialism, and Marxist approaches to analyzing capitalism.', 'ideology', 'advanced', 300, 'Marxism provides the most systematic analysis of capitalism and guide to working-class liberation. This pathway explores Marx''s theories, their development by subsequent Marxists, and contemporary applications to understanding imperialism and class struggle.', 'Marxist theory remains essential tool for understanding capitalism and envisioning liberation. Applying Marx''s methods to contemporary conditions enables workers to analyze exploitation and develop strategies for transformation.', ARRAY['marxism', 'theory', 'class', 'capitalism', 'historical_materialism'], ARRAY['Multiple'], 1850, 2024, true, false),

('990e8400-e29b-41d4-a716-446655440010', 'Anarchism and Libertarian Socialism', 'anarchism-libertarian', 'Exploration of anarchist and libertarian socialist traditions from 19th century through present, examining different anarchist currents, critiques of authoritarian socialism, direct action, mutual aid, and contemporary anarchist movements.', 'ideology', 'intermediate', 200, 'Anarchism offers distinctive approach to liberation emphasizing elimination of all hierarchies and forms of domination. This pathway explores anarchist theory, history, and practice, and ongoing debates within and between anarchist and Marxist traditions.', 'Anarchist movements represent important alternative frameworks for liberation. Contemporary organizing must engage with anarchist critiques and practices while maintaining commitment to working-class power.', ARRAY['anarchism', 'liberty', 'direct_action', 'mutual_aid', 'anti_authoritarian'], ARRAY['Multiple'], 1840, 2024, true, false),

('990e8400-e29b-41d4-a716-446655440011', 'US Imperialism and Interventions', 'us-imperialism', 'Comprehensive examination of US imperialism from Spanish-American War through present day, showing pattern of US military interventions, CIA coups, support for dictatorships, and ongoing global domination for corporate profit.', 'anti_colonial', 'intermediate', 260, 'The United States is the world''s greatest imperialist power. This pathway examines how US has intervened militarily in dozens of countries, overthrown democracies, and killed millions in service of corporate interests.', 'Understanding US imperialism is crucial for anti-imperialist organizing. US imperialism remains the greatest threat to liberation movements globally and must be confronted as integral to anti-capitalist struggle.', ARRAY['us_imperialism', 'military_intervention', 'cia', 'coup', 'corporatism'], ARRAY['Multiple'], 1898, 2024, true, true);

-- Insert Featured Collections

INSERT INTO featured_collections (id, title, slug, description, collection_type, focus_tags, featured, is_published) VALUES

('aa0e8400-e29b-41d4-a716-446655440001', 'Essential Revolutionary Texts', 'essential-revolutionary-texts', 'Curated selection of foundational texts for understanding revolution, socialism, communism, and liberation struggles, including Marx, Lenin, Mao, Fanon, Che, and other revolutionary theorists and leaders.', 'books', ARRAY['revolution', 'theory', 'communism', 'liberation'], true, true),

('aa0e8400-e29b-41d4-a716-446655440002', 'Women in Resistance', 'women-in-resistance', 'Collection of women revolutionaries, labor leaders, liberation fighters, and feminist thinkers whose struggles and theories advanced human liberation, from Rosa Luxemburg to Angela Davis to contemporary women activists.', 'people', ARRAY['women', 'feminism', 'resistance', 'liberation'], true, true),

('aa0e8400-e29b-41d4-a716-446655440003', 'Anti-Colonial Films and Documentaries', 'anti_colonial_media', 'Curated collection of films and documentaries depicting anti-colonial struggles, independence movements, occupation, and resistance, including both fiction films and documentary works.', 'mixed', ARRAY['anti_colonial', 'independence', 'resistance', 'occupation'], true, true),

('aa0e8400-e29b-41d4-a716-446655440004', 'Labor Movement Classics', 'labor-movement-classics', 'Essential films, documentaries, and written accounts of labor struggles including famous strikes, union organizing campaigns, and working-class movements that changed history.', 'mixed', ARRAY['labor', 'strikes', 'working_class', 'unions'], true, true),

('aa0e8400-e29b-41d4-a716-446655440005', 'Indigenous Liberation and Sovereignty', 'indigenous-liberation', 'Collection of indigenous leaders, thinkers, and movements struggling for sovereignty, land rights, and liberation from colonialism and capitalism.', 'people', ARRAY['indigenous', 'colonialism', 'sovereignty', 'land_rights'], false, true),

('aa0e8400-e29b-41d4-a716-446655440006', 'Socialist Economics and Alternatives', 'socialist-economics', 'Theoretical and practical works exploring socialism, planned economies, market socialism, participatory economics, and alternatives to capitalism.', 'books', ARRAY['socialism', 'economics', 'planning', 'alternatives'], false, true),

('aa0e8400-e29b-41d4-a716-446655440007', 'Guerrilla Warfare and Armed Struggle', 'guerrilla-warfare', 'Works analyzing and documenting guerrilla warfare, people''s war, armed struggle theory, and practice from Vietnam to Nicaragua to contemporary resistance.', 'books', ARRAY['guerrilla', 'armed_struggle', 'resistance', 'revolution'], false, true),

('aa0e8400-e29b-41d4-a716-446655440008', 'US Foreign Policy and Imperialism', 'us-foreign-policy', 'Critical analyses of US imperialism, military interventions, CIA operations, support for dictatorships, and US corporate exploitation globally.', 'books', ARRAY['imperialism', 'us_foreign_policy', 'military', 'interventions'], true, true),

('aa0e8400-e29b-41d4-a716-446655440009', 'Decolonial Theory and Practice', 'decolonial-theory', 'Contemporary decolonial scholarship challenging Western epistemology, examining coloniality of knowledge and power, and developing decolonial alternatives.', 'books', ARRAY['decolonial', 'theory', 'epistemology', 'colonialism'], false, true),

('aa0e8400-e29b-41d4-a716-446655440010', 'Palestinian Liberation and Resistance', 'palestine-resistance', 'Collection of Palestinian leaders, intellectuals, and resistance movements, including writings by Fanon on Algerian decolonization relevant to Palestine, films, and analyses of Palestinian struggle.', 'mixed', ARRAY['palestine', 'liberation', 'occupation', 'resistance'], true, true);

-- Verify inserts
SELECT COUNT(*) as pathway_count FROM research_pathways;
SELECT COUNT(*) as collection_count FROM featured_collections;
