"""Add politics people and events tables

Revision ID: 5a8a5d8270d0
Revises: addb0232adb3
Create Date: 2026-01-28 00:28:19.701763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5a8a5d8270d0'
down_revision: Union[str, None] = 'addb0232adb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conflicts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ucdp_id', sa.String(length=50), nullable=True),
    sa.Column('cow_id', sa.String(length=50), nullable=True),
    sa.Column('wikidata_id', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('conflict_type', sa.String(length=50), nullable=False),
    sa.Column('intensity', sa.String(length=20), nullable=True),
    sa.Column('casualties_low', sa.Integer(), nullable=True),
    sa.Column('casualties_high', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('progressive_analysis', sa.Text(), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conflicts_cow_id'), 'conflicts', ['cow_id'], unique=False)
    op.create_index(op.f('ix_conflicts_ucdp_id'), 'conflicts', ['ucdp_id'], unique=False)
    op.create_index(op.f('ix_conflicts_wikidata_id'), 'conflicts', ['wikidata_id'], unique=False)
    op.create_table('ideologies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('left_right_position', sa.Float(), nullable=True),
    sa.Column('libertarian_authoritarian_position', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('books',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('wikidata_id', sa.String(length=20), nullable=True),
    sa.Column('isbn', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('title_original', sa.String(length=500), nullable=True),
    sa.Column('publication_year', sa.Integer(), nullable=True),
    sa.Column('publisher', sa.String(length=255), nullable=True),
    sa.Column('book_type', sa.String(length=50), nullable=True),
    sa.Column('topics', postgresql.ARRAY(sa.String(length=100)), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('significance', sa.Text(), nullable=True),
    sa.Column('progressive_analysis', sa.Text(), nullable=True),
    sa.Column('marxists_archive_url', sa.String(length=500), nullable=True),
    sa.Column('gutenberg_url', sa.String(length=500), nullable=True),
    sa.Column('pdf_url', sa.String(length=500), nullable=True),
    sa.Column('cover_url', sa.String(length=500), nullable=True),
    sa.Column('country_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_books_wikidata_id'), 'books', ['wikidata_id'], unique=False)
    op.create_table('conflict_participants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conflict_id', sa.UUID(), nullable=False),
    sa.Column('country_id', sa.UUID(), nullable=True),
    sa.Column('actor_name', sa.String(length=255), nullable=True),
    sa.Column('side', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('casualties', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['conflict_id'], ['conflicts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('elections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('country_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('election_type', sa.String(length=50), nullable=False),
    sa.Column('turnout_percent', sa.Float(), nullable=True),
    sa.Column('total_votes', sa.Integer(), nullable=True),
    sa.Column('total_seats', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('parlgov_id', sa.Integer(), nullable=True),
    sa.Column('wikidata_id', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_id', 'date', 'election_type', name='uq_election_country_date_type')
    )
    op.create_index(op.f('ix_elections_parlgov_id'), 'elections', ['parlgov_id'], unique=False)
    op.create_index(op.f('ix_elections_wikidata_id'), 'elections', ['wikidata_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('wikidata_id', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('title_native', sa.String(length=500), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('date_precision', sa.String(length=10), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String(length=50)), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('progressive_analysis', sa.Text(), nullable=True),
    sa.Column('importance', sa.Integer(), nullable=True),
    sa.Column('location_name', sa.String(length=255), nullable=True),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('primary_country_id', sa.UUID(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['primary_country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_wikidata_id'), 'events', ['wikidata_id'], unique=False)
    op.create_table('people',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('wikidata_id', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_native', sa.String(length=255), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('birth_date_precision', sa.String(length=10), nullable=True),
    sa.Column('death_date', sa.Date(), nullable=True),
    sa.Column('death_date_precision', sa.String(length=10), nullable=True),
    sa.Column('person_types', postgresql.ARRAY(sa.String(length=50)), nullable=True),
    sa.Column('ideology_tags', postgresql.ARRAY(sa.String(length=50)), nullable=True),
    sa.Column('bio_short', sa.String(length=500), nullable=True),
    sa.Column('bio_full', sa.Text(), nullable=True),
    sa.Column('progressive_analysis', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('birth_place', sa.String(length=255), nullable=True),
    sa.Column('death_place', sa.String(length=255), nullable=True),
    sa.Column('primary_country_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['primary_country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_people_wikidata_id'), 'people', ['wikidata_id'], unique=True)
    op.create_table('political_parties',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parlgov_id', sa.Integer(), nullable=True),
    sa.Column('partyfacts_id', sa.Integer(), nullable=True),
    sa.Column('manifesto_id', sa.String(length=50), nullable=True),
    sa.Column('wikidata_id', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_english', sa.String(length=255), nullable=True),
    sa.Column('name_short', sa.String(length=50), nullable=True),
    sa.Column('country_id', sa.UUID(), nullable=False),
    sa.Column('founded', sa.Date(), nullable=True),
    sa.Column('dissolved', sa.Date(), nullable=True),
    sa.Column('left_right_score', sa.Float(), nullable=True),
    sa.Column('party_family', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('progressive_analysis', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_political_parties_manifesto_id'), 'political_parties', ['manifesto_id'], unique=False)
    op.create_index(op.f('ix_political_parties_parlgov_id'), 'political_parties', ['parlgov_id'], unique=False)
    op.create_index(op.f('ix_political_parties_partyfacts_id'), 'political_parties', ['partyfacts_id'], unique=False)
    op.create_index(op.f('ix_political_parties_wikidata_id'), 'political_parties', ['wikidata_id'], unique=False)
    op.create_table('book_authors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('book_id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('election_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('election_id', sa.UUID(), nullable=False),
    sa.Column('party_id', sa.UUID(), nullable=False),
    sa.Column('votes', sa.Integer(), nullable=True),
    sa.Column('vote_share', sa.Float(), nullable=True),
    sa.Column('seats', sa.Integer(), nullable=True),
    sa.Column('seat_share', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['party_id'], ['political_parties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('election_id', 'party_id', name='uq_election_result_party')
    )
    op.create_table('event_country_association',
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('country_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE')
    )
    op.create_table('event_person_association',
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('person_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='CASCADE')
    )
    op.create_table('party_ideology_association',
    sa.Column('party_id', sa.UUID(), nullable=True),
    sa.Column('ideology_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['ideology_id'], ['ideologies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['party_id'], ['political_parties.id'], ondelete='CASCADE')
    )
    op.create_table('party_memberships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('party_id', sa.UUID(), nullable=False),
    sa.Column('joined', sa.Date(), nullable=True),
    sa.Column('left', sa.Date(), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['party_id'], ['political_parties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('person_connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('person_from_id', sa.UUID(), nullable=False),
    sa.Column('person_to_id', sa.UUID(), nullable=False),
    sa.Column('connection_type', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('strength', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['person_from_id'], ['people.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_to_id'], ['people.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('person_country_association',
    sa.Column('person_id', sa.UUID(), nullable=True),
    sa.Column('country_id', sa.UUID(), nullable=True),
    sa.Column('relationship_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='CASCADE')
    )
    op.create_table('person_positions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('country_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('position_type', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    op.drop_table('person_positions')
    op.drop_table('person_country_association')
    op.drop_table('person_connections')
    op.drop_table('party_memberships')
    op.drop_table('party_ideology_association')
    op.drop_table('event_person_association')
    op.drop_table('event_country_association')
    op.drop_table('election_results')
    op.drop_table('book_authors')
    op.drop_index(op.f('ix_political_parties_wikidata_id'), table_name='political_parties')
    op.drop_index(op.f('ix_political_parties_partyfacts_id'), table_name='political_parties')
    op.drop_index(op.f('ix_political_parties_parlgov_id'), table_name='political_parties')
    op.drop_index(op.f('ix_political_parties_manifesto_id'), table_name='political_parties')
    op.drop_table('political_parties')
    op.drop_index(op.f('ix_people_wikidata_id'), table_name='people')
    op.drop_table('people')
    op.drop_index(op.f('ix_events_wikidata_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_elections_wikidata_id'), table_name='elections')
    op.drop_index(op.f('ix_elections_parlgov_id'), table_name='elections')
    op.drop_table('elections')
    op.drop_table('conflict_participants')
    op.drop_index(op.f('ix_books_wikidata_id'), table_name='books')
    op.drop_table('books')
    op.drop_table('ideologies')
    op.drop_index(op.f('ix_conflicts_wikidata_id'), table_name='conflicts')
    op.drop_index(op.f('ix_conflicts_ucdp_id'), table_name='conflicts')
    op.drop_index(op.f('ix_conflicts_cow_id'), table_name='conflicts')
    op.drop_table('conflicts')
    # ### end Alembic commands ###
