# Additional diverse leftist historical data - focusing on underrepresented regions

ADDITIONAL_EVENTS = [
    # Asian Labor and Revolutionary Movements
    {"title": "Chinese Communist Party Founded", "date": "1921-07-23", "category": "political",
     "description": "CCP founded in Shanghai with 13 delegates including Mao Zedong.",
     "tags": ["communism", "China", "party founding"]},
    {"title": "Long March Begins", "date": "1934-10-16", "category": "military",
     "description": "Red Army's 6,000 mile retreat from Nationalist forces. Cemented Mao's leadership.",
     "tags": ["civil war", "China", "Mao"]},
    {"title": "Korean Workers' Party Founded", "date": "1945-10-10", "category": "political",
     "description": "Founding of the ruling party of North Korea under Soviet occupation.",
     "tags": ["communism", "Korea", "party founding"]},
    {"title": "Japanese Communist Party Legalized", "date": "1945-10-10", "category": "political",
     "description": "JCP legalized after WWII. Became major force in postwar Japanese politics.",
     "tags": ["communism", "Japan", "party founding"]},
    {"title": "Communist Party of India Founded", "date": "1925-12-26", "category": "political",
     "description": "CPI founded in Kanpur. One of oldest communist parties in Asia.",
     "tags": ["communism", "India", "party founding"]},
    {"title": "Naxalbari Uprising", "date": "1967-05-25", "category": "political",
     "description": "Peasant uprising in West Bengal. Birth of Naxalite movement.",
     "tags": ["Maoism", "India", "peasant revolt"]},
    {"title": "Bhopal Disaster", "date": "1984-12-02", "category": "social",
     "description": "Union Carbide gas leak killed thousands. Symbol of corporate negligence.",
     "tags": ["industrial disaster", "India", "corporate crime"]},
    {"title": "Gwangju Uprising", "date": "1980-05-18", "category": "political",
     "description": "Pro-democracy uprising brutally suppressed by South Korean military.",
     "tags": ["democracy", "South Korea", "uprising"]},
    {"title": "People Power Revolution", "date": "1986-02-22", "category": "political",
     "description": "Nonviolent revolution ousted Ferdinand Marcos in Philippines.",
     "tags": ["revolution", "Philippines", "nonviolent"]},
    {"title": "Tiananmen Square Protests", "date": "1989-04-15", "category": "political",
     "description": "Student-led pro-democracy protests in Beijing. Violently suppressed June 4.",
     "tags": ["democracy", "China", "student movement"]},

    # African Liberation Movements
    {"title": "Pan-African Congress Founded", "date": "1959-04-06", "category": "political",
     "description": "PAC founded in South Africa as alternative to ANC with Africanist ideology.",
     "tags": ["anti-apartheid", "South Africa", "Pan-Africanism"]},
    {"title": "Sharpeville Massacre", "date": "1960-03-21", "category": "political",
     "description": "Police killed 69 protesters against pass laws. Turning point in anti-apartheid struggle.",
     "tags": ["anti-apartheid", "South Africa", "massacre"]},
    {"title": "Guinea-Bissau Independence", "date": "1973-09-24", "category": "political",
     "description": "Independence declared after PAIGC war against Portugal. Amilcar Cabral's legacy.",
     "tags": ["independence", "anti-colonial", "Guinea-Bissau", "PAIGC"]},
    {"title": "Ethiopian Revolution", "date": "1974-09-12", "category": "political",
     "description": "Derg military junta overthrew Emperor Haile Selassie. Established socialist state.",
     "tags": ["revolution", "Ethiopia", "socialism"]},
    {"title": "Burkina Faso Revolution", "date": "1983-08-04", "category": "political",
     "description": "Thomas Sankara took power. Implemented radical reforms until assassination in 1987.",
     "tags": ["revolution", "Burkina Faso", "Sankara"]},
    {"title": "End of Apartheid", "date": "1994-04-27", "category": "political",
     "description": "First democratic elections in South Africa. Nelson Mandela elected president.",
     "tags": ["anti-apartheid", "South Africa", "democracy"]},

    # Latin American Movements
    {"title": "Cuban Revolution Victory", "date": "1959-01-01", "category": "political",
     "description": "Fidel Castro's forces entered Havana. Batista fled.",
     "tags": ["revolution", "Cuba", "Castro"]},
    {"title": "Bay of Pigs Invasion", "date": "1961-04-17", "category": "military",
     "description": "Failed CIA-backed invasion of Cuba. Major US foreign policy failure.",
     "tags": ["Cuba", "imperialism", "CIA"]},
    {"title": "Tlatelolco Massacre", "date": "1968-10-02", "category": "political",
     "description": "Mexican government killed hundreds of student protesters before Olympics.",
     "tags": ["massacre", "Mexico", "student movement"]},
    {"title": "Allende Elected in Chile", "date": "1970-09-04", "category": "political",
     "description": "Salvador Allende became first democratically elected Marxist president.",
     "tags": ["election", "Chile", "socialism", "Allende"]},
    {"title": "Chilean Coup", "date": "1973-09-11", "category": "political",
     "description": "Military coup overthrew Allende. Pinochet dictatorship began. CIA involvement.",
     "tags": ["coup", "Chile", "Pinochet", "imperialism"]},
    {"title": "Sandinista Revolution Victory", "date": "1979-07-19", "category": "political",
     "description": "FSLN overthrew Somoza dictatorship in Nicaragua.",
     "tags": ["revolution", "Nicaragua", "Sandinistas"]},
    {"title": "Salvadoran Civil War Begins", "date": "1979-10-15", "category": "military",
     "description": "Twelve-year civil war between government and FMLN guerrillas.",
     "tags": ["civil war", "El Salvador", "FMLN"]},
    {"title": "Caracazo", "date": "1989-02-27", "category": "social",
     "description": "Mass protests against neoliberal policies in Venezuela. Hundreds killed.",
     "tags": ["protests", "Venezuela", "neoliberalism"]},
    {"title": "Hugo Chavez Elected", "date": "1998-12-06", "category": "political",
     "description": "Hugo Chavez won Venezuelan presidency. Beginning of Bolivarian Revolution.",
     "tags": ["election", "Venezuela", "Chavez", "Bolivarian"]},
    {"title": "Evo Morales Elected", "date": "2005-12-18", "category": "political",
     "description": "First indigenous president of Bolivia. MAS party victory.",
     "tags": ["election", "Bolivia", "indigenous", "Morales"]},

    # Middle Eastern Movements
    {"title": "Iranian Oil Nationalization", "date": "1951-03-15", "category": "economic",
     "description": "Mossadegh nationalized British-controlled oil. Led to 1953 CIA coup.",
     "tags": ["nationalization", "Iran", "oil", "Mossadegh"]},
    {"title": "Iraqi Revolution", "date": "1958-07-14", "category": "political",
     "description": "Military coup overthrew Hashemite monarchy. Republic established.",
     "tags": ["revolution", "Iraq", "Ba'ath"]},
    {"title": "PLO Founded", "date": "1964-05-28", "category": "political",
     "description": "Palestine Liberation Organization established at Arab League summit.",
     "tags": ["Palestine", "PLO", "liberation movement"]},
    {"title": "First Intifada", "date": "1987-12-08", "category": "political",
     "description": "Palestinian uprising against Israeli occupation of West Bank and Gaza.",
     "tags": ["Palestine", "intifada", "occupation"]},

    # European Movements
    {"title": "May 1968 France", "date": "1968-05-03", "category": "social",
     "description": "Student protests and general strike nearly toppled de Gaulle government.",
     "tags": ["protests", "France", "student movement", "general strike"]},
    {"title": "Hot Autumn Italy", "date": "1969-09-01", "category": "social",
     "description": "Wave of strikes and social upheaval in Italy. Workers and students united.",
     "tags": ["strikes", "Italy", "autonomia"]},
    {"title": "Greek Polytechnic Uprising", "date": "1973-11-14", "category": "political",
     "description": "Student uprising against military junta. Tank crushed protest.",
     "tags": ["uprising", "Greece", "anti-dictatorship"]},
    {"title": "Fall of Berlin Wall", "date": "1989-11-09", "category": "political",
     "description": "Berlin Wall opened. Symbol of Cold War division fell.",
     "tags": ["Germany", "Cold War", "reunification"]},
    {"title": "Yugoslav Wars Begin", "date": "1991-06-25", "category": "military",
     "description": "Slovenia and Croatia declared independence. Decade of wars followed.",
     "tags": ["war", "Yugoslavia", "nationalism"]},
    {"title": "Indignados Movement", "date": "2011-05-15", "category": "social",
     "description": "Anti-austerity protests across Spain. Occupied plazas demanding real democracy.",
     "tags": ["protests", "Spain", "austerity", "15-M"]},
    {"title": "Greek General Strike", "date": "2012-02-12", "category": "social",
     "description": "48-hour general strike against austerity. Widespread riots in Athens.",
     "tags": ["general strike", "Greece", "austerity"]},
]

ADDITIONAL_PEOPLE = [
    # Asian Revolutionary Leaders
    {"name": "Ho Chi Minh", "birth_date": "1890-05-19", "death_date": "1969-09-02",
     "person_types": ["revolutionary", "politician"], "ideology_tags": ["communist", "nationalist"],
     "bio_short": "Vietnamese revolutionary leader. Led independence struggle against France and US."},
    {"name": "Zhou Enlai", "birth_date": "1898-03-05", "death_date": "1976-01-08",
     "person_types": ["politician", "diplomat"], "ideology_tags": ["communist"],
     "bio_short": "First Premier of PRC. Key diplomat and moderate voice in Chinese leadership."},
    {"name": "Kim Il-sung", "birth_date": "1912-04-15", "death_date": "1994-07-08",
     "person_types": ["revolutionary", "politician"], "ideology_tags": ["communist", "Juche"],
     "bio_short": "Founder of North Korea. Developed Juche ideology."},
    {"name": "Subhas Chandra Bose", "birth_date": "1897-01-23", "death_date": "1945-08-18",
     "person_types": ["revolutionary", "nationalist"], "ideology_tags": ["socialist", "nationalist"],
     "bio_short": "Indian independence leader. Led Indian National Army against British."},
    {"name": "B.R. Ambedkar", "birth_date": "1891-04-14", "death_date": "1956-12-06",
     "person_types": ["politician", "intellectual"], "ideology_tags": ["anti-caste", "Buddhist socialist"],
     "bio_short": "Architect of Indian Constitution. Champion of Dalit rights."},
    {"name": "Sen Katayama", "birth_date": "1859-12-03", "death_date": "1933-11-05",
     "person_types": ["labor organizer", "revolutionary"], "ideology_tags": ["communist", "socialist"],
     "bio_short": "Japanese-American communist. Co-founder of Japanese Communist Party."},

    # African Liberation Leaders
    {"name": "Amilcar Cabral", "birth_date": "1924-09-12", "death_date": "1973-01-20",
     "person_types": ["revolutionary", "theorist"], "ideology_tags": ["Marxist", "Pan-Africanist"],
     "bio_short": "Led Guinea-Bissau independence. Major African revolutionary theorist."},
    {"name": "Thomas Sankara", "birth_date": "1949-12-21", "death_date": "1987-10-15",
     "person_types": ["revolutionary", "politician"], "ideology_tags": ["Marxist", "Pan-Africanist"],
     "bio_short": "Revolutionary leader of Burkina Faso. 'Africa's Che Guevara'."},
    {"name": "Samora Machel", "birth_date": "1933-09-29", "death_date": "1986-10-19",
     "person_types": ["revolutionary", "politician"], "ideology_tags": ["Marxist"],
     "bio_short": "First president of Mozambique. FRELIMO leader."},
    {"name": "Steve Biko", "birth_date": "1946-12-18", "death_date": "1977-09-12",
     "person_types": ["activist", "intellectual"], "ideology_tags": ["Black Consciousness"],
     "bio_short": "South African anti-apartheid activist. Founder of Black Consciousness Movement. Killed in detention."},
    {"name": "Chris Hani", "birth_date": "1942-06-28", "death_date": "1993-04-10",
     "person_types": ["revolutionary", "politician"], "ideology_tags": ["communist"],
     "bio_short": "Leader of South African Communist Party and MK. Assassinated."},
    {"name": "Winnie Mandela", "birth_date": "1936-09-26", "death_date": "2018-04-02",
     "person_types": ["activist", "politician"], "ideology_tags": ["socialist", "Pan-Africanist"],
     "bio_short": "South African anti-apartheid revolutionary. 'Mother of the Nation'."},

    # Latin American Figures
    {"name": "Salvador Allende", "birth_date": "1908-06-26", "death_date": "1973-09-11",
     "person_types": ["politician"], "ideology_tags": ["socialist", "Marxist"],
     "bio_short": "First democratically elected Marxist president. Died during Pinochet coup."},
    {"name": "Victor Jara", "birth_date": "1932-09-28", "death_date": "1973-09-16",
     "person_types": ["musician", "activist"], "ideology_tags": ["communist"],
     "bio_short": "Chilean folk singer and activist. Tortured and killed by Pinochet regime."},
    {"name": "Camilo Torres", "birth_date": "1929-02-03", "death_date": "1966-02-15",
     "person_types": ["priest", "revolutionary"], "ideology_tags": ["liberation theology"],
     "bio_short": "Colombian priest who joined ELN guerrillas. Symbol of liberation theology."},
    {"name": "Subcomandante Marcos", "birth_date": "1957-06-19", "death_date": None,
     "person_types": ["revolutionary", "writer"], "ideology_tags": ["Zapatista", "libertarian socialist"],
     "bio_short": "Spokesman of EZLN Zapatista movement in Chiapas, Mexico."},
    {"name": "Hugo Chavez", "birth_date": "1954-07-28", "death_date": "2013-03-05",
     "person_types": ["politician", "military"], "ideology_tags": ["Bolivarian", "socialist"],
     "bio_short": "Venezuelan president 1999-2013. Led Bolivarian Revolution."},
    {"name": "Evo Morales", "birth_date": "1959-10-26", "death_date": None,
     "person_types": ["politician", "union leader"], "ideology_tags": ["socialist", "indigenous rights"],
     "bio_short": "First indigenous president of Bolivia. Coca farmers union leader."},

    # European Figures
    {"name": "Antonio Gramsci", "birth_date": "1891-01-22", "death_date": "1937-04-27",
     "person_types": ["intellectual", "politician"], "ideology_tags": ["communist", "Marxist"],
     "bio_short": "Italian Marxist theorist. Developed concepts of hegemony and organic intellectuals."},
    {"name": "Palmiro Togliatti", "birth_date": "1893-03-26", "death_date": "1964-08-21",
     "person_types": ["politician"], "ideology_tags": ["communist", "Eurocommunist"],
     "bio_short": "Leader of Italian Communist Party. Key figure in Western European communism."},
    {"name": "Dolores Ibarruri", "birth_date": "1895-12-09", "death_date": "1989-11-12",
     "person_types": ["politician", "orator"], "ideology_tags": ["communist"],
     "bio_short": "Spanish communist leader. Known as 'La Pasionaria'. Famous for 'No Pasaran!' slogan."},
    {"name": "Rudi Dutschke", "birth_date": "1940-03-07", "death_date": "1979-12-24",
     "person_types": ["activist", "intellectual"], "ideology_tags": ["New Left", "socialist"],
     "bio_short": "German student activist leader. Spokesman for 1968 movement."},
    {"name": "Daniel Cohn-Bendit", "birth_date": "1945-04-04", "death_date": None,
     "person_types": ["activist", "politician"], "ideology_tags": ["anarchist", "Green"],
     "bio_short": "Leader of May 1968 protests in France. 'Danny the Red'."},
    {"name": "Ulrike Meinhof", "birth_date": "1934-10-07", "death_date": "1976-05-09",
     "person_types": ["journalist", "militant"], "ideology_tags": ["communist", "RAF"],
     "bio_short": "German journalist turned militant. Co-founder of Red Army Faction."},

    # Middle Eastern Figures
    {"name": "Mohammad Mosaddegh", "birth_date": "1882-06-16", "death_date": "1967-03-05",
     "person_types": ["politician"], "ideology_tags": ["nationalist", "social democrat"],
     "bio_short": "Iranian PM who nationalized oil. Overthrown in 1953 CIA coup."},
    {"name": "Gamal Abdel Nasser", "birth_date": "1918-01-15", "death_date": "1970-09-28",
     "person_types": ["politician", "military"], "ideology_tags": ["Arab nationalist", "socialist"],
     "bio_short": "Egyptian president. Leader of Arab nationalism and Pan-Arabism."},
    {"name": "George Habash", "birth_date": "1926-08-02", "death_date": "2008-01-26",
     "person_types": ["revolutionary", "politician"], "ideology_tags": ["Marxist", "Palestinian nationalist"],
     "bio_short": "Founder of PFLP. Palestinian Marxist revolutionary."},
    {"name": "Leila Khaled", "birth_date": "1944-04-09", "death_date": None,
     "person_types": ["revolutionary"], "ideology_tags": ["Marxist", "Palestinian nationalist"],
     "bio_short": "PFLP member. First woman to hijack an airplane."},
]

ADDITIONAL_BOOKS = [
    # Revolutionary Theory
    {"title": "The Wretched of the Earth", "author": "Frantz Fanon", "publication_year": 1961,
     "book_type": "political_theory",
     "description": "Analysis of decolonization and psychology of the colonized. Preface by Sartre.",
     "topics": ["colonialism", "violence", "decolonization"]},
    {"title": "Pedagogy of the Oppressed", "author": "Paulo Freire", "publication_year": 1968,
     "book_type": "philosophy",
     "description": "Revolutionary education theory. Critique of 'banking' model of education.",
     "topics": ["education", "liberation", "praxis"]},
    {"title": "Prison Notebooks", "author": "Antonio Gramsci", "publication_year": 1947,
     "book_type": "political_theory",
     "description": "Marxist theory developed in fascist prison. Hegemony, civil society, organic intellectuals.",
     "topics": ["hegemony", "Marxism", "culture"]},
    {"title": "Open Veins of Latin America", "author": "Eduardo Galeano", "publication_year": 1971,
     "book_type": "history",
     "description": "History of Latin American exploitation by colonial and imperial powers.",
     "topics": ["imperialism", "Latin America", "exploitation"]},
    {"title": "Guerrilla Warfare", "author": "Che Guevara", "publication_year": 1961,
     "book_type": "political_theory",
     "description": "Manual on guerrilla tactics based on Cuban Revolution experience.",
     "topics": ["guerrilla warfare", "revolution", "tactics"]},
    {"title": "Revolution in the Revolution?", "author": "Regis Debray", "publication_year": 1967,
     "book_type": "political_theory",
     "description": "Theory of revolutionary foco. Influenced Latin American guerrilla movements.",
     "topics": ["revolution", "foco theory", "Latin America"]},

    # Pan-African and Anti-Colonial
    {"title": "Return to the Source", "author": "Amilcar Cabral", "publication_year": 1973,
     "book_type": "political_theory",
     "description": "Selected speeches on African liberation and national culture.",
     "topics": ["liberation", "culture", "Africa"]},
    {"title": "I Write What I Like", "author": "Steve Biko", "publication_year": 1978,
     "book_type": "political_theory",
     "description": "Collection of writings on Black Consciousness movement.",
     "topics": ["Black Consciousness", "apartheid", "South Africa"]},
    {"title": "Discourse on Colonialism", "author": "Aime Cesaire", "publication_year": 1950,
     "book_type": "political_theory",
     "description": "Critique of European colonialism. Key text of negritude movement.",
     "topics": ["colonialism", "negritude", "Europe"]},
    {"title": "Black Skin, White Masks", "author": "Frantz Fanon", "publication_year": 1952,
     "book_type": "philosophy",
     "description": "Psychological analysis of racism and colonialism's effects on Black psyche.",
     "topics": ["racism", "colonialism", "psychology"]},
    {"title": "Neocolonialism: The Last Stage of Imperialism", "author": "Kwame Nkrumah", "publication_year": 1965,
     "book_type": "political_theory",
     "description": "Analysis of continued Western economic dominance after political independence.",
     "topics": ["neocolonialism", "imperialism", "Africa"]},

    # Feminist and Intersectional
    {"title": "Women, Race and Class", "author": "Angela Davis", "publication_year": 1981,
     "book_type": "history",
     "description": "Intersectional analysis of women's liberation, civil rights, and labor movements.",
     "topics": ["feminism", "race", "class"]},
    {"title": "Sister Outsider", "author": "Audre Lorde", "publication_year": 1984,
     "book_type": "essays",
     "description": "Essays and speeches on identity, difference, and radical politics.",
     "topics": ["feminism", "intersectionality", "identity"]},
    {"title": "The Combahee River Collective Statement", "author": "Combahee River Collective", "publication_year": 1977,
     "book_type": "manifesto",
     "description": "Foundational Black feminist statement. Coined 'identity politics'.",
     "topics": ["Black feminism", "identity politics", "intersectionality"]},
    {"title": "Caliban and the Witch", "author": "Silvia Federici", "publication_year": 2004,
     "book_type": "history",
     "description": "Feminist analysis of witch hunts and primitive accumulation.",
     "topics": ["feminism", "capitalism", "history"]},

    # Contemporary Theory
    {"title": "Capitalist Realism", "author": "Mark Fisher", "publication_year": 2009,
     "book_type": "political_theory",
     "description": "Analysis of neoliberal ideology. 'Easier to imagine end of world than end of capitalism.'",
     "topics": ["neoliberalism", "ideology", "cultural theory"]},
    {"title": "The New Jim Crow", "author": "Michelle Alexander", "publication_year": 2010,
     "book_type": "history",
     "description": "Mass incarceration as new racial control system in United States.",
     "topics": ["mass incarceration", "racism", "criminal justice"]},
    {"title": "Debt: The First 5000 Years", "author": "David Graeber", "publication_year": 2011,
     "book_type": "history",
     "description": "Anthropological history of debt. Challenges economic assumptions.",
     "topics": ["debt", "anthropology", "economics"]},
]
