# More curated leftist historical data

MORE_EVENTS = [
    # Labor History
    {"title": "Haymarket Affair", "date": "1886-05-04", "category": "social", 
     "description": "Labor protest in Chicago for eight-hour workday turned violent. Led to May Day becoming International Workers Day.",
     "tags": ["labor", "anarchism", "May Day", "USA"]},
    {"title": "Triangle Shirtwaist Factory Fire", "date": "1911-03-25", "category": "social",
     "description": "Deadliest industrial disaster in NYC history. 146 garment workers died. Led to labor law reforms.",
     "tags": ["labor", "workers rights", "safety", "USA"]},
    {"title": "Ludlow Massacre", "date": "1914-04-20", "category": "social",
     "description": "Colorado National Guard attacked striking coal miners. 21 killed including women and children.",
     "tags": ["labor", "strike", "massacre", "USA"]},
    {"title": "Seattle General Strike", "date": "1919-02-06", "category": "social",
     "description": "First general strike in American history. 65,000 workers shut down the city for five days.",
     "tags": ["general strike", "labor", "USA"]},
    {"title": "Winnipeg General Strike", "date": "1919-05-15", "category": "social",
     "description": "Six-week strike by 30,000 workers paralyzed Winnipeg. Major event in Canadian labor history.",
     "tags": ["general strike", "labor", "Canada"]},
    {"title": "Battle of Blair Mountain", "date": "1921-08-25", "category": "social",
     "description": "Largest labor uprising in US history. 10,000 armed miners fought against coal company enforcers.",
     "tags": ["labor", "mining", "armed conflict", "USA"]},
    {"title": "UK General Strike", "date": "1926-05-03", "category": "social",
     "description": "Nine-day general strike by 1.7 million workers in support of coal miners.",
     "tags": ["general strike", "labor", "UK"]},
    {"title": "Flint Sit-Down Strike", "date": "1936-12-30", "category": "social",
     "description": "44-day strike against General Motors. Workers occupied factories. Led to UAW recognition.",
     "tags": ["strike", "auto workers", "UAW", "USA"]},
    {"title": "Memphis Sanitation Strike", "date": "1968-02-12", "category": "social",
     "description": "Strike by 1,300 Black sanitation workers. MLK was assassinated while supporting it.",
     "tags": ["strike", "civil rights", "labor", "USA"]},
    {"title": "Delano Grape Strike", "date": "1965-09-08", "category": "social",
     "description": "Five-year strike by Filipino and Latino farmworkers. Led by Cesar Chavez and Dolores Huerta.",
     "tags": ["strike", "farmworkers", "UFW", "USA"]},
    
    # Revolutions and Uprisings
    {"title": "Haitian Revolution", "date": "1791-08-22", "category": "political",
     "description": "Successful slave revolt establishing Haiti as first free Black republic.",
     "tags": ["revolution", "slavery", "Haiti", "Caribbean"]},
    {"title": "Revolutions of 1848", "date": "1848-02-22", "category": "political",
     "description": "Wave of revolutions across Europe demanding democratic reforms. The 'Spring of Nations'.",
     "tags": ["revolution", "democracy", "Europe"]},
    {"title": "Hungarian Revolution of 1956", "date": "1956-10-23", "category": "political",
     "description": "Nationwide revolt against Soviet-imposed policies. Crushed by Soviet tanks.",
     "tags": ["revolution", "Hungary", "anti-Stalinist"]},
    {"title": "Prague Spring", "date": "1968-01-05", "category": "political",
     "description": "Period of political liberalization in Czechoslovakia. Ended by Warsaw Pact invasion.",
     "tags": ["reform", "Czechoslovakia", "socialism with human face"]},
    {"title": "Portuguese Carnation Revolution", "date": "1974-04-25", "category": "political",
     "description": "Military coup ending Estado Novo dictatorship. Led to decolonization and democracy.",
     "tags": ["revolution", "Portugal", "anti-fascist"]},
    {"title": "Iranian Revolution", "date": "1979-02-11", "category": "political",
     "description": "Overthrow of the Shah. Initially broad coalition including leftist forces.",
     "tags": ["revolution", "Iran"]},
    {"title": "Sandinista Revolution", "date": "1979-07-19", "category": "political",
     "description": "Nicaraguan revolution overthrowing Somoza dictatorship. Sandinistas took power.",
     "tags": ["revolution", "Nicaragua", "Sandinistas", "Latin America"]},
    {"title": "Solidarity Movement Founded", "date": "1980-09-17", "category": "political",
     "description": "First independent trade union in Soviet bloc. Led by Lech Walesa in Poland.",
     "tags": ["labor", "Poland", "Solidarity"]},
    {"title": "Zapatista Uprising", "date": "1994-01-01", "category": "political",
     "description": "Indigenous uprising in Chiapas, Mexico. Declared war on Mexican government on NAFTA implementation day.",
     "tags": ["uprising", "indigenous", "Mexico", "Zapatistas"]},
    {"title": "Arab Spring Begins", "date": "2010-12-17", "category": "political",
     "description": "Wave of protests across Arab world beginning in Tunisia after Mohamed Bouazizi self-immolation.",
     "tags": ["protests", "Arab Spring", "Tunisia", "Middle East"]},
    
    # Anti-Colonial Movements
    {"title": "Indian Independence", "date": "1947-08-15", "category": "political",
     "description": "End of British colonial rule in India after decades of struggle.",
     "tags": ["independence", "anti-colonial", "India"]},
    {"title": "Indonesian Independence", "date": "1945-08-17", "category": "political",
     "description": "Proclamation of independence from Dutch colonial rule.",
     "tags": ["independence", "anti-colonial", "Indonesia"]},
    {"title": "Algerian Independence", "date": "1962-07-05", "category": "political",
     "description": "End of French colonial rule after eight-year war of independence.",
     "tags": ["independence", "anti-colonial", "Algeria", "FLN"]},
    {"title": "Angolan Independence", "date": "1975-11-11", "category": "political",
     "description": "Independence from Portugal after 14-year war. MPLA took power.",
     "tags": ["independence", "anti-colonial", "Angola", "MPLA"]},
    {"title": "Mozambique Independence", "date": "1975-06-25", "category": "political",
     "description": "Independence from Portugal. FRELIMO established socialist government.",
     "tags": ["independence", "anti-colonial", "Mozambique", "FRELIMO"]},
    {"title": "Zimbabwe Independence", "date": "1980-04-18", "category": "political",
     "description": "End of white minority rule in Rhodesia. Robert Mugabe became leader.",
     "tags": ["independence", "anti-colonial", "Zimbabwe"]},
    
    # Civil Rights and Social Movements
    {"title": "March on Washington", "date": "1963-08-28", "category": "social",
     "description": "250,000 people marched for civil rights. MLK delivered 'I Have a Dream' speech.",
     "tags": ["civil rights", "USA", "MLK"]},
    {"title": "Stonewall Riots", "date": "1969-06-28", "category": "social",
     "description": "Six-day protests by LGBT community against police raid. Birth of modern LGBT rights movement.",
     "tags": ["LGBT", "civil rights", "USA"]},
    {"title": "Wounded Knee Occupation", "date": "1973-02-27", "category": "social",
     "description": "71-day occupation by American Indian Movement at Wounded Knee, South Dakota.",
     "tags": ["indigenous rights", "AIM", "USA"]},
    {"title": "Soweto Uprising", "date": "1976-06-16", "category": "social",
     "description": "Student protests against apartheid education in South Africa. Police killed hundreds.",
     "tags": ["anti-apartheid", "South Africa", "student movement"]},
    {"title": "Tiananmen Square Protests", "date": "1989-04-15", "category": "political",
     "description": "Student-led pro-democracy protests in Beijing. Violently suppressed by military.",
     "tags": ["democracy", "China", "student movement"]},
    {"title": "Battle of Seattle", "date": "1999-11-30", "category": "social",
     "description": "Mass protests against WTO meeting. Birth of anti-globalization movement.",
     "tags": ["anti-globalization", "WTO", "USA"]},
    {"title": "Occupy Wall Street", "date": "2011-09-17", "category": "social",
     "description": "Protest movement against economic inequality. 'We are the 99%' slogan.",
     "tags": ["occupy", "inequality", "USA"]},
    {"title": "Black Lives Matter Founded", "date": "2013-07-13", "category": "social",
     "description": "Movement founded after Trayvon Martin's killer acquitted. Grew after Ferguson.",
     "tags": ["BLM", "civil rights", "police brutality", "USA"]},
    
    # Economic Events
    {"title": "Great Depression Begins", "date": "1929-10-29", "category": "economic",
     "description": "Stock market crash triggered worldwide economic depression. Led to New Deal policies.",
     "tags": ["depression", "economic crisis", "USA"]},
    {"title": "Bretton Woods Conference", "date": "1944-07-01", "category": "economic",
     "description": "Established post-war international monetary system. Created IMF and World Bank.",
     "tags": ["economics", "international", "capitalism"]},
    {"title": "Chilean Economic Crisis", "date": "1973-09-11", "category": "economic",
     "description": "Pinochet coup ended Allende government. Neoliberal 'Chicago Boys' policies imposed.",
     "tags": ["coup", "neoliberalism", "Chile"]},
    {"title": "Global Financial Crisis", "date": "2008-09-15", "category": "economic",
     "description": "Lehman Brothers collapse triggered worldwide financial crisis and recession.",
     "tags": ["financial crisis", "banks", "capitalism"]},
]

MORE_PEOPLE = [
    # Labor Leaders
    {"name": "Eugene V. Debs", "birth_date": "1855-11-05", "death_date": "1926-10-20",
     "bio": "American socialist and labor leader. Five-time presidential candidate for Socialist Party. Imprisoned for opposing WWI.",
     "person_type": ["labor leader", "socialist"], "ideology_tags": ["socialism", "labor"]},
    {"name": "Mother Jones", "birth_date": "1837-08-01", "death_date": "1930-11-30",
     "bio": "Irish-American labor organizer. 'The most dangerous woman in America.' Fought for miners' rights.",
     "person_type": ["labor leader", "organizer"], "ideology_tags": ["labor", "socialism"]},
    {"name": "Big Bill Haywood", "birth_date": "1869-02-04", "death_date": "1928-05-18",
     "bio": "American labor leader. Co-founder of Industrial Workers of the World (IWW). Fled to Soviet Russia.",
     "person_type": ["labor leader", "revolutionary"], "ideology_tags": ["syndicalism", "IWW"]},
    {"name": "Joe Hill", "birth_date": "1879-10-07", "death_date": "1915-11-19",
     "bio": "Swedish-American labor activist and songwriter. IWW martyr executed on disputed murder charge.",
     "person_type": ["labor leader", "songwriter"], "ideology_tags": ["IWW", "syndicalism"]},
    {"name": "Cesar Chavez", "birth_date": "1927-03-31", "death_date": "1993-04-23",
     "bio": "American labor leader and civil rights activist. Co-founded United Farm Workers. Led grape boycott.",
     "person_type": ["labor leader", "civil rights"], "ideology_tags": ["labor", "nonviolence"]},
    {"name": "Dolores Huerta", "birth_date": "1930-04-10", "death_date": None,
     "bio": "American labor leader and civil rights activist. Co-founded UFW with Cesar Chavez. 'Si se puede!'",
     "person_type": ["labor leader", "civil rights"], "ideology_tags": ["labor", "feminism"]},
    
    # Revolutionary Women
    {"name": "Clara Zetkin", "birth_date": "1857-07-05", "death_date": "1933-06-20",
     "bio": "German Marxist theorist and activist. Founded International Womens Day. KPD leader.",
     "person_type": ["theorist", "feminist"], "ideology_tags": ["Marxism", "feminism"]},
    {"name": "Alexandra Kollontai", "birth_date": "1872-03-31", "death_date": "1952-03-09",
     "bio": "Russian revolutionary. First female government minister in history. Theorist of womens liberation.",
     "person_type": ["revolutionary", "diplomat"], "ideology_tags": ["Marxism", "feminism"]},
    {"name": "Nadezhda Krupskaya", "birth_date": "1869-02-26", "death_date": "1939-02-27",
     "bio": "Russian Bolshevik revolutionary and politician. Lenins wife. Education reformer.",
     "person_type": ["revolutionary", "educator"], "ideology_tags": ["Marxism-Leninism"]},
    {"name": "Inessa Armand", "birth_date": "1874-05-08", "death_date": "1920-09-24",
     "bio": "Russian communist revolutionary. Close associate of Lenin. Pioneer of Soviet womens movement.",
     "person_type": ["revolutionary"], "ideology_tags": ["Marxism", "feminism"]},
    {"name": "Assata Shakur", "birth_date": "1947-07-16", "death_date": None,
     "bio": "American activist and former Black Panther. Escaped prison and granted asylum in Cuba.",
     "person_type": ["revolutionary", "activist"], "ideology_tags": ["Black liberation", "socialism"]},
    {"name": "Angela Davis", "birth_date": "1944-01-26", "death_date": None,
     "bio": "American political activist, philosopher, and academic. Communist Party USA member. Prison abolitionist.",
     "person_type": ["activist", "academic"], "ideology_tags": ["communism", "feminism", "prison abolition"]},
    
    # Anti-Colonial Leaders
    {"name": "Frantz Fanon", "birth_date": "1925-07-20", "death_date": "1961-12-06",
     "bio": "Martinican psychiatrist and philosopher. Theorist of colonialism. The Wretched of the Earth.",
     "person_type": ["theorist", "revolutionary"], "ideology_tags": ["anti-colonialism", "Third World"]},
    {"name": "Aime Cesaire", "birth_date": "1913-06-26", "death_date": "2008-04-17",
     "bio": "Martinican poet and politician. Co-founder of Negritude movement. Discourse on Colonialism.",
     "person_type": ["poet", "politician"], "ideology_tags": ["anti-colonialism", "negritude"]},
    {"name": "Samora Machel", "birth_date": "1933-09-29", "death_date": "1986-10-19",
     "bio": "Mozambican revolutionary and first president. FRELIMO leader. Died in suspicious plane crash.",
     "person_type": ["revolutionary", "leader"], "ideology_tags": ["Marxism-Leninism", "anti-colonialism"]},
    {"name": "Agostinho Neto", "birth_date": "1922-09-17", "death_date": "1979-09-10",
     "bio": "Angolan physician, poet, and politician. MPLA founder and first president of Angola.",
     "person_type": ["revolutionary", "leader"], "ideology_tags": ["Marxism-Leninism", "anti-colonialism"]},
    {"name": "Cabral Amilcar", "birth_date": "1924-09-12", "death_date": "1973-01-20",
     "bio": "Guinea-Bissauan and Cape Verdean revolutionary. PAIGC founder. Assassinated before independence.",
     "person_type": ["revolutionary", "theorist"], "ideology_tags": ["anti-colonialism", "African socialism"]},
    {"name": "Walter Rodney", "birth_date": "1942-03-23", "death_date": "1980-06-13",
     "bio": "Guyanese historian and political activist. How Europe Underdeveloped Africa. Assassinated.",
     "person_type": ["historian", "activist"], "ideology_tags": ["Pan-Africanism", "Marxism"]},
    
    # Contemporary Leftists
    {"name": "Cornel West", "birth_date": "1953-06-02", "death_date": None,
     "bio": "American philosopher, political activist, and social critic. Democratic socialist.",
     "person_type": ["academic", "activist"], "ideology_tags": ["democratic socialism", "Christianity"]},
    {"name": "Naomi Klein", "birth_date": "1970-05-08", "death_date": None,
     "bio": "Canadian author and activist. No Logo, The Shock Doctrine, This Changes Everything.",
     "person_type": ["author", "activist"], "ideology_tags": ["anti-capitalism", "climate justice"]},
    {"name": "Slavoj Zizek", "birth_date": "1949-03-21", "death_date": None,
     "bio": "Slovenian philosopher and cultural critic. Combines Lacanian psychoanalysis with Marxism.",
     "person_type": ["philosopher"], "ideology_tags": ["Marxism", "Lacanian"]},
    {"name": "David Graeber", "birth_date": "1961-02-12", "death_date": "2020-09-02",
     "bio": "American anthropologist and anarchist activist. Debt: The First 5000 Years. Occupy organizer.",
     "person_type": ["anthropologist", "activist"], "ideology_tags": ["anarchism"]},
    {"name": "Yanis Varoufakis", "birth_date": "1961-03-24", "death_date": None,
     "bio": "Greek economist and politician. Former finance minister. DiEM25 co-founder.",
     "person_type": ["economist", "politician"], "ideology_tags": ["left-wing", "Euro-skeptic"]},
    {"name": "Jeremy Corbyn", "birth_date": "1949-05-26", "death_date": None,
     "bio": "British politician. Labour Party leader 2015-2020. Anti-war activist.",
     "person_type": ["politician"], "ideology_tags": ["democratic socialism", "anti-war"]},
    {"name": "Jean-Luc Melenchon", "birth_date": "1951-08-19", "death_date": None,
     "bio": "French politician. La France Insoumise founder. Presidential candidate.",
     "person_type": ["politician"], "ideology_tags": ["left-wing populism", "ecosocialism"]},
    {"name": "Pablo Iglesias", "birth_date": "1978-10-17", "death_date": None,
     "bio": "Spanish politician and political scientist. Podemos co-founder. Former deputy PM.",
     "person_type": ["politician", "academic"], "ideology_tags": ["left-wing populism"]},
]

MORE_BOOKS = [
    {"title": "The Wretched of the Earth", "author": "Frantz Fanon", "year": 1961,
     "topics": ["colonialism", "violence", "decolonization"],
     "significance": "Essential text on anti-colonial struggle and psychology of the oppressed."},
    {"title": "Pedagogy of the Oppressed", "author": "Paulo Freire", "year": 1968,
     "topics": ["education", "liberation", "critical pedagogy"],
     "significance": "Foundational work on critical pedagogy and education as liberation."},
    {"title": "Capitalist Realism", "author": "Mark Fisher", "year": 2009,
     "topics": ["capitalism", "culture", "mental health"],
     "significance": "Influential analysis of how capitalism colonizes imagination."},
    {"title": "A Peoples History of the United States", "author": "Howard Zinn", "year": 1980,
     "topics": ["history", "class struggle", "USA"],
     "significance": "History from perspective of workers, minorities, and the oppressed."},
    {"title": "The Shock Doctrine", "author": "Naomi Klein", "year": 2007,
     "topics": ["neoliberalism", "disaster capitalism", "economics"],
     "significance": "Exposes how crises are exploited to impose neoliberal policies."},
    {"title": "No Logo", "author": "Naomi Klein", "year": 1999,
     "topics": ["branding", "globalization", "sweatshops"],
     "significance": "Critique of corporate branding and globalization. Anti-globalization manifesto."},
    {"title": "Debt: The First 5000 Years", "author": "David Graeber", "year": 2011,
     "topics": ["debt", "economics", "anthropology"],
     "significance": "Anthropological history challenging myths about money and markets."},
    {"title": "The New Jim Crow", "author": "Michelle Alexander", "year": 2010,
     "topics": ["mass incarceration", "racism", "criminal justice"],
     "significance": "Exposes racial bias in criminal justice system as new form of control."},
    {"title": "Blackshirts and Reds", "author": "Michael Parenti", "year": 1997,
     "topics": ["fascism", "communism", "Cold War"],
     "significance": "Marxist analysis of fascism and defense of Soviet achievements."},
    {"title": "Open Veins of Latin America", "author": "Eduardo Galeano", "year": 1971,
     "topics": ["imperialism", "Latin America", "exploitation"],
     "significance": "Classic account of Latin American exploitation by colonial powers."},
    {"title": "Manufacturing Consent", "author": "Noam Chomsky", "year": 1988,
     "topics": ["media", "propaganda", "democracy"],
     "significance": "Analysis of how mass media serves elite interests."},
    {"title": "Caliban and the Witch", "author": "Silvia Federici", "year": 2004,
     "topics": ["feminism", "primitive accumulation", "witch hunts"],
     "significance": "Feminist Marxist analysis of witch hunts and origins of capitalism."},
    {"title": "The Dispossessed", "author": "Ursula K. Le Guin", "year": 1974,
     "topics": ["anarchism", "utopia", "science fiction"],
     "significance": "Anarchist utopian novel exploring revolutionary society."},
    {"title": "Mutual Aid", "author": "Peter Kropotkin", "year": 1902,
     "topics": ["evolution", "cooperation", "anarchism"],
     "significance": "Argues cooperation not competition drives evolution. Anarchist classic.",
     "marxists_url": "https://www.marxists.org/reference/archive/kropotkin-peter/1902/mutual-aid/"},
    {"title": "Reform or Revolution", "author": "Rosa Luxemburg", "year": 1900,
     "topics": ["reform", "revolution", "social democracy"],
     "significance": "Classic critique of reformism within socialist movement.",
     "marxists_url": "https://www.marxists.org/archive/luxemburg/1900/reform-revolution/"},
    {"title": "Imperialism: The Highest Stage of Capitalism", "author": "Vladimir Lenin", "year": 1917,
     "topics": ["imperialism", "monopoly capitalism", "colonialism"],
     "significance": "Lenins analysis of imperialism as late-stage capitalism.",
     "marxists_url": "https://www.marxists.org/archive/lenin/works/1916/imp-hsc/"},
]
