"""Large static dataset of leftist figures, events, and books."""

# Extended list of leftist figures
LEFTIST_FIGURES = [
    # Classic Marxist theorists
    {"wikidata_id": "Q9061", "name": "Karl Marx", "birth_date": "1818-05-05", "death_date": "1883-03-14", "birth_place": "Trier, Germany", "person_types": ["philosopher", "economist", "writer"], "ideology_tags": ["communist", "marxist"], "bio_short": "German philosopher and economist, author of Das Kapital and co-author of The Communist Manifesto."},
    {"wikidata_id": "Q9916", "name": "Friedrich Engels", "birth_date": "1820-11-28", "death_date": "1895-08-05", "birth_place": "Wuppertal, Germany", "person_types": ["philosopher", "writer"], "ideology_tags": ["communist", "marxist"], "bio_short": "German philosopher and Marx's closest collaborator."},
    {"wikidata_id": "Q10518", "name": "Vladimir Lenin", "birth_date": "1870-04-22", "death_date": "1924-01-21", "birth_place": "Ulyanovsk, Russia", "person_types": ["politician", "revolutionary", "writer"], "ideology_tags": ["communist", "marxist-leninist"], "bio_short": "Russian revolutionary, leader of the Bolshevik Revolution."},
    {"wikidata_id": "Q5816", "name": "Leon Trotsky", "birth_date": "1879-11-07", "death_date": "1940-08-21", "birth_place": "Bereslavka, Ukraine", "person_types": ["politician", "revolutionary", "writer"], "ideology_tags": ["communist", "trotskyist"], "bio_short": "Marxist revolutionary, founded the Red Army."},
    {"wikidata_id": "Q3621", "name": "Rosa Luxemburg", "birth_date": "1871-03-05", "death_date": "1919-01-15", "birth_place": "Zamosc, Poland", "person_types": ["politician", "revolutionary", "economist"], "ideology_tags": ["communist", "marxist"], "bio_short": "Polish-German Marxist theorist and revolutionary."},
    {"wikidata_id": "Q5593", "name": "Antonio Gramsci", "birth_date": "1891-01-22", "death_date": "1937-04-27", "birth_place": "Ales, Italy", "person_types": ["philosopher", "politician", "writer"], "ideology_tags": ["communist", "marxist"], "bio_short": "Italian Marxist philosopher, developed theory of cultural hegemony."},
    {"wikidata_id": "Q7743", "name": "Joseph Stalin", "birth_date": "1878-12-18", "death_date": "1953-03-05", "birth_place": "Gori, Georgia", "person_types": ["politician"], "ideology_tags": ["communist", "stalinist"], "bio_short": "Soviet leader from 1924 to 1953."},
    {"wikidata_id": "Q7378", "name": "Mao Zedong", "birth_date": "1893-12-26", "death_date": "1976-09-09", "birth_place": "Shaoshan, China", "person_types": ["politician", "revolutionary"], "ideology_tags": ["communist", "maoist"], "bio_short": "Chinese communist revolutionary, founder of the PRC."},
    
    # Anarchists
    {"wikidata_id": "Q36303", "name": "Mikhail Bakunin", "birth_date": "1814-05-30", "death_date": "1876-07-01", "birth_place": "Pryamukhino, Russia", "person_types": ["philosopher", "revolutionary"], "ideology_tags": ["anarchist", "collectivist"], "bio_short": "Russian revolutionary anarchist, founder of collectivist anarchism."},
    {"wikidata_id": "Q312817", "name": "Peter Kropotkin", "birth_date": "1842-12-09", "death_date": "1921-02-08", "birth_place": "Moscow, Russia", "person_types": ["philosopher", "scientist", "writer"], "ideology_tags": ["anarchist", "anarcho-communist"], "bio_short": "Russian anarcho-communist, author of Mutual Aid."},
    {"wikidata_id": "Q7281", "name": "Emma Goldman", "birth_date": "1869-06-27", "death_date": "1940-05-14", "birth_place": "Kaunas, Lithuania", "person_types": ["activist", "writer"], "ideology_tags": ["anarchist", "feminist"], "bio_short": "Lithuanian-American anarchist activist and writer."},
    {"wikidata_id": "Q313tried", "name": "Pierre-Joseph Proudhon", "birth_date": "1809-01-15", "death_date": "1865-01-19", "birth_place": "Besancon, France", "person_types": ["philosopher", "economist"], "ideology_tags": ["anarchist", "mutualist"], "bio_short": "French anarchist philosopher, first to call himself an anarchist."},
    {"wikidata_id": "Q334126", "name": "Errico Malatesta", "birth_date": "1853-12-14", "death_date": "1932-07-22", "birth_place": "Santa Maria Capua Vetere, Italy", "person_types": ["activist", "writer"], "ideology_tags": ["anarchist", "anarcho-communist"], "bio_short": "Italian anarchist and writer."},
    {"wikidata_id": "Q55436", "name": "Nestor Makhno", "birth_date": "1888-10-26", "death_date": "1934-07-25", "birth_place": "Huliaipole, Ukraine", "person_types": ["revolutionary", "military"], "ideology_tags": ["anarchist"], "bio_short": "Ukrainian anarchist revolutionary and military commander."},
    {"wikidata_id": "Q312669", "name": "Buenaventura Durruti", "birth_date": "1896-07-14", "death_date": "1936-11-20", "birth_place": "Leon, Spain", "person_types": ["revolutionary", "activist"], "ideology_tags": ["anarchist", "anarcho-syndicalist"], "bio_short": "Spanish anarchist revolutionary during the Spanish Civil War."},
    
    # Latin American revolutionaries
    {"wikidata_id": "Q5575", "name": "Che Guevara", "birth_date": "1928-06-14", "death_date": "1967-10-09", "birth_place": "Rosario, Argentina", "person_types": ["revolutionary", "physician"], "ideology_tags": ["communist", "marxist"], "bio_short": "Argentine Marxist revolutionary, key figure in Cuban Revolution."},
    {"wikidata_id": "Q5752", "name": "Fidel Castro", "birth_date": "1926-08-13", "death_date": "2016-11-25", "birth_place": "Biran, Cuba", "person_types": ["politician", "revolutionary"], "ideology_tags": ["communist", "marxist-leninist"], "bio_short": "Cuban revolutionary and leader of Cuba."},
    {"wikidata_id": "Q181529", "name": "Salvador Allende", "birth_date": "1908-06-26", "death_date": "1973-09-11", "birth_place": "Valparaiso, Chile", "person_types": ["politician", "physician"], "ideology_tags": ["socialist", "marxist"], "bio_short": "Chilean socialist president, overthrown in 1973 coup."},
    {"wikidata_id": "Q182658", "name": "Hugo Chavez", "birth_date": "1954-07-28", "death_date": "2013-03-05", "birth_place": "Sabaneta, Venezuela", "person_types": ["politician", "military"], "ideology_tags": ["socialist", "bolivarian"], "bio_short": "Venezuelan president and leader of Bolivarian Revolution."},
    {"wikidata_id": "Q11748", "name": "Evo Morales", "birth_date": "1959-10-26", "death_date": None, "birth_place": "Orinoca, Bolivia", "person_types": ["politician", "activist"], "ideology_tags": ["socialist", "indigenous rights"], "bio_short": "Bolivian president, first indigenous head of state."},
    {"wikidata_id": "Q312190", "name": "Subcomandante Marcos", "birth_date": "1957-06-19", "death_date": None, "birth_place": "Tampico, Mexico", "person_types": ["revolutionary", "writer"], "ideology_tags": ["zapatista", "libertarian socialist"], "bio_short": "Mexican insurgent and spokesperson for the EZLN."},
    
    # African revolutionaries
    {"wikidata_id": "Q166092", "name": "Thomas Sankara", "birth_date": "1949-12-21", "death_date": "1987-10-15", "birth_place": "Yako, Burkina Faso", "person_types": ["politician", "revolutionary", "military"], "ideology_tags": ["marxist", "pan-africanist"], "bio_short": "Burkinabe revolutionary, 'Africa's Che Guevara'."},
    {"wikidata_id": "Q36602", "name": "Patrice Lumumba", "birth_date": "1925-07-02", "death_date": "1961-01-17", "birth_place": "Onalua, Congo", "person_types": ["politician"], "ideology_tags": ["socialist", "pan-africanist", "anti-colonialist"], "bio_short": "First Prime Minister of independent Congo."},
    {"wikidata_id": "Q2416", "name": "Nelson Mandela", "birth_date": "1918-07-18", "death_date": "2013-12-05", "birth_place": "Mvezo, South Africa", "person_types": ["politician", "activist"], "ideology_tags": ["socialist", "anti-apartheid"], "bio_short": "South African anti-apartheid revolutionary and president."},
    {"wikidata_id": "Q193660", "name": "Kwame Nkrumah", "birth_date": "1909-09-21", "death_date": "1972-04-27", "birth_place": "Nkroful, Ghana", "person_types": ["politician"], "ideology_tags": ["socialist", "pan-africanist"], "bio_short": "Ghanaian independence leader and pan-Africanist."},
    {"wikidata_id": "Q188586", "name": "Amilcar Cabral", "birth_date": "1924-09-12", "death_date": "1973-01-20", "birth_place": "Bafata, Guinea-Bissau", "person_types": ["revolutionary", "writer"], "ideology_tags": ["marxist", "anti-colonialist"], "bio_short": "Guinea-Bissauan revolutionary and theorist."},
    {"wikidata_id": "Q57371", "name": "Julius Nyerere", "birth_date": "1922-04-13", "death_date": "1999-10-14", "birth_place": "Butiama, Tanzania", "person_types": ["politician", "philosopher"], "ideology_tags": ["socialist", "ujamaa"], "bio_short": "Tanzanian president who developed African socialism."},
    
    # Asian revolutionaries
    {"wikidata_id": "Q12749", "name": "Ho Chi Minh", "birth_date": "1890-05-19", "death_date": "1969-09-02", "birth_place": "Nghe An, Vietnam", "person_types": ["politician", "revolutionary"], "ideology_tags": ["communist", "nationalist"], "bio_short": "Vietnamese revolutionary leader."},
    {"wikidata_id": "Q216", "name": "Josip Broz Tito", "birth_date": "1892-05-07", "death_date": "1980-05-04", "birth_place": "Kumrovec, Croatia", "person_types": ["politician", "revolutionary", "military"], "ideology_tags": ["communist", "titoism"], "bio_short": "Yugoslav communist leader."},
    {"wikidata_id": "Q42519", "name": "Kim Il-sung", "birth_date": "1912-04-15", "death_date": "1994-07-08", "birth_place": "Mangyongdae, Korea", "person_types": ["politician"], "ideology_tags": ["communist", "juche"], "bio_short": "Founder of North Korea."},
    {"wikidata_id": "Q9574", "name": "Pol Pot", "birth_date": "1925-05-19", "death_date": "1998-04-15", "birth_place": "Prek Sbauv, Cambodia", "person_types": ["politician"], "ideology_tags": ["communist"], "bio_short": "Leader of Khmer Rouge."},
    
    # European socialists
    {"wikidata_id": "Q76", "name": "Jean Jaures", "birth_date": "1859-09-03", "death_date": "1914-07-31", "birth_place": "Castres, France", "person_types": ["politician", "philosopher"], "ideology_tags": ["socialist"], "bio_short": "French socialist leader, assassinated before WWI."},
    {"wikidata_id": "Q44520", "name": "August Bebel", "birth_date": "1840-02-22", "death_date": "1913-08-13", "birth_place": "Cologne, Germany", "person_types": ["politician"], "ideology_tags": ["socialist", "marxist"], "bio_short": "German social democratic politician."},
    {"wikidata_id": "Q57455", "name": "Karl Kautsky", "birth_date": "1854-10-16", "death_date": "1938-10-17", "birth_place": "Prague, Austria", "person_types": ["philosopher", "politician"], "ideology_tags": ["marxist", "social democrat"], "bio_short": "Czech-Austrian Marxist theoretician."},
    {"wikidata_id": "Q60045", "name": "Eduard Bernstein", "birth_date": "1850-01-06", "death_date": "1932-12-18", "birth_place": "Berlin, Germany", "person_types": ["politician", "philosopher"], "ideology_tags": ["socialist", "revisionist"], "bio_short": "German social democratic theorist."},
    {"wikidata_id": "Q181659", "name": "Karl Liebknecht", "birth_date": "1871-08-13", "death_date": "1919-01-15", "birth_place": "Leipzig, Germany", "person_types": ["politician", "revolutionary"], "ideology_tags": ["communist", "marxist"], "bio_short": "German socialist, co-founder of Spartacist League."},
    
    # American socialists
    {"wikidata_id": "Q193459", "name": "Eugene V. Debs", "birth_date": "1855-11-05", "death_date": "1926-10-20", "birth_place": "Terre Haute, Indiana", "person_types": ["politician", "labor_leader"], "ideology_tags": ["socialist"], "bio_short": "American socialist and union leader."},
    {"wikidata_id": "Q233876", "name": "Mother Jones", "birth_date": "1837-08-01", "death_date": "1930-11-30", "birth_place": "Cork, Ireland", "person_types": ["activist", "labor_leader"], "ideology_tags": ["socialist", "labor"], "bio_short": "Irish-American labor organizer."},
    {"wikidata_id": "Q182765", "name": "Big Bill Haywood", "birth_date": "1869-02-04", "death_date": "1928-05-18", "birth_place": "Salt Lake City, Utah", "person_types": ["labor_leader", "activist"], "ideology_tags": ["socialist", "syndicalist"], "bio_short": "American labor leader, founder of IWW."},
    {"wikidata_id": "Q561", "name": "Angela Davis", "birth_date": "1944-01-26", "death_date": None, "birth_place": "Birmingham, Alabama", "person_types": ["activist", "philosopher", "academic"], "ideology_tags": ["communist", "feminist", "anti-racist"], "bio_short": "American political activist and academic."},
    {"wikidata_id": "Q215562", "name": "Malcolm X", "birth_date": "1925-05-19", "death_date": "1965-02-21", "birth_place": "Omaha, Nebraska", "person_types": ["activist"], "ideology_tags": ["black nationalist", "socialist"], "bio_short": "American Muslim minister and human rights activist."},
    {"wikidata_id": "Q41094", "name": "Martin Luther King Jr.", "birth_date": "1929-01-15", "death_date": "1968-04-04", "birth_place": "Atlanta, Georgia", "person_types": ["activist", "minister"], "ideology_tags": ["democratic socialist", "civil rights"], "bio_short": "American civil rights leader."},
    {"wikidata_id": "Q5586", "name": "Huey P. Newton", "birth_date": "1942-02-17", "death_date": "1989-08-22", "birth_place": "Monroe, Louisiana", "person_types": ["activist", "revolutionary"], "ideology_tags": ["socialist", "black panther"], "bio_short": "Co-founder of the Black Panther Party."},
    {"wikidata_id": "Q297524", "name": "Fred Hampton", "birth_date": "1948-08-30", "death_date": "1969-12-04", "birth_place": "Summit, Illinois", "person_types": ["activist", "revolutionary"], "ideology_tags": ["socialist", "black panther"], "bio_short": "Black Panther Party leader, assassinated by FBI."},
    
    # Contemporary leftists
    {"wikidata_id": "Q9440", "name": "Noam Chomsky", "birth_date": "1928-12-07", "death_date": None, "birth_place": "Philadelphia, Pennsylvania", "person_types": ["linguist", "philosopher", "activist"], "ideology_tags": ["anarcho-syndicalist", "libertarian socialist"], "bio_short": "American linguist and political activist."},
    {"wikidata_id": "Q200768", "name": "Howard Zinn", "birth_date": "1922-08-24", "death_date": "2010-01-27", "birth_place": "Brooklyn, New York", "person_types": ["historian", "activist"], "ideology_tags": ["socialist", "anarchist"], "bio_short": "American historian and activist, author of A People's History."},
    {"wikidata_id": "Q353030", "name": "Slavoj Zizek", "birth_date": "1949-03-21", "death_date": None, "birth_place": "Ljubljana, Slovenia", "person_types": ["philosopher"], "ideology_tags": ["marxist", "lacanian"], "bio_short": "Slovenian philosopher and cultural critic."},
    {"wikidata_id": "Q352160", "name": "David Harvey", "birth_date": "1935-10-31", "death_date": None, "birth_place": "Gillingham, England", "person_types": ["geographer", "academic"], "ideology_tags": ["marxist"], "bio_short": "British Marxist geographer."},
    {"wikidata_id": "Q193857", "name": "Cornel West", "birth_date": "1953-06-02", "death_date": None, "birth_place": "Tulsa, Oklahoma", "person_types": ["philosopher", "activist"], "ideology_tags": ["socialist", "christian socialist"], "bio_short": "American philosopher and political activist."},
    {"wikidata_id": "Q60208", "name": "Bernie Sanders", "birth_date": "1941-09-08", "death_date": None, "birth_place": "Brooklyn, New York", "person_types": ["politician"], "ideology_tags": ["democratic socialist"], "bio_short": "American senator and presidential candidate."},
    {"wikidata_id": "Q82866", "name": "Alexandria Ocasio-Cortez", "birth_date": "1989-10-13", "death_date": None, "birth_place": "Bronx, New York", "person_types": ["politician"], "ideology_tags": ["democratic socialist"], "bio_short": "American congresswoman."},
    {"wikidata_id": "Q192831", "name": "Jeremy Corbyn", "birth_date": "1949-05-26", "death_date": None, "birth_place": "Chippenham, England", "person_types": ["politician"], "ideology_tags": ["socialist"], "bio_short": "British politician, former Labour leader."},
    {"wikidata_id": "Q298889", "name": "Jean-Luc Melenchon", "birth_date": "1951-08-19", "death_date": None, "birth_place": "Tangier, Morocco", "person_types": ["politician"], "ideology_tags": ["socialist", "ecosocialist"], "bio_short": "French politician, leader of La France Insoumise."},
    
    # Theorists and writers
    {"wikidata_id": "Q208602", "name": "Frantz Fanon", "birth_date": "1925-07-20", "death_date": "1961-12-06", "birth_place": "Fort-de-France, Martinique", "person_types": ["philosopher", "psychiatrist", "writer"], "ideology_tags": ["marxist", "anti-colonialist"], "bio_short": "Martinican psychiatrist and political philosopher."},
    {"wikidata_id": "Q211182", "name": "Paulo Freire", "birth_date": "1921-09-19", "death_date": "1997-05-02", "birth_place": "Recife, Brazil", "person_types": ["educator", "philosopher"], "ideology_tags": ["socialist", "liberation theology"], "bio_short": "Brazilian educator, author of Pedagogy of the Oppressed."},
    {"wikidata_id": "Q23461", "name": "Simone de Beauvoir", "birth_date": "1908-01-09", "death_date": "1986-04-14", "birth_place": "Paris, France", "person_types": ["philosopher", "writer"], "ideology_tags": ["socialist", "feminist", "existentialist"], "bio_short": "French philosopher and feminist theorist."},
    {"wikidata_id": "Q39688", "name": "Jean-Paul Sartre", "birth_date": "1905-06-21", "death_date": "1980-04-15", "birth_place": "Paris, France", "person_types": ["philosopher", "writer"], "ideology_tags": ["marxist", "existentialist"], "bio_short": "French philosopher, playwright, and political activist."},
    {"wikidata_id": "Q44421", "name": "Herbert Marcuse", "birth_date": "1898-07-19", "death_date": "1979-07-29", "birth_place": "Berlin, Germany", "person_types": ["philosopher"], "ideology_tags": ["marxist", "frankfurt school"], "bio_short": "German-American philosopher, critical theorist."},
    {"wikidata_id": "Q57182", "name": "Theodor Adorno", "birth_date": "1903-09-11", "death_date": "1969-08-06", "birth_place": "Frankfurt, Germany", "person_types": ["philosopher", "sociologist"], "ideology_tags": ["marxist", "frankfurt school"], "bio_short": "German philosopher and sociologist."},
    {"wikidata_id": "Q44403", "name": "Walter Benjamin", "birth_date": "1892-07-15", "death_date": "1940-09-26", "birth_place": "Berlin, Germany", "person_types": ["philosopher", "critic"], "ideology_tags": ["marxist"], "bio_short": "German philosopher and cultural critic."},
    {"wikidata_id": "Q46599", "name": "Louis Althusser", "birth_date": "1918-10-16", "death_date": "1990-10-22", "birth_place": "Birmandreïs, Algeria", "person_types": ["philosopher"], "ideology_tags": ["marxist", "structuralist"], "bio_short": "French Marxist philosopher."},
    {"wikidata_id": "Q84550", "name": "Georg Lukacs", "birth_date": "1885-04-13", "death_date": "1971-06-04", "birth_place": "Budapest, Hungary", "person_types": ["philosopher", "critic"], "ideology_tags": ["marxist"], "bio_short": "Hungarian Marxist philosopher and literary critic."},
    {"wikidata_id": "Q61064", "name": "CLR James", "birth_date": "1901-01-04", "death_date": "1989-05-31", "birth_place": "Caroni, Trinidad", "person_types": ["historian", "writer", "activist"], "ideology_tags": ["trotskyist", "pan-africanist"], "bio_short": "Trinidadian historian and socialist theorist."},
]

# Historical events
HISTORICAL_EVENTS = [
    # Revolutions
    {"wikidata_id": "Q8646", "title": "French Revolution", "start_date": "1789-05-05", "end_date": "1799-11-09", "category": "political", "event_type": "revolution", "location_name": "France", "description": "Revolution that overthrew the French monarchy and established the First Republic."},
    {"wikidata_id": "Q41493", "title": "Paris Commune", "start_date": "1871-03-18", "end_date": "1871-05-28", "category": "political", "event_type": "revolution", "location_name": "Paris, France", "description": "Revolutionary socialist government that ruled Paris."},
    {"wikidata_id": "Q38142", "title": "Russian Revolution", "start_date": "1917-03-08", "end_date": "1917-11-08", "category": "political", "event_type": "revolution", "location_name": "Russia", "description": "Revolution that overthrew the Tsarist autocracy."},
    {"wikidata_id": "Q188712", "title": "October Revolution", "start_date": "1917-11-07", "end_date": "1917-11-08", "category": "political", "event_type": "revolution", "location_name": "Petrograd, Russia", "description": "Bolshevik seizure of power."},
    {"wikidata_id": "Q152389", "title": "German Revolution", "start_date": "1918-11-03", "end_date": "1919-08-11", "category": "political", "event_type": "revolution", "location_name": "Germany", "description": "Revolution that overthrew the German Empire."},
    {"wikidata_id": "Q27997", "title": "Hungarian Soviet Republic", "start_date": "1919-03-21", "end_date": "1919-08-01", "category": "political", "event_type": "revolution", "location_name": "Hungary", "description": "Short-lived communist state in Hungary."},
    {"wikidata_id": "Q8676", "title": "Chinese Revolution", "start_date": "1949-10-01", "end_date": "1949-10-01", "category": "political", "event_type": "revolution", "location_name": "China", "description": "Communist victory in the Chinese Civil War."},
    {"wikidata_id": "Q11266", "title": "Cuban Revolution", "start_date": "1953-07-26", "end_date": "1959-01-01", "category": "political", "event_type": "revolution", "location_name": "Cuba", "description": "Armed revolt that overthrew Batista dictatorship."},
    {"wikidata_id": "Q155936", "title": "Sandinista Revolution", "start_date": "1979-07-19", "end_date": "1979-07-19", "category": "political", "event_type": "revolution", "location_name": "Nicaragua", "description": "Revolution that overthrew the Somoza dictatorship."},
    {"wikidata_id": "Q179848", "title": "Iranian Revolution", "start_date": "1979-01-01", "end_date": "1979-04-01", "category": "political", "event_type": "revolution", "location_name": "Iran", "description": "Revolution that overthrew the Shah."},
    
    # Labor movements and strikes
    {"wikidata_id": "Q156788", "title": "Haymarket Affair", "start_date": "1886-05-04", "end_date": "1886-05-04", "category": "social", "event_type": "strike", "location_name": "Chicago, USA", "description": "Labor protest and bombing that became symbol of labor movement."},
    {"wikidata_id": "Q731469", "title": "Pullman Strike", "start_date": "1894-05-11", "end_date": "1894-07-20", "category": "social", "event_type": "strike", "location_name": "USA", "description": "Nationwide railroad strike."},
    {"wikidata_id": "Q2478889", "title": "Great Railroad Strike of 1877", "start_date": "1877-07-14", "end_date": "1877-09-04", "category": "social", "event_type": "strike", "location_name": "USA", "description": "First major nationwide strike in United States."},
    {"wikidata_id": "Q1755282", "title": "British General Strike", "start_date": "1926-05-04", "end_date": "1926-05-12", "category": "social", "event_type": "strike", "location_name": "United Kingdom", "description": "General strike called by TUC in support of miners."},
    {"wikidata_id": "Q748178", "title": "May 1968 events", "start_date": "1968-05-02", "end_date": "1968-06-23", "category": "social", "event_type": "protest", "location_name": "France", "description": "Period of civil unrest in France."},
    {"wikidata_id": "Q2720699", "title": "Gdansk Shipyard Strike", "start_date": "1980-08-14", "end_date": "1980-08-31", "category": "social", "event_type": "strike", "location_name": "Gdansk, Poland", "description": "Strike that led to formation of Solidarity."},
    
    # Civil wars and conflicts
    {"wikidata_id": "Q10874", "title": "Spanish Civil War", "start_date": "1936-07-17", "end_date": "1939-04-01", "category": "military", "event_type": "civil_war", "location_name": "Spain", "description": "War between Republicans and Nationalists."},
    {"wikidata_id": "Q8678", "title": "Russian Civil War", "start_date": "1917-11-07", "end_date": "1922-10-25", "category": "military", "event_type": "civil_war", "location_name": "Russia", "description": "War between Red and White armies."},
    {"wikidata_id": "Q8740", "title": "Chinese Civil War", "start_date": "1927-08-01", "end_date": "1950-05-01", "category": "military", "event_type": "civil_war", "location_name": "China", "description": "War between Communists and Nationalists."},
    {"wikidata_id": "Q8754", "title": "Korean War", "start_date": "1950-06-25", "end_date": "1953-07-27", "category": "military", "event_type": "war", "location_name": "Korea", "description": "War between North and South Korea."},
    {"wikidata_id": "Q8663", "title": "Vietnam War", "start_date": "1955-11-01", "end_date": "1975-04-30", "category": "military", "event_type": "war", "location_name": "Vietnam", "description": "War between North Vietnam and USA/South Vietnam."},
    
    # Independence movements
    {"wikidata_id": "Q134583", "title": "Indian Independence", "start_date": "1947-08-15", "end_date": "1947-08-15", "category": "political", "event_type": "independence", "location_name": "India", "description": "India gains independence from British rule."},
    {"wikidata_id": "Q188748", "title": "Algerian War of Independence", "start_date": "1954-11-01", "end_date": "1962-07-05", "category": "military", "event_type": "independence", "location_name": "Algeria", "description": "War for Algerian independence from France."},
    {"wikidata_id": "Q12131", "title": "Congo Independence", "start_date": "1960-06-30", "end_date": "1960-06-30", "category": "political", "event_type": "independence", "location_name": "Congo", "description": "Congo gains independence from Belgium."},
    
    # Coups and repression
    {"wikidata_id": "Q13441", "title": "1973 Chilean coup", "start_date": "1973-09-11", "end_date": "1973-09-11", "category": "political", "event_type": "coup", "location_name": "Chile", "description": "Military coup overthrows Allende government."},
    {"wikidata_id": "Q379894", "title": "Operation Condor", "start_date": "1975-01-01", "end_date": "1989-01-01", "category": "political", "event_type": "repression", "location_name": "South America", "description": "Campaign of political repression by South American dictatorships."},
    {"wikidata_id": "Q151190", "title": "Indonesian Mass Killings", "start_date": "1965-10-01", "end_date": "1966-07-01", "category": "political", "event_type": "repression", "location_name": "Indonesia", "description": "Anti-communist purge killing up to 1 million people."},
    
    # Protests and movements
    {"wikidata_id": "Q49089", "title": "Tiananmen Square protests", "start_date": "1989-04-15", "end_date": "1989-06-04", "category": "political", "event_type": "protest", "location_name": "Beijing, China", "description": "Pro-democracy protests brutally suppressed."},
    {"wikidata_id": "Q206886", "title": "Prague Spring", "start_date": "1968-01-05", "end_date": "1968-08-21", "category": "political", "event_type": "reform", "location_name": "Czechoslovakia", "description": "Period of political liberalization crushed by Soviet invasion."},
    {"wikidata_id": "Q41553", "title": "Fall of the Berlin Wall", "start_date": "1989-11-09", "end_date": "1989-11-09", "category": "political", "event_type": "revolution", "location_name": "Berlin, Germany", "description": "Symbolic end of Cold War division of Europe."},
    {"wikidata_id": "Q7794", "title": "Occupy Wall Street", "start_date": "2011-09-17", "end_date": "2011-11-15", "category": "social", "event_type": "protest", "location_name": "New York, USA", "description": "Protest against economic inequality."},
    {"wikidata_id": "Q10298668", "title": "Arab Spring", "start_date": "2010-12-18", "end_date": "2012-12-01", "category": "political", "event_type": "revolution", "location_name": "Middle East", "description": "Wave of pro-democracy protests across Arab world."},
    {"wikidata_id": "Q7937688", "title": "Gezi Park protests", "start_date": "2013-05-28", "end_date": "2013-08-01", "category": "political", "event_type": "protest", "location_name": "Istanbul, Turkey", "description": "Civil unrest in Turkey."},
]

# Books
LEFTIST_BOOKS = [
    {"wikidata_id": "Q133641", "title": "The Communist Manifesto", "publication_year": 1848, "book_type": "manifesto", "topics": ["communism", "class struggle"], "marxists_url": "https://www.marxists.org/archive/marx/works/1848/communist-manifesto/", "authors": ["Q9061", "Q9916"]},
    {"wikidata_id": "Q214947", "title": "Das Kapital", "publication_year": 1867, "book_type": "political_theory", "topics": ["capitalism", "economics"], "marxists_url": "https://www.marxists.org/archive/marx/works/1867-c1/", "authors": ["Q9061"]},
    {"wikidata_id": "Q720891", "title": "State and Revolution", "publication_year": 1917, "book_type": "political_theory", "topics": ["state", "revolution"], "marxists_url": "https://www.marxists.org/archive/lenin/works/1917/staterev/", "authors": ["Q10518"]},
    {"wikidata_id": "Q1231529", "title": "The Conquest of Bread", "publication_year": 1892, "book_type": "political_theory", "topics": ["anarchism", "economics"], "marxists_url": "https://www.marxists.org/reference/archive/kropotkin-peter/1892/conquest-bread.htm", "authors": ["Q312817"]},
    {"wikidata_id": "Q830105", "title": "Mutual Aid: A Factor of Evolution", "publication_year": 1902, "book_type": "philosophy", "topics": ["anarchism", "evolution"], "marxists_url": "https://www.marxists.org/reference/archive/kropotkin-peter/1902/mutual-aid/", "authors": ["Q312817"]},
    {"wikidata_id": "Q1200988", "title": "Prison Notebooks", "publication_year": 1948, "book_type": "political_theory", "topics": ["hegemony", "marxism"], "marxists_url": "https://www.marxists.org/archive/gramsci/prison_notebooks/", "authors": ["Q5593"]},
    {"wikidata_id": "Q3057", "title": "What Is to Be Done?", "publication_year": 1902, "book_type": "political_theory", "topics": ["revolution", "party"], "marxists_url": "https://www.marxists.org/archive/lenin/works/1901/witbd/", "authors": ["Q10518"]},
    {"wikidata_id": "Q1066778", "title": "Reform or Revolution", "publication_year": 1899, "book_type": "political_theory", "topics": ["socialism", "reform"], "marxists_url": "https://www.marxists.org/archive/luxemburg/1900/reform-revolution/", "authors": ["Q3621"]},
    {"wikidata_id": "Q2368312", "title": "The Wretched of the Earth", "publication_year": 1961, "book_type": "political_theory", "topics": ["colonialism", "decolonization"], "authors": ["Q208602"]},
    {"wikidata_id": "Q1066694", "title": "Pedagogy of the Oppressed", "publication_year": 1968, "book_type": "philosophy", "topics": ["education", "liberation"], "authors": ["Q211182"]},
    {"wikidata_id": "Q1066727", "title": "A People's History of the United States", "publication_year": 1980, "book_type": "history", "topics": ["US history", "class"], "authors": ["Q200768"]},
    {"wikidata_id": "Q849126", "title": "Manufacturing Consent", "publication_year": 1988, "book_type": "political_theory", "topics": ["media", "propaganda"], "authors": ["Q9440"]},
    {"wikidata_id": "Q1154758", "title": "The Second Sex", "publication_year": 1949, "book_type": "philosophy", "topics": ["feminism", "existentialism"], "authors": ["Q23461"]},
    {"wikidata_id": "Q606776", "title": "One-Dimensional Man", "publication_year": 1964, "book_type": "philosophy", "topics": ["capitalism", "technology"], "authors": ["Q44421"]},
    {"wikidata_id": "Q1754532", "title": "History and Class Consciousness", "publication_year": 1923, "book_type": "philosophy", "topics": ["marxism", "reification"], "authors": ["Q84550"]},
    {"wikidata_id": "Q1171802", "title": "The Black Jacobins", "publication_year": 1938, "book_type": "history", "topics": ["Haiti", "revolution"], "authors": ["Q61064"]},
    {"wikidata_id": "Q2298136", "title": "Imperialism, the Highest Stage of Capitalism", "publication_year": 1917, "book_type": "political_theory", "topics": ["imperialism", "capitalism"], "marxists_url": "https://www.marxists.org/archive/lenin/works/1916/imp-hsc/", "authors": ["Q10518"]},
    {"wikidata_id": "Q3520628", "title": "The Origin of the Family, Private Property and the State", "publication_year": 1884, "book_type": "political_theory", "topics": ["family", "state"], "marxists_url": "https://www.marxists.org/archive/marx/works/1884/origin-family/", "authors": ["Q9916"]},
    {"wikidata_id": "Q582939", "title": "Quotations from Chairman Mao", "publication_year": 1964, "book_type": "manifesto", "topics": ["maoism", "revolution"], "authors": ["Q7378"]},
    {"wikidata_id": "Q2078234", "title": "Guerrilla Warfare", "publication_year": 1961, "book_type": "military", "topics": ["guerrilla", "revolution"], "authors": ["Q5575"]},
]
